### ISSUE TITLE
Not possible to delete uptime check (google_monitoring_uptime_check_config) 

### ISSUE THREAD

**Issue by jaceq** [hashicorp/terraform-provider-google#10176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.0.5

provider: 3.86.0
### Affected Resource(s)

google_monitoring_uptime_check_config

### Debug Output
```
---[ REQUEST ]---------------------------------------
DELETE /v3/projects/some-project/uptimeCheckConfigs/someCheck?alt=json HTTP/1.1
Host: monitoring.googleapis.com
User-Agent: Terraform/1.0.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/3.86.0
Content-Type: application/json
Accept-Encoding: gzip
```

This get 400 back from API saying it contains invalid argument

### Panic Output
```
Error: Error when reading or editing UptimeCheckConfig: googleapi: Error 400: Request contains an invalid argument.
```

### Expected Behavior

Check should get deleted.

### Actual Behavior

Check doesn't get deleted and TF throws an error

### Steps to Reproduce

1. Configure an uptime check 
2. terraform apply
3. Change configuration in a way that forces a replacement (eg. hostname)
4. terraform apply (deletion fails)

### References

* #0000

b/305279561

**Comment by melinath** [comment]
I can't reproduce this - could you please add an example minimal terraform configuration that demonstrates this behavior?

**Comment by callensm** [comment]
I'm also encountering the same bug where a uptime check config period update forces a resource replacement and the API is failing on deletion with `Error: Error when reading or editing UptimeCheckConfig: googleapi: Error 400: Request contains an invalid argument.`

**Comment by uda** [comment]
I also encountered this issue exactly as described, an uptime check with a linked alert policy cannot be destroyed+created, I didn't check if just destroy works, which I assume will work because the policy depends on details from the uptime check and will be destroyed first so the uptime check delete won't fail.

For now, Since it isn't something we do often, I opted for the ugly workaround, deleted the relevant policies, planned and applied. The uptime checks were destroyed, created and then the alert policies were created from fresh, which is a good enough result for my use case.

**Comment by Pinolo** [comment]
This issue is solved/mitigated by the solution highlighted in https://github.com/hashicorp/terraform-provider-google/issues/3133#issuecomment-468783073

I only wish it was documented, since I think it's a common use case and nobody should be requested to infer the logical lifecycle of GCP resources behind a generic 400 error code

**Comment by jdurelli** [comment]
I will add an error message for 400s that mentions making sure all Alert Policies are deleted first.
