### ISSUE TITLE
Failing test(s): TestAccComputeRouterInterface_* (QUOTA_EXCEEDED: IN_USE_ADDRESSES)

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10215]
Failure rate: Currently 100% (less frequently prior to ~7 days ago)

Impacted tests:
- TestAccComputeRouterInterface_basic
- TestAccComputeRouterInterface_withTunnel
- TestAccComputeVpnTunnel_router
- TestAccComputeVpnTunnel_defaultTrafficSelectors

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/208057?buildTab=tests&expandedTest=3930948907344933945
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/208265?buildTab=tests&pager.currentPage=1&status=failed&expandedTest=5183945409174794622

Message:

```
Error: Error creating ForwardingRule: operation received error: error code "QUOTA_EXCEEDED", message: Quota 'IN_USE_ADDRESSES' exceeded.
```

**Comment by shuyama1** [comment]
All tests have passed since Oct 28 (only TestAccComputeRouterInterface_withTunnel failed once with an unrelated error). Current quota status for In-use IP addresses global: 6/50 (7 day usage peak: 12/50). @rileykarson Should we close this or are there any more steps needed to investigate this issue?

**Comment by rileykarson** [comment]
Nope, feel free to close it!
