### ISSUE TITLE
Support Spot VMs

### ISSUE THREAD

**Issue by balboah** [hashicorp/terraform-provider-google#10309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'm using preemtible instances today together with GKE autoscaling.
Just received the announcement from Google Cloud that they are switching to "Spot VMs".

I believe this feature should be added in the beta provider until GA.

### New or Affected Resource(s)

* google_container_node_pool
* google_compute_instance

### Potential Terraform Configuration

```tf
resource "google_container_node_pool" "primary_spotvm_nodes" {
  # ...

  node_config {
    spot  = true
    # ...
  }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/concepts/spot-vms
* Internal issue: http://b/202997221

**Comment by djetelina** [comment]
Hi, this might be a spam, and might go without saying, but please keep in mind that it affects GKE too.

gcloud cli
`gcloud beta container node-pools create POOL_NAME --cluster=CLUSTER_NAME --spot`

which is similar to preemptible node pools. So the syntax in node pools I'd expecet would be

```hcl
node_config {
    spot  = true
}
```

**Comment by MKaciuba** [comment]
Hi, any estimate on release date for this feature?

**Comment by scotte** [comment]
> Hi, any estimate on release date for this feature?

@MKaciuba It's available now in the "google-beta" provider. I used it yesterday. Since Google considers spot instances to be preview status, perhaps Terraform won't release it to the "google" provider until Google considers it GA? Just speculation, I have no idea...

**Comment by azmng** [comment]
Hi, any news regarding GCE support? I mean google_compute_instance resource, I was unable to find any reference in google-beta...

**Comment by ShaunHowell** [comment]
Hi, the `provisioning_model` field is in the [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#provisioning_model) under beta but isn't actually included in the 4.11.0 release ([link](https://github.com/hashicorp/terraform-provider-google-beta/blob/v4.11.0/google-beta/resource_compute_instance.go#L42)). It looks like [this](https://github.com/hashicorp/terraform-provider-google-beta/commit/c049cca6bfc534811cfd2ff4840b6dd5af15bda9) commit reverted its inclusion. 
Was this an accident? Will this be re-included soon?

**Comment by rvennam-lbg** [comment]
> 

I just tried provisioning a spot instance and it worked with 4.13.0 provider version.

**Comment by rileykarson** [comment]
I'm not sure why this would have been in the docs@4.11.0, as it was in the release notes for https://github.com/hashicorp/terraform-provider-google-beta/releases/tag/v4.12.0. There may have been a minor hiccup- sorry about that!

I _believe_ this issue is ready to be closed based on https://github.com/GoogleCloudPlatform/magic-modules/pull/5662. @shuyama1 or @andrewyz please correct me if you feel otherwise! I see the PR says "part of" rather than "closes" which generally means a change only partially addresses an issue, but that's an unspoken meaning and I can't spot anything missing.

**Comment by andrewyz** [comment]
There was some test failures in 4.11.0, so the commit was reverted and then released in 4.12.0. Not sure why the docs@4.11.0  didn't reflect this change.

**Comment by rileykarson** [comment]
Hmm- the docs appear to have been properly reverted (we've reverted the code and not the docs in the past, so I figured I'd check that!). @megan07 is there a way to check the registry's commit/tag for past versions? This probably isn't worth spending much time on since it's correct in latest, but I'm curious 🤷

@andrewyz can you confirm that we can close this issue now?

**Comment by andrewyz** [comment]
Yes, look good so far.
