### ISSUE TITLE
Terraform always replaces(destroy & create) GKE autopilot

### ISSUE THREAD

**Issue by kanjih** [hashicorp/terraform-provider-google#10522]
### Terraform Version
```
v1.0.8
```

### Affected Resource
* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "default" {
  name     = "test"
  location = "asia-northeast1"

  network    = {id of existing vpc}
  subnetwork = {id of existing subnetwork}

  enable_autopilot = true

  node_config {
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}
```

### Expected Behavior
When I exec terrafrom plan with the above same code, terraform shows there's no change and terraform won't do anything.

### Actual Behavior
When I exec terrafrom plan with the above same code, terraform says it will replace (destroy & create) the gke cluster even though there's no change.
If the code doens't have node_config, it won't happen.

### Steps to Reproduce
1. write the above code
2. call `terraform init`
3. call `terraform apply`
4. call `terraform apply` again

**Comment by c2thorn** [comment]
@kanjih `node_config.oauth_scopes` does not seem to be configurable with Autopilot enabled. I'd recommend removing the field since the backend will just replace your values automatically.

It'd be nice if the provider prevented you from trying to attempt this, but I'm not sure that is possible with how `node_config` is structured internally.
