### ISSUE TITLE
Substantially reduce MM setup complexity

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#10625]
One of the common patterns I see when Google-internal folks adopt MM is that they write a guide for themselves + their team on how to get set up- installing rbenv, various accessory tools (bundler, black, goimports) and so on. We could reduce the complexity of getting started using MM by finding a way to eliminate components, or packaging MM in a way that it takes less time to onboard (Docker, maybe?).

**Comment by upodroid** [comment]
I don't think MM is complicated to setup if we assume that developers know how to setup Language tooling such as rbenv, goenv/gvm, pyenv properly on their Macs.

I recently helped a collegue setup https://github.com/terraform-google-modules/terraform-google-lb-http which uses kitchen(Ruby). That project has a convenient docker image which imho abstracts dealing with dependencies but you have to deal with bad authentication(service account keys instead of using gcloud ADCs) and other hardcoded shenanigans.

**Comment by ScottSuarez** [comment]
+1 to containerized build option

**Comment by rileykarson** [comment]
https://googlecloudplatform.github.io/magic-modules/docs/getting-started/setup/#setting-up-a-container-based-environment
