### ISSUE TITLE
Documentation for deployment triggers on google_app_engine_standard_app_version zip deployment.

### ISSUE THREAD

**Issue by bajaco** [hashicorp/terraform-provider-google#10688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The app engine version is not redeployed when a hash change generates a new bucket object, unless the bucket object name is different from the previously used object. Nor does it change upon a new version if the bucket is set to use versioning. While I believe an option to trigger redeployment that could be set to either a new version or hash change would be optimal, I understand that this may be intended behavior. However, while I'm new to Terraform and should have read the plan more carefully to figure out what was going on, a note about including the hash in the file name would have been a huge help. It's somewhat unintuitive that the source zip object is updated but not the service that sources it. Or perhaps an example could be included with a filename derived from the archive file's md5. I apologize if this is intuitive to most people, it just took more searching than expected for me to figure it out.

### New or Affected Resource(s)

* google_app_engine_standard_app_version
* google_app_engine_flexible_app_version
* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
  # It would be great to have an option for redeployment triggers, but it may not be appropriate
  deployment {
    zip {
      source_url = "https://storage.googleapis.com/${google_storage_bucket.bucket.name}/${google_storage_bucket_object.service-archive.name}"
      redeploy {
        version = false
        source_hash = data.archive_file.service-source.output_md5
      }
    }
  }

# Or a note  in the docs
Note

App Engine App Versions are not redeployed unless there is a change to google_storage_bucket_object.name.
Use the archive object's hash in the name to trigger deployments on hash changes.
```

### References

* #5387
* #3793
* #1938

**Comment by SarahFrench** [comment]
I'm somewhat familiar with the older issue linked in the references of this issue description, and read about how there was some decision-making needed before making any changes to the provider itself.

I think documenting the workarounds is something we can definitely add in the documentation in the meantime, though the person who does it would need to go through the comments on those issues, especially https://github.com/hashicorp/terraform-provider-google/issues/1938, and test out the different options that could be documented (e.g. use of data sources, lifecycle meta arguments, choosing to include hashes in the file's path).

Because some manual work would be required to verify all the different options I want to size this as an M.

**Comment by ggtisc** [comment]
Currently it is possible to change the zip file and it detects the change making an `update-in-place`
