### ISSUE TITLE
Failing test(s): TestAccContainerCluster_withAuthenticatorGroupsConfig

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#10860]
Failure rate: 52% in Dec 2021

Impacted tests:
- TestAccContainerCluster_withAuthenticatorGroupsConfig

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/240006?buildTab=tests&expandedTest=1946850189227800554

Message:

```
Error 400: Security group name must start with gke-security-groups but got: <security group name that starts with that string>
```

**Comment by melinath** [comment]
This is still failling, but the error message has changed slightly:

```
Error: googleapi: Error 404: Not found: GAIA email lookup: gke-security-groups@<domain> does not exist or has been deleted.
```

https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=1946850189227800554

It's not clear that the linked PR actually fixed the underlying issue; the impacted test doesn't seem to have run on the PR for some reason.

**Comment by megan07** [comment]
I think this new error is likely because it's not an existing group in the domain, I don't have access to add it, but we could try it here: https://cloud.google.com/kubernetes-engine/docs/how-to/google-groups-rbac#setup-group
I'm not sure it will solve it, but I don't think it will hurt and worst case will bring us back to the original error.

**Comment by slevenick** [comment]
Added group, test passes now I believe
