### ISSUE TITLE
google_monitoring_uptime_check_config resource is always identified "change" wrongly

### ISSUE THREAD

**Issue by liuchenggang2014** [hashicorp/terraform-provider-google#10884]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.6.0

### Affected Resource(s)

google_monitoring_uptime_check_config

* google_XXXXX

### Terraform Configuration Files

https://github.com/liuchenggang2014/uptime_check/blob/main/single/https_uptimecheck.tf

```tf
resource "google_monitoring_uptime_check_config" "https" {
  display_name = "https-uptime-check"
  timeout      = "10s"
  period = "60s"

  http_check {
    path         = "/hc.html"
    port         = "443"
    use_ssl      = true
    validate_ssl = true
  }

  monitored_resource {
    type = "uptime_url"
    labels = {
      host       = "glb.goodvm.net"
    }
  }

}
```
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Debug Output

<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, run `terraform apply` with the environment variable `TF_LOG=DEBUG`. See the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html) for more information.
--->

### Panic Output

<!--- If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`. --->

### Expected Behavior

terraform apply first. the result is fine.
but when I execute "terraform apply" again w/o any change.  it should do nothing



<!--- What should have happened? --->

### Actual Behavior

it prompt me : "Note: Objects have changed outside of Terraform"

<!--- What actually happened? --->

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform apply`
2.  terraform apply

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: authenticating as a user instead of a service account? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

<!---
Note Google Cloud customers who are working with a dedicated Technical Account Manager / Customer Engineer: to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team
--->

**Comment by MatTerra** [comment]
👍🏽

**Comment by Ubaldo-Brea** [comment]
We are with the same problem in our project, this have be fixed

**Comment by dgteixeira** [comment]
Hello all, any update on this?

We can use a `ignore_changes` lifecycle block, but it is a not a ideal way.

Thanks!

**Comment by shuyama1** [comment]
Sorry for the delay on this issue. Would you mind sharing the debug log?

**Comment by shuyama1** [comment]
Could you try adding `project_id` to the `labels` block in your configuration and see if that solves your problem? Looks like it is required to be set in this case.

**Comment by Ubaldo-Brea** [comment]
Hi shuyama1, sorry my delay.
We  added project_id to labels Block, it was part of our code as you can see below. I´m attached actual config state, the terraform code used for this state and a terraform plan showing the problem.

actual config
============
# google_monitoring_uptime_check_config.url_https_check:
resource "google_monitoring_uptime_check_config" "url_https_check" {
    display_name     = "Uptime check"
    id               = "projects/projectx/uptimeCheckConfigs/uptime-check-pknFaR3gF7g"
    name             = "projects/projectx/uptimeCheckConfigs/uptime-check-pknFaR3gF7g"
    period           = "60s"
    project          = "projectx"
    selected_regions = [
        "EUROPE",
        "SOUTH_AMERICA",
        "ASIA_PACIFIC",
    ]
    timeout          = "60s"
    uptime_check_id  = "uptime-check-pknFaR3gF7g"

    http_check {
        headers        = {}
        mask_headers   = false
        path           = "/probe_files/potato"
        port           = 443
        request_method = "GET"
        use_ssl        = true
        validate_ssl   = true
    }

    monitored_resource {
        labels = {
            "host"       = "fileserver.host.com."
            "project_id" = "projectx"
        }
        type   = "uptime_url"
    }
}
============

actual terraform code
==============

resource "google_monitoring_uptime_check_config" "url_https_check" {
  project          = data.google_project.this.name
  display_name     = "uptime check"
  timeout          = "60s"
  period           = "60s"
  selected_regions = ["EUROPE", "SOUTH_AMERICA", "ASIA_PACIFIC"]
  http_check {
    request_method = "GET"
    path           = google_storage_bucket_object.probe_folder_file.name
    port           = "443"
    use_ssl        = true
    validate_ssl   = true
  }
  monitored_resource {
    type = "uptime_url"
    labels = {
      project_id = var.project_id
      host       = google_dns_record_set.fileserver_public.name
    }
  }
  depends_on = [google_compute_managed_ssl_certificate.fileserver]
}

resource "google_monitoring_alert_policy" "alert_policy" {
  display_name = "HTTP Uptime Check Alerting Policy"
  combiner     = "OR"
  conditions {
    display_name = "HTTP Uptime Check Alert"
    condition_threshold {
      filter     = "metric.type=\"monitoring.googleapis.com/uptime_check/check_passed\" AND metric.label.check_id=\"${google_monitoring_uptime_check_config.url_https_check.uptime_check_id}\" AND resource.type=\"uptime_url\""
      duration   = "60s"
      comparison = "COMPARISON_GT"
      aggregations {
        alignment_period     = "300s"
        per_series_aligner   = "ALIGN_NEXT_OLDER"
        cross_series_reducer = "REDUCE_COUNT_FALSE"
        group_by_fields      = ["resource.label.*"]
      }
      threshold_value = "1"
      trigger {
        count = "1"
      }
    }
  }
  notification_channels = ["${google_monitoring_notification_channel.basic.id}"]
}
resource "google_monitoring_notification_channel" "basic" {
  display_name = "Migration team Mailing list"
  type         = "email"
  labels = {
    email_address = "test@email"
  }
}
==============

terraform plan output
===============
google_service_account.pubsub_subscriber: Refreshing state... [id=projects/Projectx/serviceAccounts/pub-sub-subscriber-sa@Projectx.iam.gserviceaccount.com]
google_project_iam_custom_role.this: Refreshing state... [id=projects/Projectx/roles/storagegetonly]
google_monitoring_dashboard.summary_table: Refreshing state... [id=projects/474803099999/dashboards/8a5dbb59-5c0a-48e1-b7bd-39b7d2f1163e]
google_monitoring_notification_channel.basic: Refreshing state... [id=projects/Projectx/notificationChannels/165774384625439999999]
google_dns_managed_zone.projectx_public: Refreshing state... [id=projects/Projectx/managedZones/projectx]
google_dns_managed_zone.projectx_private: Refreshing state... [id=projects/Projectx/managedZones/projectx-private]
google_dns_record_set.fileserver_private: Refreshing state... [id=projects/Projectx/managedZones/projectx-private/rrsets/fileserver.projectx.host.com./CNAME]
google_compute_global_address.default: Refreshing state... [id=projects/Projectx/global/addresses/Projectx-public-ip]
google_project_service.this["compute.googleapis.com"]: Refreshing state... [id=Projectx/compute.googleapis.com]
google_storage_bucket.logging: Refreshing state... [id=Projectx-logging]
google_project_iam_member.default["roles/editor|group:test@projectx.com"]: Refreshing state... [id=Projectx/roles/editor/group:test@projectx.com]
google_project_iam_member.default["roles/iam.serviceAccountTokenCreator|group:test@projectx.com"]: Refreshing state... [id=Projectx/roles/iam.serviceAccountTokenCreator/group:test@projectx.com]
google_project_iam_member.default["roles/pubsub.admin|group:test@projectx.com"]: Refreshing state... [id=Projectx/roles/pubsub.admin/group:test@projectx.com]
google_project_service.this["servicenetworking.googleapis.com"]: Refreshing state... [id=Projectx/servicenetworking.googleapis.com]
google_project_service.this["pubsub.googleapis.com"]: Refreshing state... [id=Projectx/pubsub.googleapis.com]
google_project_service.this["iam.googleapis.com"]: Refreshing state... [id=Projectx/iam.googleapis.com]
google_project_service.this["dns.googleapis.com"]: Refreshing state... [id=Projectx/dns.googleapis.com]
google_project_iam_member.default["roles/viewer|user:micael.g.soares@projectx.com"]: Refreshing state... [id=Projectx/roles/viewer/user:micael.g.soares@projectx.com]
google_project_iam_member.default["roles/logging.admin|group:test@projectx.com"]: Refreshing state... [id=Projectx/roles/logging.admin/group:test@projectx.com]
google_project_iam_member.default["roles/logging.admin|group:test2@projectx.com"]: Refreshing state... [id=Projectx/roles/logging.admin/group:test2@projectx.com]
google_project_iam_member.default["roles/editor|group:test1@projectx.com"]: Refreshing state... [id=Projectx/roles/editor/group:test1@projectx.com]
google_project_iam_member.default["roles/storage.admin|group:test@projectx.com"]: Refreshing state... [id=Projectx/roles/storage.admin/group:test@projectx.com]
google_project_iam_member.default["roles/pubsub.admin|group:test1@projectx.com"]: Refreshing state... [id=Projectx/roles/pubsub.admin/group:test1@projectx.com]
google_project_iam_member.default["roles/editor|group:test2@projectx.com"]: Refreshing state... [id=Projectx/roles/editor/group:test2@projectx.com]
google_project_iam_member.default["roles/iam.serviceAccountTokenCreator|group:test1@projectx.com"]: Refreshing state... [id=Projectx/roles/iam.serviceAccountTokenCreator/group:test1@projectx.com]
google_project_iam_member.default["roles/iam.serviceAccountTokenCreator|group:test2@projectx.com"]: Refreshing state... [id=Projectx/roles/iam.serviceAccountTokenCreator/group:test2@projectx.com]
google_project_iam_member.default["roles/logging.admin|group:test1@projectx.com"]: Refreshing state... [id=Projectx/roles/logging.admin/group:test1@projectx.com]
google_project_iam_member.default["roles/pubsub.admin|group:test2@projectx.com"]: Refreshing state... [id=Projectx/roles/pubsub.admin/group:test2@projectx.com]
google_storage_bucket_iam_member.member: Refreshing state... [id=b/Projectx-logging/roles/storage.legacyBucketWriter/group:cloud-storage-analytics@google.com]
google_dns_record_set.fileserver_public: Refreshing state... [id=projects/Projectx/managedZones/projectx/rrsets/fileserver.projectx.host.com./A]
google_storage_bucket.software_files: Refreshing state... [id=projectx-sw-files]
google_storage_bucket_object.probe_folder_file: Refreshing state... [id=projectx-sw-files-probe_files/potato]
google_compute_backend_bucket.software_files: Refreshing state... [id=projects/Projectx/global/backendBuckets/files-image-backend-bucket]
google_storage_bucket_iam_member.default: Refreshing state... [id=b/projectx-sw-files/projects/Projectx/roles/storagegetonly/allUsers]
google_compute_managed_ssl_certificate.fileserver: Refreshing state... [id=projects/Projectx/global/sslCertificates/fileserver]
google_compute_url_map.backend_routing_header: Refreshing state... [id=projects/Projectx/global/urlMaps/bucket-url-map]
google_compute_target_http_proxy.external_lb_http: Refreshing state... [id=projects/Projectx/global/targetHttpProxies/external-lb-http-proxy]
google_compute_target_https_proxy.external_lb_https: Refreshing state... [id=projects/Projectx/global/targetHttpsProxies/external-lb-https-proxy]
google_monitoring_uptime_check_config.url_https_check: Refreshing state... [id=projects/Projectx/uptimeCheckConfigs/cperepo-uptime-check-pknFaR3gF7g]
google_compute_global_forwarding_rule.external_lb_http: Refreshing state... [id=projects/Projectx/global/forwardingRules/external-lb-http-rule]
google_compute_global_forwarding_rule.external_lb_https: Refreshing state... [id=projects/Projectx/global/forwardingRules/external-lb-https-rule]
google_monitoring_alert_policy.alert_policy: Refreshing state... [id=projects/Projectx/alertPolicies/16457511842054399999]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # google_project_iam_member.default["roles/editor|group:test@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/editor/group:test@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/editor|group:test2@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/editor/group:test2@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/editor|group:test1@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/editor/group:test1@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/iam.serviceAccountTokenCreator|group:test@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/iam.serviceAccountTokenCreator/group:test@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/iam.serviceAccountTokenCreator|group:test2@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/iam.serviceAccountTokenCreator/group:test2@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/iam.serviceAccountTokenCreator|group:test1@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/iam.serviceAccountTokenCreator/group:test1@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/logging.admin|group:test@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/logging.admin/group:test@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/logging.admin|group:test2@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/logging.admin/group:test2@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/logging.admin|group:test1@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/logging.admin/group:test1@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/pubsub.admin|group:test@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/pubsub.admin/group:test@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/pubsub.admin|group:test2@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/pubsub.admin/group:test2@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/pubsub.admin|group:test1@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/pubsub.admin/group:test1@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_project_iam_member.default["roles/storage.admin|group:test@projectx.com"] has changed
  ~ resource "google_project_iam_member" "default" {
      ~ etag    = "BwXYJ1vdVlE=" -> "BwXYwgx9q/c="
        id      = "Projectx/roles/storage.admin/group:test@projectx.com"
        # (3 unchanged attributes hidden)
    }

  # google_storage_bucket_iam_member.default has changed
  ~ resource "google_storage_bucket_iam_member" "default" {
      ~ etag   = "CAI=" -> "CAM="
        id     = "b/projectx-sw-files/projects/Projectx/roles/storagegetonly/allUsers"
        # (3 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_monitoring_uptime_check_config.url_https_check will be updated in-place
  ~ resource "google_monitoring_uptime_check_config" "url_https_check" {
        id               = "projects/Projectx/uptimeCheckConfigs/cperepo-uptime-check-pknFaR3gF7g"
        name             = "projects/Projectx/uptimeCheckConfigs/cperepo-uptime-check-pknFaR3gF7g"
        # (6 unchanged attributes hidden)

      ~ http_check {
          ~ path           = "/probe_files/potato" -> "probe_files/potato"
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
===============

I hope this can help.
Thank you

Ubaldo Brea

**Comment by shuyama1** [comment]
Hi @Ubaldo-Brea! Thanks for the information provided. Looks like the API is adding a `\` if the provided path does not begin with "/", and therefore it creates a permadiff for `path` field in Terraform. I am working on a PR to fix it and it should be out by tomorrow. Sorry for the delay on this issue!

Hi All! Does anyone still see some other errors other than the `path` issue I mentioned above after adding `project_id` to the `labels` block?
