### ISSUE TITLE
Failing test(s): TestAccCloudbuildWorkerPool_basic

### ISSUE THREAD

**Issue by shuyama1** [hashicorp/terraform-provider-google#10925]
Failure rate: 100% since Jan 08

Impacted tests:
- TestAccCloudbuildWorkerPool_basic

Nightly builds:
- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/245183?buildTab=tests&status=failed&expandedTest=-510496357074789472

Message:

```
Error: Error updating WorkerPool: googleapi: Error 400: invalid request: generic::invalid_argument: Request field update_mask: No field path named "worker_config".
```

**Comment by slevenick** [comment]
Likely linked to b/214436212

**Comment by melinath** [comment]
It looks like that bug is fixed, so hopefully this test will fix itself soon. For now it's still at 100%. https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/254727?buildTab=tests&expandedTest=-510496357074789472

**Comment by melinath** [comment]
The test is now failing due to a destroy/create permadiff on network_config since 2022-02-15: https://ci-oss.hashicorp.engineering/test/-510496357074789472?currentProjectId=GoogleCloud&branch=%3Cdefault%3E&expandedTest=id%3A353821%2Cbuild%3A%28id%3A257163%29

Hard to know when it kicked in since it was probably being obscured by the previous issue.

**Comment by slevenick** [comment]
Yup, b/218925489 covers this

**Comment by melinath** [comment]
This is now passing.
