### ISSUE TITLE
Why Terraform try to destroy resource that been imported?

### ISSUE THREAD

**Issue by niraj06** [hashicorp/terraform-provider-google#11043]
We have terraform module to create a google big query tables, using that module we try to import the table, so far good but, when we try to "terraform apply" it's trying to delete the import table and plan to re-create it.
This is a message in the console that will be destroyed
  # (because resource uses count or for_each)

Yes, the module has for_each been used, don't understand why it's forcing to drop resources?

resource "google_bigquery_table" "default" {
  for_each        = local.tables
  project         = each.value.project_id
  dataset_id      = each.value.dataset_id
  table_id        = each.key
  friendly_name   = each.value.friendly_name
  description     = each.value.description
  clustering      = try(each.value.options.clustering, null)
  expiration_time = try(each.value.options.expiration_time, null)
  labels          = each.value.labels
  schema          = file(each.value.schema)

  dynamic "encryption_configuration" {
    for_each = try(each.value.options.encryption_key, null) != null ? [""] : []
    content {
      kms_key_name = each.value.options.encryption_key
    }
  }

  dynamic "range_partitioning" {
    for_each = try(each.value.range_partitioning, null) != null ? [""] : []
    content {
      field = each.value.range_partitioning.field
      range {
        start    = each.value.range_partitioning.start
        end      = each.value.range_partitioning.end
        interval = each.value.range_partitioning.interval
      }
    }
  }

  dynamic "time_partitioning" {
    for_each = try(each.value.time_partitioning, null) != null ? [""] : []
    content {
      expiration_ms = each.value.time_partitioning.expiration_ms
      field         = each.value.time_partitioning.field
      type          = each.value.time_partitioning.type
    }
  }
  deletion_protection = "true"

  lifecycle {
    ignore_changes = [
      encryption_configuration
    ]
  }
}

**Comment by NathanMcK95** [comment]
I ran into this same issue when trying to import AWS ECR repositories. In my case the issue was that the way you import resources defined using **count** or **for_each** use a different syntax compared to importing a resource that defines a single entity.

Using this syntax caused terraform to delete and recreate the ECR repo after the import: terraform import module.ecr_repositories.aws_ecr_repository.repository test/repository/abc

Using this syntax imported the resource successfully and did not cause the deletion and recreation issue: terraform import 'module.ecr_repositories.aws_ecr_repository.repository["test/repository/abc"]' test/repository/abc

You can find the documenation of this syntax at the bottom of the page: https://www.terraform.io/cli/commands/import


Hopefully this helps!

**Comment by rileykarson** [comment]
@NathanMcK95 has likely covered it! If that doesn't address it, can you attach a plan output here so we can diagnose the issue?

It's possible for some resources that import will result in a resource missing information, if APIs don't return user-defined values.
