### ISSUE TITLE
Force downstream builder to wait for all sync branches before continuing

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#11109]
Currently, sync steps wait on their individual sync branches before pushing new commits. We could create a prerequisite step that requires all sync branches to be synced before pushing any of them. 

Doing so would remove the possibility of [Divergence by more than one commit](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/README.md#divergence-by-more-than-one-commit) scenario. This is the most complicated scenario to resolve.

**Comment by melinath** [comment]
Alternatively we could make it so that syncing "succeeds" automatically if the sync point is behind main - that is, we could make it possibly to retry runs without resetting all the sync branches. This would reduce the complexity of resolving the issue significantly by allowing one branch to catch up just by re-running jobs on Cloud Build rather than taking manual steps.
