### ISSUE TITLE
Authentication error message incorrectly suggests that gcloud auth will work with Terraform Cloud backend

### ISSUE THREAD

**Issue by mfwgenerics** [hashicorp/terraform-provider-google#11115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.5 on linux_amd64

### Affected Resource(s)

* google

### Terraform Configuration Files

```tf
provider "google" {
  project     = "my-project-id"
  region      = "australia-southeast1"
}

terraform {
  cloud {
    organization = "my-organization"

    workspaces {
      name = "api-staging-australia-southeast1"
    }
  }
}

# unimportant example resources
resource "google_sql_database" "database" { 
  name     = "my-database"
  instance = google_sql_database_instance.instance.name
}

resource "google_sql_database_instance" "instance" {
  name             = "my-database-instance"
  region           = "australia-southeast1"
  database_version = "MYSQL_5_7"
  settings {
    tier = "db-f1-micro"
  }

  deletion_protection  = "true"
}
```

### Debug Output

https://gist.github.com/mfwgenerics/35b1c3cf1ec1cec6c1c72a32b261e7e6#file-sample-sh

### Expected Behavior

Successfully following the instructions provided by the error message should have resulted in the error being resolved. Specifically, the error message was incorrect in claiming that running `gcloud auth application-default login` would allow me to "to use [my] gcloud credentials."

### Actual Behavior

Application credentials were not used after running `gcloud auth`. Additionally, GOOGLE_CREDENTIALS and GOOGLE_APPLICATION_CREDENTIALS env vars were ignored. Providing the credentials directly in the provider block did work.

If this is intended behavior when using the Terraform Cloud backend, the error message should be amended with this fact to avoid misleading and frustrating the user.

### Steps to Reproduce

1. `terraform plan`
2. `gcloud auth application-default login`
3. `terraform plan`

**Comment by rileykarson** [comment]
FYI @megan07: That's a reasonable error message for TPG as ran locally w/ TF, but may not hit the mark for TFC/TFE users where I'm not sure if it's possible to execute commands at all.

**Comment by megan07** [comment]
Hi @mfwgenerics - sorry for the delay around this. I think the issue here is that you are running this remotely (in TFC) and the default credentials that you create with `gcloud auth application-default login` are stored locally. You can solve this in two ways - you can change your [execution mode](https://www.terraform.io/cloud-docs/workspaces/settings#execution-mode) to `Local` in TFC, or, if you'd like to run it remotely I believe you'll need to store your credentials in your workspace's [Variables](https://www.terraform.io/cloud-docs/workspaces/variables/managing-variables#workspace-specific-variables).

I'll leave this issue open to clarify this in the documentation and/or the error message. Please let me know if neither of these works for you or if you have further questions. Thanks!
