### ISSUE TITLE
google_compute_interconnect_attachment: Error reading InterconnectAttachment: mtu

### ISSUE THREAD

**Issue by sharmaansh21** [hashicorp/terraform-provider-google#11131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

0.15.5

### Affected Resource(s)

* google_compute_interconnect_attachment

### Terraform Configuration Files
Create an interconnect with default values it will fail while running plan next time.

Error reading InterconnectAttachment: mtu: '' expected type 'string', got unconvertible type 'float64'

**Comment by ScottSuarez** [comment]
do you have an example terraform configuration?

**Comment by SarahFrench** [comment]
@/megan07 suggested I take a look at this issue, but after looking I think this is a known issue stemming from an old provider version (👉 [see description from 2021](https://github.com/GoogleCloudPlatform/magic-modules/pull/4643#discussion_r605168759)) rather than a current issue requiring a fix.

@sharmaansh21 if you're still having this problem, and you're using a version of the provider around v3.61.0, I think you need to upgrade your provider version. This bug was fixed in [v3.64.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.64.0)

**Comment by roaks3** [comment]
Per the comment above, closing this as already fixed
