### ISSUE TITLE
DataProc Job - allow waiting for job completion

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-google#11163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today the dataproc job resource only waits for the job to be running, it would be convenient to be able to run short jobs (applying spark/hive schema changes) and waiting for them to succeed (or fail and stop the apply)

### New or Affected Resource(s)

* google_dataproc_job

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by slevenick** [comment]
I don't think we want the provider to have this sort of functionality. Generally the `*_job` resources are non-standard and aren't well managed by Terraform in general, so I think adding this sort of functionality introduces a lot of questions about how jobs should work that we can't handle right now.

For example: What happens if the job fails? Would we expect Terraform to retry the job on the next `terraform apply` or should it consider itself successfully created?

Overall we don't want to be in the business of orchestrating jobs, so we shouldn't support this until Terraform has standard handling of job-type resources
