### ISSUE TITLE
`google_redis_instance`'s `read_replicas_mode` is not optional

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-google#11410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/google v4.16.0
+ provider registry.terraform.io/hashicorp/google-beta v4.16.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
```

### Affected Resource(s)

* google_redis_instance

### Terraform Configuration Files

```tf
resource "google_redis_instance" "this" {
  name               = "redis"
  memory_size_gb     = 1
  connect_mode       = "PRIVATE_SERVICE_ACCESS"
  redis_version      = "REDIS_6_X"
  tier   = "STANDARD_HA" # Same behavior with "BASIC"
}
```

### Expected Behavior

There should be no drift on existing `google_redis_instance` resources if the `read_replicas_mode` property was not specified.

### Actual Behavior

We get the following drift on plan on all our redis instances:
```
  # module.stack.google_redis_instance.this["ums"] must be replaced
-/+ resource "google_redis_instance" "this" {
      [...]
      + read_replicas_mode       = "READ_REPLICAS_DISABLED" # forces replacement
      [...]
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

The `read_replicas_mode` is supposed to be optional but is not. Worse, it forces us to make a choice for a property that's not applicable. In the GCP portal, the "Read Replicas" property is set to "NA":

![Capture d’écran 2022-04-05 à 10 41 42](https://user-images.githubusercontent.com/122286/161714376-a750d888-849d-46d8-82ba-13770e48c36e.png)

### Steps to Reproduce

1. Create a `google_redis_instance` with the provider version < 4.16.0
2. `terraform apply`, plan is clean
3. Upgrade the provider to 4.16.0
4. `terraform plan` is not clean.

### Important Factoids

Using the `version = "~> 4.15, != 4.16.0"` version constraint fixes the issue (no plan drift).

### References

This behavior was introduced in 4.16.0 with https://github.com/hashicorp/terraform-provider-google/pull/11330

**Comment by memphis88** [comment]
I have just experienced this and was about to write on the PR

**Comment by aorfanos** [comment]
same here

**Comment by rileykarson** [comment]
Sorry about that! This is an issue where the API returns a null value for a field if it was unspecified at creation time, but adopts a default value in the backend. When we make the provider send a value by default, the backend *does* return the set value. They're hard to catch because we don't know in advance the API will behave this way, and our tests spin up and down resources in one go.

I'll post a fix that should make it in to `4.17.0`, removing the explicit default and making the provider ignore returned values unless the field is user-specified. In the meantime, downgrading or using `lifecycle.ignore_changes` should mitigate.

**Comment by rileykarson** [comment]
Whoops, minor misclassification on my part. There are two fairly similar failure modes and I picked the wrong one. This statement was off:

> This is an issue where the API returns a null value for a field if it was unspecified at creation time, but adopts a default value in the backend. When we make the provider send a value by default, the backend does return the set value.

Instead, the API returns a different value for the resource based on its creation time rather than the user's request. Resources created _before_ the feature were implemented in the backend return the empty value and resources created _after_ it was implemented properly return the default value of the field. I have [logs](https://gist.github.com/rileykarson/13989b7f6a97e284bd6827a71ada12b6) from our CI going back around 90d and can confirm that on Jan 4th the default value was returned correctly even when not sent in the create request.

This doesn't change the mitigations or solution, although it makes a backfill of the values marginally more likely (which makes setting the field to `""` a slightly worse choice, as getting that diff in the future is more likely)

**Comment by billxinli** [comment]
Setting READ_REPLICAS_DISABLED or READ_REPLICAS_ENABLED forces the resources to be recreated.

**Comment by joe-a-t** [comment]
@rileykarson would it be possible to publish a 4.16.1 or 4.17.0 early? Given that this is a breaking change, it would be really great if we could avoid having to wait a week or two for the fix to get published.

**Comment by rileykarson** [comment]
Hey! This should go out in `4.17.0` on Monday, I don't feel this meets our [policy](https://github.com/hashicorp/terraform-provider-google/wiki/Release-Process#when-to-cherry-pick) for a patch release. While this is a perma-destroy, a possible candidate, it has somewhat limited impact as it only affects older instances, rather than all instances, and has multiple mitigations.

Sorry about that- releases are pretty expensive to make, so we have to be fairly judicious about when to break our regular schedule.

**Comment by joe-a-t** [comment]
@rileykarson looks like maybe something was borked with the release process today? The new release don't have any changelog, just all of the prior release notes...

**Comment by rileykarson** [comment]
The release script does that, the results need to be manually fixed. https://github.com/hashicorp/terraform-provider-google/blob/release-4.17.0/CHANGELOG.md and https://github.com/hashicorp/terraform-provider-google-beta/blob/release-4.17.0/CHANGELOG.md have the changelog in the meantime.
