### ISSUE TITLE
Cannot enable cloudresourcemanager.googleapis.com via Terraform

### ISSUE THREAD

**Issue by voycey** [hashicorp/terraform-provider-google#11435]
It seems like Cloud Resource Manager is required to active Cloud Resource Manager via Terraform - making this useless and requiring a manual intervention via console or via `gcloud`

This is the same issue as here that is now occurring in v4.16.0 :

https://github.com/hashicorp/terraform-provider-google/issues/6101

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/google v4.16.0
+ provider registry.terraform.io/hashicorp/google-beta v3.90.1
+ provider registry.terraform.io/hashicorp/helm v2.5.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.9.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/integrations/github v4.23.0

### Affected Resource(s)

cloudresourcemanager.googleapis.com

### Terraform Configuration Files

```tf
provider "google" {
  project = var.gcp_project_id
  region  = var.gcp_region
  credentials = var.gcp_service_account
}

locals {
  cluster_name = "guardian-cluster"
  build_gcp = var.deploy_to_where == "gcp" ? 1 : 0
}

resource "google_project_service" "cloudresourcemanager-service" {
  project = var.gcp_project_id
  service = "cloudresourcemanager.googleapis.com"
  count = local.build_gcp

  timeouts {
    create = "30m"
    update = "40m"
  }

}
```

### Debug Output

```
│ Error: Error when reading or editing Project Service tymlez-dev-240712/iam.googleapis.com: googleapi: Error 403: Cloud Resource Manager API has not been used in project 513643033245 before or it is disab
led. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=513643033245 then retry. If you enabled this API recently, wait a few minutes
for the action to propagate to our systems and retry.

```

### Expected Behavior

Terraform should be able to enable the cloudresourcemanager.googleapis.com API

### Actual Behavior

It fails saying it needs the cloudresourcemanager.googleapis.com to enable cloudresourcemanager.googleapis.com

### Steps to Reproduce

Use applied config above or in the linked issue
1. `terraform apply`

### References

* #0000

**Comment by rileykarson** [comment]
Is `513643033245` the project you're editing (`tymlez-dev-240712`)? The project service (service management) API draws quota/permissions from the project of the service account (SA) in use rather than from the project of the resource. If you create an SA in-project and then try to use that SA to call service management, it will fail.

If that's the case, you'll want to enable the service at project creation (wherever in your pipeline- manually, with gcloud, or a separate Terraform config) or use https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#user_project_override to change the quota project if that's not possible.

If it's different project, you'll want to enable the service on the project of the SA.

Optimistically closing, let me know if these don't work and I'll reopen.
