### ISSUE TITLE
Access token stored in state file when using google_client_config

### ISSUE THREAD

**Issue by leocurrie** [hashicorp/terraform-provider-google#11451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.16.0
```

### Affected Resource(s)

* google_client_config

### Terraform Configuration Files

```tf
terraform {
  required_version = "= 1.1.8"
  required_providers {
    google = "= 4.16.0"
  }
  backend "gcs" {
    bucket = "my_tf_state_bucket"
    prefix = "test_prefix"
  }
}

data "google_client_config" "current" {
}

```

### Debug Output

https://gist.github.com/leocurrie/8f8baa1b0b696111a1ae8c00bfcf7685

### Panic Output

N/A

### Expected Behavior

OAuth access token should not be stored in state file

### Actual Behavior

When examining the contents of the generated state file in the GCS bucket (i.e. `my_tf_state_bucket/test_prefix/default.tfstate`, an access token is stored as part of the google_client_config state:

```
{
  "version": 4,
  "terraform_version": "1.1.8",
  "serial": 1,
  "lineage": "0d0637ad-4b07-5923-1099-7111faa64591",
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "google_client_config",
      "name": "current",
      "provider": "provider[\"registry.terraform.io/hashicorp/google\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "access_token": "ya29.A0AR........[intentionally truncated here]",
            "id": "projects//regions//zones/",
            "project": "",
            "region": "",
            "zone": ""
          },
          "sensitive_attributes": []
        }
      ]
    }
  ]
}
```

The `access_token` can be used for subsequent API calls.

It's not clear to me why this token needs to be stored in the state file. I assume it will eventually expire.

### Steps to Reproduce

1. `terraform apply`
2. Inspect contents of state file stored in GCS bucket

### Important Factoids

This potentially undesirable behaviour does not appear to be [documented](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config).
If this behaviour is intentional I think it would be helpful to update the documentation to highlight that the token is stored in the state file.

**Comment by kravvcu** [comment]
I also stumbled upon this surprising behavior just last week. In my opinion there is no reason for the access token to be stored in state as IMO it should be re-fetched (re-generated) each time and should only be stored in memory in runtime.

This is a security risk when working in a team:

1. Person A runs 'apply'. This person's access token is stored in Terraform state.
2. Person B grabs the Terraform state and can perform any action Person A using their token. Malicious or not, the audit log is *not* accurate.

**Comment by upodroid** [comment]
Hello

That is intented and relatively safe to do so as the token is short lived. Also, you shouldn't be using that for service account impersonation as the feature has been added directly to the provider configuration.

The only reason you should be using that particular datasource is to access the Kubernetes API with the kubernetes terraform provider.

Thanks

**Comment by kravvcu** [comment]
> That is intended and relatively safe to do so as the token is short lived

For some definition of 'relatively safe' ;) The fact that the token is short lived just *ADDS* to the argument that it shouldn't be stored there, since, more often than not, it will need to be refreshed or refetched. So why permit such a security risk?

Also: I'm looking at `gcloud config config-helper` and it looks like those tokens are valid for 1 hour. If the ones placed in Terraform state have the same expiry then I wouldn't say they are 'short lived'. 1 hour is a lot of time in the problem's context.

> Also, you shouldn't be using that for service account impersonation as the feature has been added directly to the provider configuration.

If you mean using our personal credentials to impersonate the service account to perform deployment then I don't think that's a proper workflow as the audit logs would point towards the service account as the identity which performed any actions. It'd the same as using using a common 'root' user instead of personal accounts on VMs/machines.

> The only reason you should be using that particular datasource is to access the Kubernetes API with the kubernetes terraform provider.

Yes, that is our use case.

> The state bucket is sensitive and needs to be stored in a project with minimal access. You can leverage various security tools from Google to harden access to the bucket:

I believe none of the mentioned ones solve the problem at hand:

- CSEK only adds encryption but won't prevent a fellow worker to fetch my, possibly still valid, token
- Tighter IAM Permissions: we can't really remove read/write for the .tfstate files as we wouldn't be able to perform our work
- IAM deny policies: similar reasoning as above I believe (unless you had a scenario in mind which I could not figure out)
- VPC Service Controls: as above

**Comment by upodroid** [comment]
> For some definition of 'relatively safe' ;) The fact that the token is short lived just _ADDS_ to the argument that it shouldn't be stored there, since, more often than not, it will need to be refreshed or refetched. So why permit such a security risk?

It is 'relatively safe' given that it is not renewable and relatively short lived compared to a service account key. It is well known that all values available in terraform is stored in terraform including sensitive information.

Everyone has different thresholds and thoughts about what sensitive is.
https://www.terraform.io/language/state/sensitive-data

> If you mean using our personal credentials to impersonate the service account to perform deployment then I don't think that's a proper workflow as the audit logs would point towards the service account as the identity which performed any actions. It'd the same as using using a common 'root' user instead of personal accounts on VMs/machines.

Service Acccout Impersonations are audited by Google. You can see who impersonated and who used the token. https://cloud.google.com/iam/docs/audit-logging/examples-service-accounts#auth-as-service-account

There is an alternate solution to your problem which is out of scope of this provider. You will need to run `gcloud container clusters get-credentials` to generate a KUBECONFIG file that can be consumed by kubernetes, kubernetes-alpha and helm provider.

**Comment by melinath** [comment]
It looks like one of the primary purposes of the google_client_config is to provide an access token; [this example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_config#example-usage-configure-kubernetes-provider-with-oauth2-access-token) in the documentation shows passing the access token to a kubernetes provider. Also, the field itself is marked as [Sensitive](https://www.terraform.io/plugin/sdkv2/best-practices/sensitive-state) in the provider. So this is not a bug.

However, it could potentially be better documented that this data source contains sensitive data so that folks can know to follow the guidance at https://www.terraform.io/language/state/sensitive-data.
