### ISSUE TITLE
Support optional vm_count for google_compute_resource_policy.group_placement_policy when collocation="COLLOCATED"

### ISSUE THREAD

**Issue by nick-stroud** [hashicorp/terraform-provider-google#11483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v1.1.5
on linux_amd64
```

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```tf
resource "google_compute_resource_policy" "placement_policy" {
  name   = "my-placement-policy"
  region = "us-central1"
  group_placement_policy {
    collocation = "COLLOCATED"
  }
}
```

### Expected Behavior

The resource policy should be created without a `vm_count` as described in the official documentation: https://cloud.google.com/compute/docs/instances/define-instance-placement#compact.

### Actual Behavior

Terraform fails because `vm_count` is not specified. 

```
$ terraform apply
╷
│ Error: Missing required argument
│ 
│   with google_compute_resource_policy.placement_policy,
│   on main.tf line 4, in resource "google_compute_resource_policy" "placement_policy":
│    4:   group_placement_policy {
│ 
│ "group_placement_policy.0.availability_domain_count": one of `group_placement_policy.0.availability_domain_count,group_placement_policy.0.vm_count` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with google_compute_resource_policy.placement_policy,
│   on main.tf line 4, in resource "google_compute_resource_policy" "placement_policy":
│    4:   group_placement_policy {
│ 
│ "group_placement_policy.0.vm_count": one of `group_placement_policy.0.availability_domain_count,group_placement_policy.0.vm_count` must be specified
╵
```

### Important Factoids

- The actual behavior is in line with the [provider documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy#nested_group_placement_policy) but is enforcing a limitation that goes against the recommendation of the GCP documentation (See note in [this section](https://cloud.google.com/compute/docs/instances/define-instance-placement#compact))
- The equivelent gcloud command succeeds (note lack of `--vm-count` argument): 
```
gcloud compute resource-policies create group-placement my-placement-policy \
    --collocation COLLOCATED \
    --region us-central1 \
    --project <project-id>
```

**Comment by melinath** [comment]
This looks like it's probably a valid enhancement request; I don't think it's a bug, since the provider is behaving as expected (and if it's a bug it's probably a persistent bug, which would be treated as an enhancement request). It looks like [gcloud made `--vm-count` optional in 2020-03](https://cloud.google.com/sdk/docs/release-notes#28300_2020-03-03). And according to the [API user guide](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy#nested_group_placement_policy) it is possible to exclude the field (even though it's not marked optional in the [API reference](https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies#resource:-resourcepolicy).

Currently vmCount and availabilityDomainCount are marked as `at_least_one_of`; it _might_ be as simple as changing that to `conflicts_with` and marking them as optional, but I'm not sure. The logic of which subfields have to be specified and what behavior is expected if they aren't seems to also be influenced by the `collocation` field.
