### ISSUE TITLE
Support location parameter in google_cloudbuild_trigger

### ISSUE THREAD

**Issue by odashi** [hashicorp/terraform-provider-google#11624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current `google_cloudbuild_trigger` resource generates an HTTP request without the location parameter. It does not work with repository mappings on a specific region.
I'd be appreciate if the resource supports such an explicit parameter.

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "foo" {
  project = "myproject"
  location = "us-central1"
  ...
}
```

to generate the following URI:
```
https://cloudbuild.googleapis.com/v1/projects/myproject/locations/us-central1/triggers?...`
```

### References

* NA

**Comment by rileykarson** [comment]
See https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers/create, the API added a second locational variant of the resource. Not sure if we want to add a new resource or not, i.e. `google_cloud_build_location_trigger`

**Comment by atemate** [comment]
I needed to spend some time debugging why some of my builds succeed but no trigger is created, and others fail while the repo is already connected. It appeared that `region = "global"` is the default value for the `google_cloudbuild_trigger`.

I fully support either implementing this feature or at least documenting this behaviour [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger).

But I'd vote for having parameter `region` (not `location` as suggested in the description), because it's called `region` in the GCP Console UI.
