### ISSUE TITLE
Follow up to #6127

### ISSUE THREAD

**Issue by Thomasdezeeuw** [hashicorp/terraform-provider-google#12103]
This is a follow up to #6127, but that is locked so I can't ask my question their.

In https://github.com/hashicorp/terraform-provider-google/issues/6127 the issue was raised that when an instance is deleted and recreated (no updated in place) it will no be added back the instance group. The issue was closed pointing to https://github.com/hashicorp/terraform-plugin-sdk/issues/122. Fortunately it was closed with a (possible) solution to work around this issue.

Unfortunately, we hit this issue again today (in staging luckily). So, I'm wondering was this issue ever properly solved? I.e. was the solution created for https://github.com/hashicorp/terraform-plugin-sdk/issues/122 applied?

**Comment by slevenick** [comment]
What version of the Terraform CLI are you using? I think the fix is not applied in the provider itself, it's a meta-argument you can add to your config according to https://github.com/hashicorp/terraform-plugin-sdk/issues/122#issuecomment-1114912583

**Comment by Thomasdezeeuw** [comment]
> What version of the Terraform CLI are you using?

We're using 1.2.4-r0 (from Alphine).

> I think the fix is not applied in the provider itself, it's a meta-argument you can add to your config according to [hashicorp/terraform-plugin-sdk#122 (comment)](https://github.com/hashicorp/terraform-plugin-sdk/issues/122#issuecomment-1114912583)

I guess I misunderstood the linked comment. I though it mean that providers could indicate that another provider could change it's value. So, the Google provider could indicate that an instance could affect a group. But I'll give `replace_triggered_by` a manual try first.

**Comment by JPMoresmau** [comment]
Unfortunately, `replace_triggered_by` sent me a rabbit hole and didn't fix my issue. So when I asked for the instance group to be replaced when the instances change, it doesn't work because that instance group is being referenced by other things (a load balancer backend service, etc.). I tried then to add `create_before_destroy` but this fails as well because we have things like IP addresses that have to be unique and so we can't have two instances at the same time, however fleetingly. So the silly fix for us is to run `apply` twice as already recommended in other places, but it's a bit weird and frustrating that we cannot somehow indicate the instance group should be updated (and not replaced). Or have we missed something?

**Comment by slevenick** [comment]
I'm not very familiar with replace_triggered_by, but if it doesn't work in the way you expect it may be worth bringing that up with the SDK team directly. Does it not cause all the dependent resources to be recreated when the instance group is destroyed?

Overall I don't think we have a good way of handling this from within the provider, so if replace_triggered_by doesn't solve for your use-case we may be stuck with the double apply for the moment

**Comment by Thomasdezeeuw** [comment]
@slevenick I'm going to close this for now. We couldn't get `replace_triggered_by` to work, but the double apply works well enough for at the moment so this has fallen of the list of priorities.
