### ISSUE TITLE
Add support for cmekSettings on google_logging_project_bucket_config

### ISSUE THREAD

**Issue by steenblik** [hashicorp/terraform-provider-google#12123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for cmekSettings on ~google_logging_organization_bucket_config~ and google_logging_project_bucket_config. This allows for the creation for Cloud Logging Buckets encrypted with KMS keys.

https://cloud.google.com/logging/docs/routing/managed-encryption-storage
~https://cloud.google.com/logging/docs/reference/v2/rest/v2/organizations.locations.buckets~
https://cloud.google.com/logging/docs/reference/v2/rest/v2/projects.locations.buckets

### New or Affected Resource(s)

* ~google_logging_organization_bucket_config~
* google_logging_project_bucket_config

### Potential Terraform Configuration

```tf
resource "google_logging_project_bucket_config" "basic" {
  project        = "project_id"
  location       = "us-central1"
  retention_days = 30
  bucket_id      = "custom-bucket"

  cmek_settings {
    kms_key_name = "projects/my-project/locations/us-central1/keyRings/my-ring/cryptoKeys/my-key"
  }
}
```

### References

* #0000

**Comment by zli82016** [comment]
CmekSettings needs to be a new resource
https://cloud.google.com/logging/docs/reference/v2/rest/v2/TopLevel/getCmekSettings

**Comment by zli82016** [comment]
Hello, @steenblik, from my understanding, cmekSettings  is not useful to google_logging_organization_bucket_config. 

Custom buckets can only be created under projects, and cannot be created under organizations. Only the two system-generated log buckets: _Required and _Default are supported under organizations. However, we cannot update the cmekSettings for _Required and _Default buckets under organizations because we cannot add a CMEK key to a non-CMEK bucket. CMEK must be enabled at bucket creation. 

May I ask the reason or use cases to request support cmekSettings for google_logging_organization_bucket_config?

**Comment by steenblik** [comment]
Hi @zli82016 - Yes you are correct. This should not be applicable to organizations. I've amended the issue accordingly.
