### ISSUE TITLE
Add deletion_protection to google_compute_disk

### ISSUE THREAD

**Issue by przsab** [hashicorp/terraform-provider-google#12317]
### Terraform Version

Terraform v0.12.31
+ provider.google v3.90.1

### Affected Resource(s)

google_compute_disk

### Expected Behavior

Terraform should throw error like gcloud.

### Actual Behavior

Terraform recreates the disk, wiping all data when smaller size is provided.

### Steps to Reproduce

Deploy disk:

```
resource "google_compute_disk" "disk1" {
    name = "disk1"
    size = 2
}
```

Then change code to include size of 1 and apply:
```
resource "google_compute_disk" "disk1" {
    name = "disk1"
    size = 1
}
```

Plan output shows:
```
  # google_compute_disk.disk1 must be replaced
...
      ~ size                      = 2 -> 1 # forces replacement
...

google_compute_disk.disk1: Destroying... [id=projects/sab-dev-dbpe-2837/zones/us-central1-a/disks/disk1]
google_compute_disk.disk1: Destruction complete after 2s
google_compute_disk.disk1: Creating...
google_compute_disk.disk1: Creation complete after 1s [id=projects/sab-dev-dbpe-2837/zones/us-central1-a/disks/disk1]
```

At the same time, gcloud throws an error for same type of operation:
```
gcloud compute disks resize disk1 --size=1

This command increases disk size. This change is not reversible.
For more information, see:
https://cloud.google.com/sdk/gcloud/reference/compute/disks/resize

Do you want to continue (Y/n)?  y

ERROR: (gcloud.compute.disks.resize) Could not fetch resource:
 - Invalid value for field 'sizeGb': '1'. New disk size '1' GiB must be larger than existing size '2' GiB.
```

**Comment by edwardmedia** [comment]
@przsab disk recreation is expected. 1) This is mentioned in the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_disk#size). 2) Also did you review the terraform plan before you approve it? In the terraform workflow, there is no pause step available after you approve it. What do you suggest to improve this? 

```
NOTE If you change the size, Terraform updates the disk size if upsizing is detected but recreates the disk if downsizing is requested. You can add lifecycle.prevent_destroy in the config to prevent destroying and recreating.
```

**Comment by edwardmedia** [comment]
@przsab there are use cases where users want to downsize disks. To highlight: 1) here is the [doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_disk#size) that specifies what will happen if one choose resize on the config.  2) In the terraform workflow, there is a plan that shows the same before one approve it. There is no pause step available in the workflow. 

What do you suggest to improve it?

```
NOTE If you change the size, Terraform updates the disk size if upsizing is detected but recreates the disk if downsizing is requested. You can add lifecycle.prevent_destroy in the config to prevent destroying and recreating.
```

**Comment by przsab** [comment]
Lifecycle method is entirely static and cannot be automated in a parametrized way (sed is not reliable and we are using HCL so stuck on https://github.com/hashicorp/hcl/issues/294).

Because we are all automated, our goal is to prevent accidental destroy of disk during resize operations. Even if documented, every other tool errors out during this operation (GCP SDK, AWS CLI, AWS Terraform provider) and, rightfully, considers persistent disk immutable. Disk downsize is not possible with Terraform alone, requires OS block level migration so erroring out during an attempt would properly reflect the actual state of things.

**Comment by edwardmedia** [comment]
@przsab what do you suggest to help you in this case at the terraform & provider level?

**Comment by przsab** [comment]
One of these:
1. Throw an error during downsize just like gcloud does.
2. Add **allow_downsize = bool** optional property to google_compute_disk that would error out if size is decreased.
3. Query Stateful MIG configurations to see if the disk is configured as stateful, and if so, throw an error when downsized.

Option 2 will not break backwards compatibility if declared as optional or defaulting to true.

**Comment by slevenick** [comment]
This is intended Terraform functionality, as a recreate is required to decrease the disk size.

See previous discussion: https://github.com/hashicorp/terraform-provider-google/issues/10168#issuecomment-928214374

allow_downsize could theoretically work, but we want to avoid case-by-case situations like this, so I would lean towards not implementing this.

We can leave this open as an enhancement request for a deletion_protection or similar field

**Comment by SherriTrojan** [comment]
The disks in this case are defined as stateful.  Please see the stateful-migs link above. The disks are defined with a stateful policy of 'never'.  Stateful disks are meant to identify disks where the data is stateful and must not be deleted.  Recreating and destroying the data  breaks this configuration.  This is a bug for stateful instances/disk.

**Comment by SherriTrojan** [comment]
Please change this back to 'bug'

**Comment by slevenick** [comment]
I wouldn't consider this a bug even if the disk in question is stateful. The same situation could happen for a database, or any other resource managed by Terraform.

This could be considered as a feature request, but in general Terraform is acting correctly. It finds a change that requires a recreation of the resource, presents that to the user with the warning that the change will require recreate, and then takes that action when the user approves the plan. See https://learn.hashicorp.com/tutorials/terraform/automate-terraform#auto-approval-of-plans for the warnings on auto-approving plans without manual review

**Comment by SherriTrojan** [comment]
Then I have defined a critical database as stateful, and you are completely ignoring this and destroying the data.  What have I gained by going through the effort to declare this as stateful?  Terraform is ignoring the policy and incorrectly taking the wrong action.

**Comment by slevenick** [comment]
I would argue that Terraform is correctly detecting that it needs to recreate a disk to satisfy the user's intended change (downsize the disk), asking the user if they accept the plan that it created, and then applying that plan. None of these steps are out of line with what Terraform is expected to do

Terraform in general doesn't have a sense of what resources are or are not stateful, or policies about how to handle those types of resources.

You may want to look into the meta lifecycle argument of [prevent_destroy](https://www.terraform.io/language/meta-arguments/lifecycle#prevent_destroy) that can allow you to specify that a resource should not be destroyed. That provides a way to specifically tell Terraform to not destroy a particular resource because it is important

**Comment by SherriTrojan** [comment]
prevent_destroy is a primitive command that is not parameterized and is not usable in automation.
If Terraform is not able to identify correct state of a disk, then it should not delete the data!  It should error out as gcloud also does.

*** Policy: never: (Default.) Never delete the disk; detach the disk when the VM is deleted.

Please escalate to your leader.  We would like someone else to review this.

**Comment by slevenick** [comment]
I'll add one last recommendation that auto-approving plans is considered dangerous and not recommended for production workloads: https://learn.hashicorp.com/tutorials/terraform/automate-terraform#auto-approval-of-plans

If you wish to escalate this issue, please do so through official support channels. Unfortunately we are unable to do so via a GitHub issue

**Comment by SherriTrojan** [comment]
Relying on a human to validate a plan is a guarantee you will have it missed at some point and will take a significant outage with loss of data.

Even where this bug was introduced: https://github.com/hashicorp/terraform-provider-google/pull/1460
the requestor did not want it recreated:
......this situation probably doesn't have a good solution as throwing away a persistent disk and creating a new one is probably not what the user wants, unless data migration is planned carefully

**Comment by slevenick** [comment]
We always want to be able to make the user's infrastructure match their desired state when requested, which is why ForceNew was added when the disk size decreases. The only way for us to get to that desired state is to recreate the disk with the correct size. If you add the lifecycle argument to prevent destroy then Terraform understands the intention to not destroy this particular resource, and throws an error similar to gcloud's behavior in the resize situation.

I think there's a bit of confusion around stateful disks as declared in a managed instance group and how that interacts with the disk managed by Terraform. My understanding from reading https://cloud.google.com/compute/docs/instance-groups/stateful-migs#stateful_policy is that declaring a disk in a stateful policy only changes how a stateful managed instance group will interact with them. This configuration prevents the managed instance group from changing the disk or deleting it when the managed VM is shut down, but doesn't actually place any restrictions on the deletion of the underlying disk by other tools. Basically it tells the stateful MIG how to interact with the disk, but doesn't tell anything else

I'm not an expert on stateful MIGs or disks, but my interpretation is that there isn't any signal on the disk's statefulness available outside of the MIG

**Comment by SherriTrojan** [comment]
Even the original requestor understood how harmful this action could be.  Note: Disk downsize is not possible with Terraform alone, requires OS block level migration so erroring out during an attempt would properly reflect the actual state of things.
 I don't believe those writing the stateful managed instance documentation could foresee someone deleting the persistent stateful disk marked with never delete.  (Can the stateful managed instance documentation be updated that Terraform will still delete it if downsizing so that others won't loose a critical stateful disk) Without a fix to this bug, Terraform will not be usable for day2 ops on stateful instances.  I go back to the original suggestion with 2 likely being the best option.

1. Throw an error during downsize just like gcloud does.
2. Add allow_downsize = bool optional property to google_compute_disk that would error out if size is decreased.
Query Stateful MIG configurations to see if the disk is configured as stateful, and if so, throw an error when downsized. Docs: https://cloud.google.com/compute/docs/instance-groups/stateful-migsAdd allow_downsize = bool optional property to google_compute_disk that would error out if size is decreased.
3. Query Stateful MIG configurations to see if the disk is configured as stateful, and if so, throw an error when downsized. Docs: https://cloud.google.com/compute/docs/instance-groups/stateful-migs

**Comment by rileykarson** [comment]
Hey all! I'm going to close this, given that the discussion has sidebarred into a discussion about disk resizes rather than deletion protection, and given that we've already stated a general stance that disk `deletion_protection` is not something we're interested in in https://github.com/hashicorp/terraform-provider-google/issues/10168#issuecomment-928214374.

I want to +1 @slevenick's response that stateful configuration is metadata for a *MIG* to decide how to process a resource, not Terraform. The equivalent in Terraform would be using Terraform's lifecycle fields like `ignore_changes` or `prevent_destroy`. A generalised lien resource, similar to https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/resource_manager_lien, would be a way to control this at the GCP level, although that has not been built to my knowledge.

**Comment by SherriTrojan** [comment]
This bug is being escalated.
