### ISSUE TITLE
google_monitoring_notification_channel == project  parameter is missing in documentation and it is required 

### ISSUE THREAD

**Issue by ahmedloai** [hashicorp/terraform-provider-google#12470]
During my trial to deploy google_monitoring_notification_channel by Terraform and based on the provided docs i Found that 
Examples are 

resource "google_monitoring_notification_channel" "basic" {
  display_name = "Test Notification Channel"
  type         = "email"
  labels = {
    email_address = "fake_email@blahblah.com"
  }
}

resource "google_monitoring_notification_channel" "default" {
  display_name = "Test Slack Channel"
  type         = "slack"
  labels = {
    "channel_name" = "#foobar"
  }
  sensitive_labels {
    auth_token = "one"
  }
}

While actually it works for me fine but after doing that 

resource "google_monitoring_notification_channel" "basic" {
  display_name = "Test Notification Channel"
  type         = "email"
  **project    = <project.id>**
  labels = {
    email_address = "fake_email@blahblah.com"
  }
}

It is not mentioned in the docs at anyplace

**Comment by edwardmedia** [comment]
@ahmedloai the google provider allows users to provide `project` and other common parameters like `region` and `zone` with multiple ways. If you have already configured in the provider block or [environment variables](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#project), they become optional in the individual resource. Because most gcp resources are on project, `project` is required for these resources. Does this make sense?

**Comment by edwardmedia** [comment]
@ahmedloai I agree the documentation isn't super good. This is a constant topic on where to put those words. Questions and suggestions keep coming. We will continue implementing improvement to better serve users. Thanks for your suggestion. Closing the issue then

**Comment by ahmedloai** [comment]
thx for clarification
