### ISSUE TITLE
Feature Request: DNS Managed Zone data source by DNS Name, not just Zone Name

### ISSUE THREAD

**Issue by genevieve** [hashicorp/terraform-provider-google#1255]
### Affected Resource
- data google_dns_managed_zone

### Expected Behavior
A dns managed zone can be found by it's dns name, not just the zone name.

### Actual Behavior
The only way to retrieve a dns managed zone with a terraform google data source is via the zone name. With the aws terraform provider, you retrieve the zone with the dns name.

Would you be willing to accept a PR for this functionality?

**Comment by emilymye** [comment]
We are always happy to accept PRs! However, this might not be a problem we can fix - it looks like https://cloud.google.com/dns/api/v1/managedZones/get requires name or ID, probably because it's possible to create two zones with the same DNS name under GCP (I just did it) :/

**Comment by genevieve** [comment]
Yeah, it probably wouldn't be ideal to get a list of the managed zones and then filter on the dns name instead of doing the api call with the zone name..

**Comment by emilymye** [comment]
Honestly, the filter option isn't the worst idea  I'll be honest - since our team mostly come from the GCP side, I have no idea how AWS or AWS provider does things at all (is that what a aws_route_53_zone is?) but it's certainly possible. 

However, I guess I'm actually confused as to why you need this in particular. Are you talking only about import? I'm not sure if there is another situation where you couldn't just refer to it by terraform-computed name or id.

**Comment by genevieve** [comment]
We have users that use the terraform templates for multiple environments that are all manually added as record sets to the same dns zone.

If we could use the data source for importing the existing dns zone that matches the domain you intend to use for X environment, we could add the record set for you to that zone instead of requiring manual intervention for every environment that needs to be a record set.
