### ISSUE TITLE
google_redis_instance - auth_string 

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#12563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_redis_instance

### Terraform Configuration Files

`auth_string` according to the docs can be populated but its generated by GCP. So this should be output only in the docs.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance 

### References

* #0000

**Comment by edwardmedia** [comment]
@drandell I agreed `auth_string` should be in the exported section. Because this is a specially handled field, currently the code generation tool does not support adding a field like this into the exported section. Changing the label to `document` 

https://github.com/GoogleCloudPlatform/magic-modules/blob/70352381f79e67152922421649d1b48cdacf8fe9/mmv1/templates/terraform/resource.html.markdown.erb#L156

**Comment by drandell** [comment]
If I get some time this week I might make the PR for this, agree wrong label :)
