### ISSUE TITLE
secret_manager_secret_version: retrieve value only

### ISSUE THREAD

**Issue by eraac** [hashicorp/terraform-provider-google#12632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Using the data `google_secret_manager_secret_version` require more permissions than `roles/secretmanager.secretAccessor`. Which after reading the code make sense, because the data give more information than the secret value, but also metadata (like the creation time, ...)

But it's not really intuitive and you need to give more permissions to an user/service account where isn't required (when you only want the secret), it will be good to have an attribute to limit the information retrieve, or a custom resource to access only the value.

### New or Affected Resource(s)

* google_secret_manager_secret_version

### Potential Terraform Configuration

```tf
data "google_secret_manager_secret_version" "secret" {
  project = "xxx"
  secret  = "yyy"
  version = 1
  only_value = true
}

# OR 

data "google_secret_manager_secret_version_access" "secret" {
  project = "xxx"
  secret  = "yyy"
  version = 1
}
```

**Comment by mitj04** [comment]
I've gone through this issue and it seems like a request for new data-source.
- `google_secret_manager_secret_version` provides metadata which consists of additional data which requires more permissions than secretAccessor.
- As per the [documentation](https://cloud.google.com/secret-manager/docs/access-control), secretAccessor provides only secretmanager.versions.access so we can only access version of secret, while [Secret Manager Viewer](https://cloud.google.com/secret-manager/docs/access-control#secretmanager.viewer) and other roles give access to secrets, iamPolicies, versions, etc.
-  The new suggested data source `google_secret_manager_secret_access` will require only the accessor role and will be able to return only the payload of secrets.
- Also, the [Access](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/access) method needs to be used instead of [Get](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/get) method.

**Comment by mitj04** [comment]
b/263941788

**Comment by mitj04** [comment]
According to the [documentation](https://cloud.google.com/secret-manager/docs/access-control), it appears that the [Secret Manager Secret Accessor](https://cloud.google.com/secret-manager/docs/access-control#secretmanager.secretAccessor) role gives users access to the [GET](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/get), [LIST](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/list), and [ACCESS](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/access) methods that are utilised in the current datasource `google_secret_manager_secret_version`. Therefore, this datasource only grants access to extract the payload of secrets by using the Secret Manager Secret Accessor role. Hence, it appears that there is no particular need to construct a new datasource because the existing datasource is performing the same thing.

Closing this issue. If there is a need for a different solution please open a new issue describing the problem & proposed solution in detail. Thanks!

**Comment by eraac** [comment]
> According to the [documentation](https://cloud.google.com/secret-manager/docs/access-control), it appears that the [Secret Manager Secret Accessor](https://cloud.google.com/secret-manager/docs/access-control#secretmanager.secretAccessor) role gives users access to the [GET](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/get), [LIST](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/list), and [ACCESS](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/access) methods that are utilised in the current datasource `google_secret_manager_secret_version`. Therefore, this datasource only grants access to extract the payload of secrets by using the Secret Manager Secret Accessor role. Hence, it appears that there is no particular need to construct a new datasource because the existing datasource is performing the same thing.

The current datasource also needs the permission `secretmanager.secrets.get` (because of the metadata). The role [Secret Manager Secret Accessor](https://cloud.google.com/secret-manager/docs/access-control#secretmanager.secretAccessor) *don't* give this permission.

The needs as describe in my issue is a datasource (or an attribute) to only access the secret value, not the metadata (which require more permissions)

**Comment by mitj04** [comment]
Reopening it.

It looks like the new suggested data source `google_secret_manager_secret_access` will require only the Accessor role and will be able to return only the payload of secrets.
- Also, the [Access](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/access) needs to be used instead of [Get](https://cloud.google.com/secret-manager/docs/reference/rest/v1/projects.secrets.versions/get).

Thanks for the quick update.

**Comment by wyardley** [comment]
Just to confirm, this requires less access, but will still result in the secret value being stored in terraform state, right?

**Comment by wyardley** [comment]
Might also be good to extend the docs to explain the use case / reasoning a little better and maybe even add a pointer from the `google_secret_manager_secret_version` resource docs? The downstream generated docs don’t really explain how this resource is different from `google_secret_manager_secret_version`

**Comment by melinath** [comment]
@wyardley yes, that's correct. Please feel free to open a new issue requesting that docs change or [contribute it](https://googlecloudplatform.github.io/magic-modules/) - seems like a good improvement!  :-)

**Comment by wyardley** [comment]
@melinath done
