### ISSUE TITLE
Document meaning of "flatten" and "expand" in the context of Terraform provider development

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12657]
Currently we have two types of conversion functions: Flatteners and expanders. These are not intuitive for new users (or even experienced users), because it's not clear what is being flattened or expanded. In most cases, the end result is exactly the same level of flat or nested as the starting point.

It would be great to rename these functions (for example to `tf2apiResourceName` and `api2tfResourceName`) to make it immediately clear what the function's purpose is.

**Comment by rileykarson** [comment]
Note that the nomenclature is common across providers: https://github.com/hashicorp/terraform-provider-aws/blob/a2ee3af3cc8a395039f055397d8f71b7463effde/internal/service/firehose/delivery_stream.go#L1638 and https://github.com/hashicorp/terraform-provider-azurerm/blob/8debe94a1db69c92019c069b3ccbf1cce1c61209/internal/services/datashare/data_share_account_resource.go#L195 are examples.

We may want to improve our documentation about what the functions do, rather than break from the rest of the ecosystem's convention.
