### ISSUE TITLE
Add GKE logging variant field for increasing log agent throughput

### ISSUE THREAD

**Issue by Dev25** [hashicorp/terraform-provider-google#12667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE has recently added support for configuring a high throughput logging mode at both a cluster and node pool level. Add this field so users can opt in to the `MAX_THROUGHPUT` mode.

https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs#throughput

### New or Affected Resource(s)

* google_container_cluster
* google_container_node_pool

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_container_cluster" "primary" {
  name               = "demo-cluster"

  logging_variant = "MAX_THROUGHPUT"
  # or
  logging_config {
    variant = "MAX_THROUGHPUT"
  }
}

resource "google_container_node_pool" "pools" {
  node_config {
     logging_config {
         variant = "MAX_THROUGHPUT"
     }
  }
}
```

### References

* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodePoolLoggingConfig#LoggingVariantConfig
* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/NodeConfig
* https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs#throughput

**Comment by giuliano-sider** [comment]
I think this issue is important for GKE users and I'm working on a PR to add the field to google_container_cluster. Subsequently, I can submit a PR for the google_container_node_pool as well. I was thinking of adding logging_variant inside the node_pool_defaults to stay more or less consistent with the GKE API itself, and to emphasize that this is a cluster-level value that is applied to node pools by default; that is, it's the logging variant that's used throughout the cluster unless overridden at the node pool level. For example, by specifying
```terraform
resource "google_container_cluster" "with_logging_variant_node_pool_default" {
  name               = "foo-cluster"
  location           = "us-central1-f"
  initial_node_count = 1

  node_pool_defaults {
    node_config_defaults {
      logging_variant = "MAX_THROUGHPUT"
    }
  }
}
```
every node pool in the cluster will have the max throughput logging agent configured (see the [GKE docs](https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs#high_throughput_for_all_nodes_in_a_cluster) for more information).
