### ISSUE TITLE
Auto truncate comment in release making process

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#12751]
When making a release the release note thats generated contains a lot of unrelated content that the user needs to manually truncate. I would be nice to automatically detect and truncate this string before generating the note.

steps 4 and 7

<img width="943" alt="Screen Shot 2022-10-10 at 3 23 33 PM" src="https://user-images.githubusercontent.com/9483464/194940711-29b31392-ae13-4073-9da0-85efbd2178a3.png">

https://github.com/hashicorp/terraform-provider-google/wiki/Release-Process#bug-on-duty

**Comment by SarahFrench** [comment]
I took a quick look at this problem and I wanted to share what I learned:

The release process owned by HashiCorp expects there to be an artifact, containing the release notes for a given release, uploaded to the repo containing the provider. [This is the section of the GHA workflow for this repo](https://github.com/hashicorp/terraform-provider-google/blob/3458a7ff3f69bd3a5402c844b40e5b80e0c54c83/.github/workflows/release.yml#L26-L32) that defines how the release notes are generated and then uploaded.

The `sed` command used to pull out the section of CHANGELOG.md relevant to the latest release is something made by HashiCorp : [see it here in the release tooling's README](https://github.com/hashicorp/ghaction-terraform-provider-release#setting-release-notes-from-changelog)

The `sed` command uses `git describe` to pull in the latest tag and then uses that output to identify the previous tag. This is used to prevent lines in the changelog from previous releases being streamed into the output `release-notes.txt` file. So if you tag v4.50.0 and the previous tag is v4.49.0 then you should see all of your changelog file above the entry for v4.49.0 being put into `release-notes.txt`.

**Here's a clue to the problem I found about the issue**: The command below is nested in the `sed` command. When I check out the main branch of this repo and run the command:

```bash
git describe --abbrev=0 --match='v*.*.*' --tags

#v4.40.0
```

...it returns `v4.40.0` but I'd expect there to be newer tags because that's a few releases ago. When I check to see what the previous tag was (i.e. run the same command but exclude `v4.40.0`) I see:

```bash
git describe --abbrev=0 --exclude="v4.40.0" --match='v*.*.*' --tags

# v4.27.0
```

I then [found out about this command](https://git-scm.com/docs/git-tag#Documentation/git-tag.txt---mergedltcommitgt), which will "Only list tags whose commits are reachable from the specified commit (HEAD if not specified)". The grep avoids noise and focuses on recent history:

```bash
git tag --merged | grep v4.

# v4.17.0
# v4.27.0
# v4.40.0
```

I believe this is the reason why old entries are found in the release notes!

Either we need to get a clearer idea of the tagging & merging process or we need to work out a different process to generate that  `release-notes.txt` artifact.

**Comment by SarahFrench** [comment]
This solution seems hacky and still has the previous problem of needing to reliably discover the previous version tag

```
git checkout v4.42.0

export PREV_VERSION=4.41

sed -e '1,/'$PREV_VERSION'/!d' -e '/'$PREV_VERSION'/d'  CHANGELOG.md > release-notes.txt
```
