### ISSUE TITLE
Failing test(s): Error waiting for Create Instance // "code": "UNKNOWN"

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#12912]
### Affected Resource(s)

* google_sql_database_instance
* google_sql_ssl_cert
* google_sql_user

Failure rate: 
- initially: rare per test
- Nov 2022: TestAccSqlDatabaseInstance_basicClone failed 100% with various error messages.

Impacted tests:
- TestAccSqlDatabaseInstance_createFromBackup
- TestAccSqlDatabaseInstance_backupUpdate
- TestAccSqlDatabaseInstance_cloneWithSettings
- TestAccSqlDatabaseInstance_PointInTimeRecoveryEnabled
- TestAccSqlDatabaseInstance_insights
- TestAccSqlClientCert_postgres
- TestAccSqlUser_postgres
- TestAccSqlDatabaseInstance_basicClone
- TestAccSqlUser_postgresAbandon

Nightly builds:
-https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject/348563?buildTab=tests&expandedTest=-4211530923017358526&logFilter=debug

Message:

```
Error: Error waiting for Create Instance:
```

From the API response:

```
"error": {
  "kind": "sql#operationErrors",
  "errors": [
   {
    "kind": "sql#operationError",
    "code": "UNKNOWN"
   }
  ]
 },
```

**Comment by AarshDhokai** [comment]
b/261392894

**Comment by melinath** [comment]
Additional messages:

```
Error: Error, failed to create instance tf-test-uo21pwapm9: googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request.
```

```
Error: Error waiting for Create Instance: timeout while waiting for state to become 'DONE' (last state: 'RUNNING', timeout: 30m0s)
```

Bumping priority because TestAccSqlDatabaseInstance_basicClone failed 100% during Nov 2022

**Comment by roaks3** [comment]
This issue was created first, but I already started collapsing some of the context on https://github.com/hashicorp/terraform-provider-google/issues/12995 (sorry).

In short:
- The empty error is now captured in https://github.com/hashicorp/terraform-provider-google/issues/12995. I've copied over relevant context.
- The 409 is not something we're seeing anymore
- The 30m timeout was resolved

That should cover all of the issues gathered here, so closing this one.
