### ISSUE TITLE
Reduce import-related build issues

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#13147]
# Background

New contributors run into the same class of error fairly frequently, getting roughly this error:

```
TF_LOG=TRACE make testacc TEST=./google TESTARGS='-run=TestAccDataprocCluster_withLabels' > output.log
# github.com/hashicorp/terraform-provider-google/google [github.com/hashicorp/terraform-provider-google/google.test]
google/resource_bigtable_app_profile.go:468:9: undefined: bigtableadmin
google/resource_compute_subnetwork.go:39:22: undefined: cidr
make: *** [GNUmakefile:15: testacc] Error 2
```

We should remove some of the friction here- improve docs, throw errors, obviate entirely, etc.

# What kind of contribution is this issue about?

general contributions

# Related PR(s), if any:

* N/A

# Details

This is _likely_ to have to do with `goimports`, or not having cloned the providers before running MM. I haven't seen this exact error myself, but my environment's a year+ old (and pretty much a clone of a 4-year-old one) so I don't expect to.

**Comment by melinath** [comment]
in my experience this is usually due to either not having the main branches in sync or due to stale files from a previous branch. I usually have folks run `git checkout -- . && git clean -f google/ google-beta/ website/` and sync their PR & downstream to main, and that generally fixes it.

I've also noticed there's additional confusion because of `> output.log` redirecting stdout to a file.

I've documented the cleanup process & tried to clarify the usage of `output.log` as part of [a docs fixup PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/6894) but it would be worth documenting the syncing & goimports parts as well. Perhaps we could add a "Troubleshooting" page that includes information like this.
