### ISSUE TITLE
google_storage_transfer_job -- event_stream field

### ISSUE THREAD

**Issue by kazukousen** [hashicorp/terraform-provider-google#13293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We'd like to request the support to add an `event_stream` field in `google_storage_transfer_job`  to more closely to more closely reflect the API's [TransferJob](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs) resource which supports a eventStream field.

### New or Affected Resource(s)

* google_storage_transfer_job

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_storage_transfer_job" "transfer-job" {
    description = "Sample storage transfer job"
    transfer_spec {
        gcs_data_sink {
            bucket_name = "my-sink-bucket"
        }
        gcs_data_source {
            bucket_name = "my-source-bucket"
        }
    }

    event_stream {
        name = "my-aws-sqs-subscribe-role-arn"
  }
}
```

**Comment by SarahFrench** [comment]
@BBBmau - I've assigned you to this issue 🚀 

Here's a link to the field in Google's API docs: https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs#TransferJob.FIELDS.event_stream

This resource is handwritten, so instead of updating YAML you will be editing these files by hand:
- Resource: [services/storagetransfer/resource_storage_transfer_job.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storagetransfer/resource_storage_transfer_job.go)
- Acceptance Tests : [services/storagetransfer/resource_storage_transfer_job_test.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storagetransfer/resource_storage_transfer_job_test.go)
- Documentation: [website/docs/r/storage_transfer_job.html.markdown](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/storage_transfer_job.html.markdown)

**Comment by SarahFrench** [comment]
Closing, as [event_stream has been added to the resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job#nested_event_stream). 🚀
