### ISSUE TITLE
Update templated import code for resources, to avoid issues when project is not set in provider config or ENVs

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#13370]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

---

### Description

Currently the code for importing a resource in TPG only sets the resource's ID in its data (i.e. schema.ResourceData) before the SDK uses the resource's Update function to pull remaining information about that resource from the API into state and complete the import process. The [Update function depends on the `project` being set](https://github.com/hashicorp/magic-modules/blob/adefb621cb47b0e99fce5967116a84fc3d088f88/mmv1/templates/terraform/resource.erb#L592-L598) either A) in the resource's data (`schema.ResourceData`) or B) being sourced from the provider's configuration. However not all practioners set a default project, and some may want to import resources that belong to different projects than the default.

We should look into whether we can update the [templated import code](https://github.com/hashicorp/magic-modules/blob/adefb621cb47b0e99fce5967116a84fc3d088f88/mmv1/templates/terraform/resource.erb#L951-L987) to identify the project for a resource from the resource's name. 

Currently this type of import issue is addressed by creating custom import code in response to bug reports. However this problem would affect how the majority of resources are imported if the resource doesn't match the default project, and ideally the amount of custom import code won't increase linearly with resource count.

I've linked to multiple GitHub issues that stem from this problem in the **Resources** section of this description.

If a code change to address this isn't possible, we could add more explicit guidance about importing resources in the provider documentation, e.g. that it's not sufficient to include the project in the resource block prior to import, using multiple configurations of the provider with different default project values etc.

### New or Affected Resource(s)

Multiple

### Potential Terraform Configuration

N/A

### References

Here are some open issues that match this _general_ problem I've described

* https://github.com/hashicorp/terraform-provider-google/issues/13307
* https://github.com/hashicorp/terraform-provider-google/issues/10961
* https://github.com/hashicorp/terraform-provider-google/issues/10788

**Comment by rileykarson** [comment]
This works at the generator level already, and if a general issue is present it'd come down to the implementation of individual resources. Many resources define their `id` and import format as a `name` field, often referring to an output-only `name` field. In those cases, the `name` field is set by `replaceVars`. In resources with a well-defined `id` and import format, individual fields like `project` and `region` can be replaced and/or inferred. See https://github.com/hashicorp/terraform-provider-google-beta/blob/f2d33f49375d12ff26d9b55786a98e04c66891d0/google-beta/resource_compute_address.go#L543-L562, for example.

Barring excessive customization this is pretty quick to spot: an example like https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_catalog_taxonomy#import has a format of just `{{name}}`, while https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#import has a set of different possible formats.

re: the examples provided, I think both generated resources here have handwritten import funcs and google_compute_project_metadata_item is handwritten altogether, so generator changes aren't likely to solve for those examples. google_compute_project_metadata_item is easy to fix- it passes through the import value to the id, but doesn't use the id in calling Get. The others can have slashes in their URL which is more difficult to work with.

**Comment by SarahFrench** [comment]
I'd overlooked the `parseImportId` function, I didn't realise it added to the resource's data. Thanks! 😅 

So as a general rule, generated resources that _can_ have slashes in their names should have custom import code and otherwise generated resources should specify more import formats and leverage `parseImportId` - got it

I'll close this issue

**Comment by melinath** [comment]
Supporting slashes in resource names for generated import code is a long-standing improvement that would be great to make to the generator. https://github.com/hashicorp/terraform-provider-google/issues/12060

**Comment by ScottSuarez** [comment]
> re: @rileykarson 

What about import in the following scenario?
https://github.com/hashicorp/terraform-provider-google/issues/10788#issuecomment-1441137307
https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_monitoring_notification_channel.go#L500

Name is being used for the import Name is **inclusive** of project. Since project is not auto parsed from the name the `parseImportId` function dies when it tries to find project. Shall we not infer the project from the name as a fallback (instead of from provider config). If the provider config lacks the `project` field then this import dies completely on import, ie issue 10788. 

I would say parseImportId should follow the following pattern
1. import as instructed initially
2. if import format has no /project/ identifier, try to parse project from available <name>
3. If unable to find project at this point attempt to infer from provider level config
4. Error out

**Comment by rileykarson** [comment]
(watch out when opening old issues, this was open but still locked! This has only been maintainers so far, who can ignore locks)

That's a standard example of what I said in https://github.com/hashicorp/terraform-provider-google/issues/13370#issuecomment-1369866480: the format of the id for that resource is `{{name}}`, and a value looks like `projects/my-project/notificationChannels/0123456789`. The id and base import format should have been `projects/{{project}}/notificationChannels/{{channel_id}}` rather than `name`.

That implies the following formats would work:

* `projects/{{project}}/notificationChannels/{{channel_id}}`
* `{{project}}/{{channel_id}}`
* `{{channel_id}}`

For backwards compatibility we'd _also_ need to support the following undocumented format:

* `{{project}} projects/{{project}}/notificationChannels/{{channel_id}}`

That was added- seemlingly inadvertently- in https://github.com/GoogleCloudPlatform/magic-modules/pull/3270/files.
