### ISSUE TITLE
Setting node_config tags to null should ignore that field rather than set it to empty list

### ISSUE THREAD

**Issue by charleshartiii** [hashicorp/terraform-provider-google#13613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.7
on linux_amd64
provider registry.terraform.io/hashicorp/google v4.48.0

### Affected Resource(s)

* google_container_node_pool
* google_container_cluster

### Terraform Configuration Files

```tf
node_config {
    tags = null
}
```
### Expected Behavior

In above code, if there already exists a list of tags defined in the `node_config` block then I would expect TF to ignore this tags field and leave them as they are

### Actual Behavior

TF sets the tags to an emtpy list, [], thus removing existing tags

### Steps to Reproduce

1. Create google nodepool TF code with node_config block and set `tags` within the block to a list of strings, i.e. `tags=[ "one", "two" ]`
2. Terraform apply to create the nodepool with this node config
3. Now update code to say `tags=null`
4. Terraform apply and see the tags removed rather than ignored

**Comment by SarahFrench** [comment]
Hi @charleshartiii thanks for you question, I think I have something that can help the use case you're describing.

It sounds like you only want the node_config.tags argument to be used when creating a node pool but not not when updating it, right? If that's the case you can use the [ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) lifecycle meta argument to achieve this. This should allow you to run your Steps to Reproduce and see that no update is proposed at step 4.

```hcl
resource "google_container_node_pool" "example" {
  # ...

  lifecycle {
    ignore_changes = [
      node_config.tags,
    ]
  }
}
```

We can't change the provider to behave like this normally because otherwise it doesn't let users remove or change tags.

Does this help with your problem?

**Comment by charleshartiii** [comment]
Hi @SarahFrench unfortunately the `ignore_changes` does not work in our case.

Other attributes within this `node_config` block such as `machine_type`, `image_type`, `disk_size_gb`, etc I am able to set to value to `null` and they are correctly ignored by terraform.

The tags attribute should have a consistent behavior and offer ability.

I think if users ever need to remove all tags they should instead set `tags=[]` rather than null.

**Comment by melinath** [comment]
The other attributes (like machine_type, image_type, disk_size_gb) are all Optional + Computed, which means that removing them from the config (or setting them to null) will preserve the last value sent by the API (which in this case is the last value you set). So they are not being ignored - they are just continuing to send the last value the user set. Although this can be confusing sometimes, it's the best way we have to support fields that have an API-side default.

`tags` is only Optional, which means that when it is removed from the config it will be sent as an empty value to the API (instead of sending the last value returned by the API.) This is a more consistent user experience and what we generally prefer to use where possible.

As such - we are not likely to make this change. Thanks for opening this issue, and please let me know if you think I've gotten anything wrong!
