### ISSUE TITLE
TF plan difference based on the order of database_flags

### ISSUE THREAD

**Issue by nvsajeeva** [hashicorp/terraform-provider-google#13663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Description
It appears that the order of database_flags we mention in the configuration file has some effect. If we change the order of database_flags in the configuration file, the plan will show a difference.  

### Terraform Version

v1.3.6

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

```tf
  settings {
    tier = var.machine_type_tier

    database_flags {
      name  = "wait_timeout"
      value = "100"
    }
    database_flags {
      name  = "max_prepared_stmt_count"
      value = "16000"
    }


    user_labels = var.user_labels
  }
```

### Expected Behavior

```No changes. Your infrastructure matches the configuration.```

### Actual Behavior

Terraform plan shows a difference. 
```  
# google_sql_database_instance.cloudsql will be updated in-place
  ~ resource "google_sql_database_instance" "cloudsql" {
        id                             = "cstestdb-d0c5b7e1"
        name                           = "cstestdb-d0c5b7e1"
        # (14 unchanged attributes hidden)

      ~ settings {
            # (12 unchanged attributes hidden)

          ~ database_flags {
              ~ name  = "max_prepared_stmt_count" -> "wait_timeout"
              ~ value = "16000" -> "100"
            }
          ~ database_flags {
              ~ name  = "wait_timeout" -> "max_prepared_stmt_count"
              ~ value = "100" -> "16000"
            }

            # (4 unchanged blocks hidden)
        }
    }
```

### Steps to Reproduce

1. Provision an instance with database_flags in the following order
```
    database_flags {
      name  = "max_prepared_stmt_count"
      value = "16000"
    }
    database_flags {
      name  = "wait_timeout"
      value = "100"
    }
```
2. Change the order of database_flags as follows in the configuration file
```
    database_flags {
      name  = "wait_timeout"
      value = "100"
    }
    database_flags {
      name  = "max_prepared_stmt_count"
      value = "16000"
    }

```
3. ```terraform plan```

### Important Factoids

1. This is not specific to certain flags. This scenario can be observed for any flag. 
2. This becomes a problem when we merge default flags and custom flags as follows
```
    dynamic "database_flags" {
      for_each = merge(var.database_variables_flags_default, var.database_variables_flags)
      content {
        name  = database_flags.key
        value = database_flags.value
      }
    }
```
If we specify a new flag, dynamic block re-orders all the variables. This leads to a huge difference in terraform plan.

**Comment by edwardmedia** [comment]
Server-side re-ordering. Likely need to change the type from list to set. 

https://github.com/hashicorp/terraform-provider-google/blob/850d47d06b6280e4ce65c9cd40b809bdd5262df9/google/resource_sql_database_instance.go#L315

**Comment by Positronico** [comment]
The bug seems to be correctly identified. I just want to add that, on top of the unnecessary drift correction due to "out of order" flags, some specific flags can't be applied at all via terraform.

One example is the "table_open_cache". It's not a terraform limitation, because the same error happens trying to add the flag manually via webui. The only method that seems to work is using gcloud with the flag-files param:

`gcloud sql instances patch db-instance --flags-file=sql-flag-file.yaml`

The databases I manage which require this flag were updated via the above method, then removed and imported back into the state file. Nevertheless, we can't apply their TF code because of the out of order problem, since the change in the flags fail to apply.

So far, my databases can't be managed via TF until this item is fixed.

`
{
 "kind": "sql#operation",
 "targetLink": "https://sqladmin.googleapis.com/sql/v1beta4/projects/REDACTED/instances/REDACTED",
 "status": "DONE",
 "user": "REDACTED",
 "insertTime": "2023-03-28T22:42:55.959Z",
 "startTime": "2023-03-28T22:42:56.205Z",
 "endTime": "2023-03-28T22:43:06.695Z",
 "error": {
  "kind": "sql#operationErrors",
  "errors": [
   {
    "kind": "sql#operationError",
    "code": "INTERNAL_ERROR"
   }
  ]
 },
 "operationType": "UPDATE",
 "name": "dae5356e-1ee0-45aa-909d-1e6700000026",
 "targetId": "REDACTED",
 "selfLink": "https://sqladmin.googleapis.com/sql/v1beta4/projects/REDACTED/operations/dae5356e-1ee0-45aa-909d-1e6700000026",
 "targetProject": "REDACTED"
}
`

**Comment by smcgivern** [comment]
Thanks @edwardmedia, I created https://github.com/GoogleCloudPlatform/magic-modules/pull/8118 to implement that.

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8118

This will release with v5.0.0. Check https://github.com/hashicorp/terraform-provider-google/issues/15582 for more details on the major release.
