### ISSUE TITLE
Failing test(s): google_dataproc_metastore_service error code 13

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#13710]
### Failure rates

- 100% since 2023-02-03

### Impacted tests:

- TestAccDataprocMetastoreService_PrivateServiceConnect
- TestAccDataprocMetastoreFederation_dataprocMetastoreFederationBasicExample
- TestAccDataprocMetastoreFederation_dataprocMetastoreFederationBigqueryExample
- TestAccDataprocMetastoreFederationIamBindingGenerated
- TestAccDataprocMetastoreFederationIamMemberGenerated
- TestAccDataprocMetastoreFederationIamPolicyGenerated
- TestAccDataprocMetastoreService_dataprocMetastoreServiceEndpointExample

### Affected Resource(s)

* google_dataproc_metastore_service

### Nightly builds

- https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudGoogleProject/374114?buildTab=tests&expandedTest=-9117918343586913256

### Message(s)

```
Error: Error waiting to create Service: Error waiting for Creating Service: Error code 13, message: an internal error has occurred
```

**Comment by melinath** [comment]
This likely is due to an upstream breaking change.

**Comment by melinath** [comment]
We should double-check that this is not a service account permissions issue and that it still fails in the same way - the tests are currently skipped in CI (or not generated.) If it's still the same failure we should redirect to `service/metastore`.

**Comment by NickElliot** [comment]
Some of the disabled tests passed locally without issue, but still showed problems within CI. Investigated the proposed service account permission issue but found no seeming anomaly. Previous incidences of this error code have suggested some kind of version mismatch, but a couple of attempted updates failed to change. Should follow-up with the service team for a more detailed diagnostic rather than chasing down random potential fixes on our end.

**Comment by SarahFrench** [comment]
I recently got an email about this bug being resolved: https://issuetracker.google.com/issues/256628703?pli=1
I can't remember why I +1'd it, but I think it might be due to test failures like this
