### ISSUE TITLE
Allow force creation of datastream stream and skip validation

### ISSUE THREAD

**Issue by kliu47** [hashicorp/terraform-provider-google#14022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Creation of `google_datastream_stream` fails when terraform is unable to successfully complete validation. Request is the ability to allow creation of the resource in the `NOT_STARTED` state similiar to how one would use `gcloud datastream update -force`

### New or Affected Resource(s)

* google_datastream_stream

### Potential Terraform Configuration

```tf
resource "google_datastream_stream" "example" {

  display_name  = "example-stream"
  location      = "us-east1"
  stream_id     = "example-db-gcs"
  desired_state = "NOT_STARTED"
  force = true 
source_config {}
destination_config {}
}

```

### References

* #0000

b/299600924

**Comment by rileykarson** [comment]
@melinath to triage

**Comment by iperetz-goo** [comment]
@melinath yep thats a reasonable request, we expose this capability in the API via a request parameter - `force=true`
Usually users want this in cases when the validation failure are expectable to them

**Comment by BrettNWoods** [comment]
This is a great feature for our use case. We want to connect Datastream to a Postgres database but don't want to put the database credentials within the statefile. Our thoughts were that we could set up the Datastream connection profile with dummy values with an `ignore_changes` lifecycle block on those values and then change them manually, ensuring that the  secrets remain outside of the state. Because Datastream needs to be validated before the connection profile will actually build, we have to;

1. Create a new user within the db with dummy values.
2. Feed these into the `google_datastream_connection_profile`
3. Run `terraform apply` successfully
4. Change the values of the user within the database
5. Manually change the connection profile to have the correct values

As the API already has this functionality, it would be great if we could get this within terraform.

**Comment by iperetz-goo** [comment]
@BrettNWoods I can recommend creating a connection profile via the Datastream UI and just reference it in terraform, this way you will wont need to store credentials in a file + wont need to create dummy resources in TF

**Comment by ralphotowo** [comment]
+1 

I'm facing a similar issue where I'm trying to avoid committing the actual credentials into git or terraform state. Did anyone find a solution to this yet?

**Comment by tcaddy** [comment]
My current work-around is to ClickOps the resource with identical values to what's defined in HCL code, then import the resource with an `import {}` block.  And it imports successfully with zero changes.

**Comment by tsantandreu** [comment]
@tcaddy Can you provide sample code on your work around.

**Comment by tcaddy** [comment]
I actually figured out the cause of my issue and it kinda explains how my "work around" even worked in the first place.

Here's what happened: we were refreshing a lower environment with a restore of the prod database. It just so happens that we had the same username and host for the cloud sql users in both production and lower environments, but the passwords were different.

Terraform never detected the drift (the fact that the passwords didn't match). The solution is to delete the cloud sql user accounts after restore and let terraform recreate them with the correct password.

@tsantandreu
