### ISSUE TITLE
Failing test(s): TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample (beta)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14394]
### Failure rates

- 100% since 2023-04-07

### Impacted tests

- TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample

### Affected Resource(s)

* google_healthcare_dicom_store

### Nightly build test history

- [Historical test data, ending August 9th](https://ci-oss.hashicorp.engineering/test/-2576387264761293991?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E&expandedTest=id%3A196376%2Cbuild%3A%28id%3A388628%29)
- [Historical test data August 12th-present](https://hashicorp.teamcity.com/test/-2576387264761293991?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

```
------- Stdout: -------
=== RUN   TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample
=== PAUSE TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample
=== CONT  TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample
bootstrap_iam_test.go:70: Added the following bindings to the test project's IAM policy:
Members: ["serviceAccount:service-123456789@gcp-sa-healthcare.iam.gserviceaccount.com"], Role: "roles/bigquery.jobUser"
Retry the test in a few minutes.
--- FAIL: TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample (23.75s)
FAIL
```

**Comment by SarahFrench** [comment]
@roaks3 - another problem that seems to have started when the Beta overnight tests swapped to the new project. Does this permission need to be set in the project outside the control of the acceptance tests? Or should the acceptance test be updated?

**Comment by roaks3** [comment]
@SarahFrench This one I'm not sure about. You're right about the timing matching when we started using the new project, but I currently see the correct permission on the project (likely from the bootstrap function), so it's not clear what is wrong. This service agent has many more permissions granted in our original project, so it's possible that was somehow persisting access for each of the tests that use it. It also could be a timing issue where tests are run in a slightly different order.

Separate from the question of why this started to fail, I believe the failure itself is probably due to the permission being deleted by a resource: https://github.com/GoogleCloudPlatform/magic-modules/blob/6f4c708625eddf95a1f73714b7d82ff80e708be2/mmv1/third_party/terraform/tests/resource_project_service_identity_test.go.erb#L41-L45. We will probably want to update that test so that it does not try to manage this particular permission, and then I suspect this test failure will resolve.

**Comment by melinath** [comment]
Marking as service/terraform because it seems like there may be some complexity here that our team can better handle.

**Comment by rileykarson** [comment]
Clean 90d history.
