### ISSUE TITLE
Failing test(s): TestAccVertexAIFeaturestore_vertexAiFeaturestoreScalingExample

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#14395]
### Failure rates

- 100% since 2023-04-07

### Impacted tests

- TestAccVertexAIFeaturestore_vertexAiFeaturestoreScalingExample

### Affected Resource(s)

* google_vertex_ai_featurestore

### Nightly build test history

- [Link](https://ci-oss.hashicorp.engineering/test/-1713602049567904589?currentProjectId=GoogleCloudBeta&branch=%3Cdefault%3E)

### Message(s)

Looks like a quota needs to be increased in the new overnight project for TPGB

```
------- Stdout: -------
=== RUN   TestAccVertexAIFeaturestore_vertexAiFeaturestoreScalingExample
=== PAUSE TestAccVertexAIFeaturestore_vertexAiFeaturestoreScalingExample
=== CONT  TestAccVertexAIFeaturestore_vertexAiFeaturestoreScalingExample
vcr_utils.go:144: Step 1/2 error: Error running apply: exit status 1
Error: Error waiting to create Featurestore: Error waiting for Creating Featurestore: Error code 8, message: The following quotas are exceeded: FeatureStoreOnlineServingNodes
with google_vertex_ai_featurestore.featurestore,
on terraform_plugin_test.tf line 2, in resource "google_vertex_ai_featurestore" "featurestore":
2: resource "google_vertex_ai_featurestore" "featurestore" {
--- FAIL: TestAccVertexAIFeaturestore_vertexAiFeaturestoreScalingExample (14.80s)
FAIL
```

**Comment by SarahFrench** [comment]
@roaks3 - Sorry for tagging you in all these! This looks like a quota that needs to be increased in the beta project, maybe?

**Comment by roaks3** [comment]
@SarahFrench No worries! We could increase the quota here, but the quota we have is technically enough to handle our tests under normal conditions. In this case, there are some resources that have accumulated and have not been swept, so I think deleting them is a better solution. It is a bit of work for this particular resource because of all of the dependent resources, but I may be able to pick this one up today (or later in the week).

**Comment by melinath** [comment]
This is no longer failing.
