### ISSUE TITLE
Add the name field to google_storage_transfer_job

### ISSUE THREAD

**Issue by lorenzofelletti** [hashicorp/terraform-provider-google#15220]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

On the Cloud Console, when creating a Storage Transfer Job, it is possible to set a job name of choice, instead of the randomly generated one. It would be nice to have the same possibility on Terraform too, so to be able to create Jobs with a meaningful name. Otherwise, all the storage transfer jobs created by Terraform will have meaningless name.

I know it is already possible to set a custom description of the job, but by having the possibility to choose a short meaning ful name it would make it easier to quickly recognize a job among the others, which may not always be easy (especially in case one have a lot of jobs).

### New or Affected Resource(s)

* google_storage_transfer_job

### Potential Terraform Configuration

```tf
resource "google_storage_transfer_job" "job_to_patch" {
  name = "beautiful-short-name" # name or job_name would be good names imho
  description = "A really informative description"
  project     = var.project_id

  transfer_spec {
    # ...
  }
}
```

### References

b/302672796

**Comment by SarahFrench** [comment]
Adding some extra context to this request:
- The `name` field is [currently an output-only attribute](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_transfer_job#name) on the `google_storage_transfer_job` resource
- The API docs say that you can specify a name or let the API assign one : ["If this field is empty in a CreateTransferJobRequest, Storage Transfer Service assigns a unique name. Otherwise, the specified name is used as the unique name for this job."](https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs#:~:text=If%20this%20field%20is%20empty%20in%20a%20CreateTransferJobRequest%2C%20Storage%20Transfer%20Service%20assigns%20a%20unique%20name.%20Otherwise%2C%20the%20specified%20name%20is%20used%20as%20the%20unique%20name%20for%20this%20job.)
    - It may be that in the past it wasn't possible to assign a name to the resource via the API
- The name field may need to be updated to be `Optional: true` + `Computed: true` so that the field can take values from the Terraform config or from the API.

Because this resource is handwritten this work would require:
- Editing the Go code for the [name field in this file](https://github.com/GoogleCloudPlatform/magic-modules/blob/a89ba05ab20ae1a21d937588ea279ef854702482/mmv1/third_party/terraform/services/storagetransfer/resource_storage_transfer_job.go#L70-L74) (+ any other required changes)
- Updating the handwritten [documentation file](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/storage_transfer_job.html.markdown) for this resource
