### ISSUE TITLE
Why is the google_iam_deny_policy resource still only available in the google-beta provider?

### ISSUE THREAD

**Issue by paulspiegel** [hashicorp/terraform-provider-google#15229]
Deny policies looks to be GA in the v2 REST API.  The v2beta endpoint has a fairly low quota on requests per minute so we've gotten errors when using the beta provider.

https://cloud.google.com/iam/docs/reference/rest/v2/policies#Policy

thanks,
Paul

**Comment by c2thorn** [comment]
Likely has not been prioritized/picked up since it has been made GA. You can create feature request to request the resource to be promoted to GA.

There's also an option to override the endpoint yourself with https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference.html#{{service}}_custom_endpoint, but at your own risk.
