### ISSUE TITLE
Return a specific Magician error when base fails to compile

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#15899]
The current error message comes from the breaking change detector and may mislead contributors into thinking the issue is with their change. See https://github.com/GoogleCloudPlatform/magic-modules/pull/8976 for discussion.

**Comment by iyabchen** [comment]
@melinath I don't think the diff-processor build(function buildDiffProcessor) can tell whether base or head is broken.  Also, I am not sure whether we should run a build on either head or base to see which one is breaking during the diff-processor build, since they are already part of the generate diffs CI flow. 
I am thinking just update the error message to ask user to check the build results instead. What do you think?

**Comment by melinath** [comment]
Hmm! I think it could be reasonable to do something like: verify that the downstreams exist and compile, and short-circuit anything that relies on building them if we know they don't compile. Maybe as part of https://github.com/GoogleCloudPlatform/magic-modules/blob/eff19adf97250c0d62e8c417e9d7cefb60203f35/.ci/magician/cmd/generate_comment.go#L196?

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/11157
