### ISSUE TITLE
404 when accessing debug logs posted onto PRs

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16124]
# Background

<img width="615" alt="Screenshot 2023-10-05 at 11 01 55" src="https://github.com/hashicorp/terraform-provider-google/assets/15078782/5c0e4b88-2065-4c8f-9045-c86bd7981f4e">

The link to the debug logs for the passing test in the screenshot above/[this PR comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/9163#issuecomment-1747250825) has a 404 error.

# What kind of contribution is this issue about?

general contributions

# Related PR(s), if any:

* https://github.com/GoogleCloudPlatform/magic-modules/pull/9163#issuecomment-1747250825

# Details

The `TestAccCloudIdentityGroup` test loops through multiple tests and is structured differently to typical acceptance tests, so this might mean the URL of the log file is formed differently than normal?

https://github.com/hashicorp/terraform-provider-google/blob/52d037c11e0b329c141b7f2eccc99a89f74f4167/google/services/cloudidentity/resource_cloud_identity_group_test.go#L18-L46

**Comment by rileykarson** [comment]
You can access those logs directly through the GCS bucket from the bottom link! You've got it, the logs are split out by subtest and we're just reporting on the main test. TC has a similar output, actually- the only test is the top-level one and the artifacts are subtest-specific.

Given that most of these are whole packages that need to run in serial, I wonder if we could stop using subtests by just omitting `t.Parallel` since I think that applies at the package level. We'd likely want a way to catch inadvertent additions of parallel tests to those packages, though.

**Comment by SarahFrench** [comment]
I'll close this issue and open an issue about refactoring the test, thanks!
