### ISSUE TITLE
docs-examples and oics buttons have diverged

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#16384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

N/A

### Affected Resource(s)

* google_XXXXX

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/os_config_os_policy_assignment for an example. We probably guard generating the directory and adding the button on slightly different rules. I thought it might be version related, but this appears to be GA. Maybe `test_env_vars`?

### References

* #0000

**Comment by melinath** [comment]
The logic for generating OICS examples is:

https://github.com/GoogleCloudPlatform/magic-modules/blob/5e824ac9b2610cdc5a3b807c1e94e40477105a0e/mmv1/provider/terraform_oics.rb#L40-L43

I'm pretty sure the last line is a no-op for public generation since OICS generation uses beta - so only resources at alpha would be excluded by it. https://github.com/GoogleCloudPlatform/magic-modules/blob/5e824ac9b2610cdc5a3b807c1e94e40477105a0e/.ci/gcb-push-downstream.yml#L149-L160

---

The logic for including an OICS link is:

https://github.com/GoogleCloudPlatform/magic-modules/blob/5e824ac9b2610cdc5a3b807c1e94e40477105a0e/mmv1/templates/terraform/resource.html.markdown.erb#L102-L104

---

I believe those are equivalent. It looks like os_config_os_policy_assignment is not generated - I assume that we don't intend handwritten docs to have OICS links and this is just an oversight?

**Comment by melinath** [comment]
It looks like the OICS links were inadvertently introduced while migrating the resource from tpgtools to handwritten: https://github.com/hashicorp/terraform-provider-google-beta/commit/7f3b2ecf7a5f3c44001f8412910d6140d12f6a5c#diff-10ce2c336edf0b7efb1851d634d178e963bcffcc179223e09c1d6e224f112ec7R21
