### ISSUE TITLE
supporting sslMode in `google_sql_database_instance` resources

### ISSUE THREAD

**Issue by DesmondH0** [hashicorp/terraform-provider-google#16406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

From the current settings, we could not control the connectivity to use `only allows connections encrypted with SSL/TLS` due to missing `sslMode` options in `ipConfiguration`

Ref: https://cloud.google.com/sql/docs/postgres/configure-ssl-instance#rest-v1

### New or Affected Resource(s)

* `google_sql_database_instance`

### Potential Terraform Configuration

```tf
resource "google_sql_database_instance" "postgres_instance" {
  (...)
  settings {
    tier = "db-custom-2-7680"
    ip_configuration {
      require_ssl = "true"
      # this should be value of "ALLOW_UNENCRYPTED_AND_ENCRYPTED", "ENCRYPTED_ONLY" or "TRUSTED_CLIENT_CERTIFICATE_REQUIRED"
      sslMode = "ALLOW_UNENCRYPTED_AND_ENCRYPTED"
    }
  }
}
```

b/310897371

**Comment by eberle1080** [comment]
+1 although I feel like sslMode should replace require_ssl -- it's not a boolean state in the first place.

**Comment by eberle1080** [comment]
Actually it looks like the good-beta provider already has this: https://github.com/hashicorp/terraform-provider-google-beta/pull/6579

**Comment by SarahFrench** [comment]
This PR is relevant to this issue : https://github.com/GoogleCloudPlatform/magic-modules/pull/9367

**Comment by gygitlab** [comment]
Just wanted to feed back on this one. [A PR was completed last year ](https://github.com/GoogleCloudPlatform/magic-modules/pull/9367) but it's a bit confusing for PostgreSQL as the guidance in the [Terraform docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#ssl_mode) appears conflict with the [GCP docs](https://cloud.google.com/sql/docs/postgres/admin-api/rest/v1/instances).

Specifically it's clear that `requireSsl` is now "legacy" but since it appears the Terraform provider sets it to `false` by default it now creates a conflict when trying to set `sslMode` to `TRUSTED_CLIENT_CERTIFICATE_REQUIRED` as the GCP docs states:

> Only allow connections encrypted with SSL/TLS and with valid client certificates. When this value is used, the legacy requireSsl flag **must be true or cleared** to avoid the conflict between values of two flags.

IMO for this issue to be completed it would seem `requireSsl` is deprecated / removed for PostgreSQL & MySQL instances where it's default is now "cleared" instead of `false` to allow for a clean replacement with `sslMode` because as it stands today you need to confusingly manage two separate variables here to avoid conflicts with setting SSL.

**Comment by SarahFrench** [comment]
@gygitlab could you please open a [new issue](https://github.com/hashicorp/terraform-provider-google/issues/new/choose) (Bug Report) about that problem? I think this GitHub issue needs to be closed -as the feature request to add this new field is completed- and problems with the field should be reported as bugs. Bugs and feature requests are managed in different ways and it'll help the problem be triaged faster. Thank you!

**Comment by SarahFrench** [comment]
I'm closing this issue as completed because [ssl_mode has been added to the google_sql_database_instance resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#ssl_mode).

**Comment by gygitlab** [comment]
Raised a new issue [here](https://github.com/hashicorp/terraform-provider-google/issues/17443) thanks.
