### ISSUE TITLE
Plugin should not use "application default" credentials, but "active credentials"

### ISSUE THREAD

**Issue by vojkny** [hashicorp/terraform-provider-google#16474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently, the plugin is using `application default` credentials obtained with:

`gcloud auth application-default login`

Which is fine for most cases, but once you work on different projects, this requires constant relogging for each project. Google cloud allows using configurations with:

```bash
$ gcloud config configurations list
NAME      IS_ACTIVE  ACCOUNT             PROJECT      COMPUTE_DEFAULT_ZONE  COMPUTE_DEFAULT_REGION
project1  False      me@project1.com     project1     europe-west1-b        europe-west1
project2  True       me@project2.com     project2     europe-west1-c        europe-west1

$ gcloud config configurations activate project1
Activated [project1].
```

Unfortunately this setting has no effect on the plugin credentials as it only respects the `application default`. And when trying to run Terraform it says:

```
Error: error loading state: 
Failed to open state file at gs://bucket/state/default.tfstate: googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>knyttl@herohero.co does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details></Error>
```

### New or Affected Resource(s)

Not relevant.

### Potential Terraform Configuration

Not relevant.

### References

https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference?ref=hackerstack#running-terraform-on-your-workstation

**Comment by rileykarson** [comment]
The current behaviour is correct- we support [Application Default Credentials](https://cloud.google.com/docs/authentication/provide-credentials-adc) and don't use the gcloud-specific configuration. gcloud is the engine through which you can get access to user credentials in ADCs, as described at https://cloud.google.com/docs/authentication/provide-credentials-adc#local-user-cred.

Rather than rely on their configurations you'd want to automate Terraform directly, such as through the tools recommended at https://cloud.google.com/sdk/docs/configurations#automating_configuration_switching, using GOOGLE_APPLICATION_CREDENTIALS (for ADCs) or one of the provider-specific environment variables under https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference?ref=hackerstack#credentials.

Alternatively, [Terraform override files](https://developer.hashicorp.com/terraform/language/files/override) appear to work as well. Assuming you had a standard `.gitignore` rule so that you could leave those in relevant directories, you could overlay `credentials` (or any other provider mechanism) through that.

**Comment by vojkny** [comment]
> Rather than rely on their configurations you'd want to automate Terraform directly, such as through the tools recommended at https://cloud.google.com/sdk/docs/configurations#automating_configuration_switching

This is exactly what I am mentioning above! The problem seems to be that Terraform is not using the credentials from this switching, but using the default credentials set by `gcloud auth application-default login` instead of `gcloud auth login` or this `gcloud configurations activate`.

**Comment by rileykarson** [comment]
Oh, no, what I mean there is that you should use the tools recommended for switching by gcloud like `direnv` or `ondir` to control Terraform- such as by setting `GOOGLE_CREDENTIALS`- rather than rely on gcloud. We don't expect Terraform to be using gcloud's credentials at any point, just ADCs from gcloud if gcloud is the ADC source determined per https://cloud.google.com/docs/authentication/provide-credentials-adc.

**Comment by vojkny** [comment]
But what would be the expected workflow to swich between two accounts without actually having to re-login every time?
