### ISSUE TITLE
Failing test(s): TestAccComputeVpnTunnel_vpnTunnelBasicExample

### ISSUE THREAD

**Issue by trodge** [hashicorp/terraform-provider-google#16661]
### Failure rates

- 100% since 2023-11-14

### Impacted tests

- TestAccComputeVpnTunnel_vpnTunnelBasicExample

### Affected Resource(s)

* google_compute_vpn_tunnel

### Nightly build test history

- https://hashicorp.teamcity.com/test/-4828036683778076513?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true

### Message(s)

```
    vcr_utils.go:152: Step 1/2 error: Error running apply: exit status 1
        Error: Error adding labels to ComputeVpnTunnel "projects/ci-test-project-nightly-ga/regions/us-central1/vpnTunnels/tf-test-tunnel-1nh3xkxlbc4": googleapi: Error 412: Labels fingerprint either invalid or resource labels have changed, conditionNotMet
          with google_compute_vpn_tunnel.tunnel1,
          on terraform_plugin_test.tf line 2, in resource "google_compute_vpn_tunnel" "tunnel1":
           2: resource "google_compute_vpn_tunnel" "tunnel1" {
```

b/314944273

**Comment by joelsdc** [comment]
Workaround: create the `google_compute_vpn_tunnel` resource with no labels, and ensure you are not using `default_labels` at the provider config level.

**Comment by melinath** [comment]
There's also a bug report related to this: https://github.com/hashicorp/terraform-provider-google/issues/16588

**Comment by melinath** [comment]
Since this is GA only, it's likely related to the promotion of the `labels` field to GA: https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.7.0

It looks like `label_fingerprint` is currently [marked beta-only in the provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_vpn_tunnel#label_fingerprint) (which would explain why it's not being sent by the `google` provider) but it's [available in the GA API](https://cloud.google.com/compute/docs/reference/rest/v1/vpnTunnels). Maybe the fix is just to promote the label_fingerprint field, and that was missed in the promotion PR because we don't currently run GA tests.

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/9768
