### ISSUE TITLE
Failing test(s): TestAccCompute* (Beta) ("Region X already has a Network Edge Security Service")

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#16745]
### Failure rates

- 100% since 2023-11-10

### Impacted tests

- TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy
- TestAccComputeRegionSecurityPolicyRule_regionSecurityPolicyRuleNetworkMatchUpdate
- TestAccComputeTargetInstance_withSecurityPolicy

### Affected Resource(s)

* google_compute_target_pool
* google_compute_network_edge_security_service

### Nightly build test history

- TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy
- [TestAccComputeRegionSecurityPolicyRule_regionSecurityPolicyRuleNetworkMatchUpdate](https://hashicorp.teamcity.com/test/-8614576542318311132?currentProjectId=TerraformProviders_GoogleBeta_NightlyTests&expandTestHistoryChartSection=true)
- TestAccComputeTargetInstance_withSecurityPolicy

### Message(s)

```
Error: Error creating NetworkEdgeSecurityService: googleapi: Error 400: Invalid value for field 'resource.region': ''. Region us-west2 already has a Network Edge Security Service., invalid
```

**Comment by SarahFrench** [comment]
I've tagged this as service/terraform as this issue is related to running tests in parallel in a single project. I think this can be addressed by ensuring tests run in different regions, and doesn't _require_ service team involvement.

**Comment by shuyama1** [comment]
Cleaned up the dangling resources in the testing project and handwrite the sweeper to sweep resources in multiple regions (https://github.com/GoogleCloudPlatform/magic-modules/pull/10216). Created https://github.com/hashicorp/terraform-provider-google/issues/17835 to track support for sweeper in multi-region in mmv1 generator.

`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy` still failed consistently due to a different error. Created https://github.com/hashicorp/terraform-provider-google/issues/17838 to track it.
