### ISSUE TITLE
panic: Error reading level state: strconv.ParseInt: parsing "8580780465065941099": value out of range

### ISSUE THREAD

**Issue by bourdeau** [hashicorp/terraform-provider-google#16809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.6.6
on linux_386

### Affected Resource(s)

all

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 1.6.6"
  cloud {
    organization = "staysail"

    workspaces {
      name = "preprod"
    }
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.9.0"
    }
    random = ">= 3.4.3"
  }
}
```

### Debug Output

https://gist.github.com/bourdeau/22ed5d5a28b36d760632777e86a15f36

### Panic Output

https://gist.github.com/bourdeau/22ed5d5a28b36d760632777e86a15f36

### Expected Behavior

`terraform plan` normal output

### Actual Behavior

Crashes because trying to cast "8580780465065941099" to int.

```bash
panic: Error reading level state: strconv.ParseInt: parsing "8580780465065941099": value out of range
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

* I use a user account instead of a service account.

### References

I didn't find any other issue related. Maybe I didn't look hard enough.

**Comment by melinath** [comment]
Generally speaking, `value out of range` errors happen due to running on a 32-bit system - here are some open (and closed) tickets with similar errors in the past: https://github.com/hashicorp/terraform-provider-google/issues?q=is%3Aissue+is%3Aopen+%22value+out+of+range%22

It's hard to tell from your config & debug log which resource this is related to - could you share a minimal config (without modules or variables and with the smallest number of resources possible) that reproduces the issue? Thanks!

**Comment by bourdeau** [comment]
@melinath Thank you for your help

I use Terraform Cloud to store the state, but I execute terraform commands locally. 

I'm on a 64bits machine (`Linux ph-corsair 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`)

My project look like this:

```bash
.
├── docs
│   └── img
│       └── logo.jpg
├── environments
│   ├── preprod
│   │   └── main.tf
│   ├── prod
│   │   └── main.tf
│   └── test
│       └── main.tf
├── Makefile
├── modules
│   └── staysail
│       ├── bucket.tf
│       ├── cloud_run.tf
│       ├── database.tf
│       ├── dns.tf
│       ├── etc
│       │   └── env.tpl
│       ├── iam.tf
│       ├── lb.tf
│       ├── main.tf
│       ├── output.tf
│       ├── registry.tf
│       ├── secrets.tf
│       ├── service_account.tf
│       └── variables.tf
└── README.md
```

I tried to debug creating a new environment named `test` which contains exactly the same config as `preprod`:

```hcl
terraform {
  required_version = ">= 1.6.6"
  cloud {
    organization = "staysail"

    workspaces {
      name = "test"
    }
  }
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.9.0"
    }
    random = ">= 3.4.3"
  }
}


module "staysail" {
  source  = "../../modules/staysail"
  stage   = "test"
  is_prod = false
  db_settings = {
    tier              = "db-custom-1-3840"
    availability_type = "ZONAL"
    retained_backups  = 1
  }
  cr_api_settings = {
    cpu            = "1"
    memory         = "2048Mi"
    cpu_throttling = false
    min_scale      = "0"
    max_scale      = "1"
  }
  polaris_version = "latest"
}
```
The only external modules is the load balancer:
```hcl
module "gce-lb-http" {
  source  = "GoogleCloudPlatform/lb-http/google//modules/serverless_negs"
  version = "~> 9.0"
  ...
}
```
`terraform plan` in the new `test`environment went absolutely fine. The bug only occurs in existing terraform states (`prod`and `preprod`).

The bug appears after a `terraform init -upgrade`, no changes made.

I can push the full code on a public repo if it helps.

**Comment by rileykarson** [comment]
> Generally speaking, value out of range errors happen due to running on a 32-bit system....

A 32-bit system can only run a 32-bit binary but a 64-bit system can run either a 32-bit or 64-bit binary. This error generally happens when folks on an AMD64 system have accidentally installed an i386 binary- 32 bit systems are pretty rare nowadays.The big trap causing this to happen is on\ https://developer.hashicorp.com/terraform/install which lists i386/ARM before AMD64/ARM64 (and happens most commonly on Windows, where package managers are less ubiquitious. although that's not the case here):

![image](https://github.com/hashicorp/terraform-provider-google/assets/2080520/e197963b-2b12-4fb4-bd62-80b59d6c334c)

@bourdeau while your system is AMD64 as indicated by the x86_64 in your system version string, the Terraform binary you've downloaded is i386 (32-bit). In your original post see the results from `terraform -v`:

```
Terraform v1.6.6
on linux_386
```

For an AMD64 binary you'd expect `linux_amd64`. This is from my system where I'm using Terraform `1.5.2`:

```
Terraform v1.5.2
on linux_amd64
```

You should be able to replace your binary w/ the AMD64 one.

**Comment by rileykarson** [comment]
I reworked https://github.com/hashicorp/terraform-provider-google/issues/6518 into a canonical issue, deduplicating.
