### ISSUE TITLE
google_container_cluster: with enable_autopilot does not allow configuring gcp_filestore_csi_driver_config

### ISSUE THREAD

**Issue by terlar** [hashicorp/terraform-provider-google#17215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

v1.6.0

### Affected Resource(s)

google_container_cluster

### Terraform Configuration

```tf
resource "google_container_cluster" "autopilot" {
  provider = google-beta

  # ... rest of mandatory fields

  enable_autopilot = true
  addons_config {
    gcp_filestore_csi_driver_config {
      enabled = false
    }
  }
}
```
or
```tf
resource "google_container_cluster" "autopilot" {
  provider = google-beta

  # ... rest of mandatory fields

  enable_autopilot = true
  addons_config {
    gcp_filestore_csi_driver_config {
      enabled = true
    }
  }
}
```

### Expected Behavior

It should allow disabling or setting the `gcp_filestore_csi_driver_config`. Just like you can do via a cluster update via the CLI and/or the interface:

```
gcloud container clusters update CLUSTER_NAME --update-addons=GcpFilestoreCsiDriver=DISABLED
```

![image](https://github.com/hashicorp/terraform-provider-google/assets/280235/3ee44d85-518a-4adc-8843-3e34527c4441)

Right now I have to work around this via `terraform-google-modules/gcloud/google` and the update takes 30 minutes+ while the creation of the cluster just takes 8 minutes.

### Actual Behavior

`"addons_config.0.gcp_filestore_csi_driver_config": conflicts with enable_autopilot`

Is this due to creation of clusters not allowing doing this? But updates allow it.

### Steps to reproduce

1. `terraform apply`

b/324558621

**Comment by edwardmedia** [comment]
@terlar the error you received appear to be that addons is not supported by the autopilot. 

Take a look at the [comparison](https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison#add-ons) for the autopilot, you might see what are supported. 

Where did you see it should be as what you stated in `Expected Behavior`?

**Comment by terlar** [comment]
Thank you for the link. The addon is pre-configured, but can optionally be disabled:
https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/filestore-csi-driver#disable

I guess it is the same thing as with mesh certificates (cannot be enabled during creation). Filestore CSI driver cannot be disabled during creation.

But it is possible to disable the addon either via GCloud CLI and the Google Cloud Console.

I saw this in the linked documentation as well as in the Google Cloud Console on my own autopilot clusters (screenshot posted earlier).

**Comment by edwardmedia** [comment]
Yes, need to bring the behavior up to the same as other tools

**Comment by sunnylovestiramisu** [comment]
This is an intended behavior in AP cluster, gcp_filestore_csi_driver_config will always be enabled. 

We only allow customers to turn it on or off for standard clusters.

**Comment by terlar** [comment]
As you can see from my screenshot and earlier message that is not true. I do have autopilot clusters and I can disable filestore CSI driver both via `gcloud` and Google Cloud Console **after** cluster creation.

**Comment by philipsabri** [comment]
> This is an intended behavior in AP cluster, gcp_filestore_csi_driver_config will always be enabled.
> 
> We only allow customers to turn it on or off for standard clusters.

@sunnylovestiramisu  @leiyiz 

It is allowed to create an Autopilot cluster directly through the API with `gcpFilestoreCsiDriverConfig` set to disabled.

![image](https://github.com/user-attachments/assets/07cc77f6-7ef6-4ebf-b1f2-e508248b4274)
![image](https://github.com/user-attachments/assets/cf5fdd2a-316e-4675-ba75-fae995ad7364)
![image](https://github.com/user-attachments/assets/a78717eb-0f38-4da4-a606-e293bb0da9ce)


There is also [google documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/filestore-csi-driver#disable) confirming that you can disable it, although it is not recommended.

Allowing this configuration for Autopilot clusters would save time when creating new clusters, especially since it's permitted through the API:
```
    gcp_filestore_csi_driver_config {
      enabled = false
    }
```
