### ISSUE TITLE
Implement gcloud privateca certificates create within a resource

### ISSUE THREAD

**Issue by Roymprog** [hashicorp/terraform-provider-google#17506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Description

Opening a new issue, as [this issue](https://github.com/hashicorp/terraform-provider-google/issues/15102) is marked as resolved.

The provider does not seem to support having the CA Service create a private and public key for you. Eg.
```bash
gcloud privateca certificates create \
  --issuer-pool=POOL_ID \
  --ca=ROOT_CA_ID \
  --generate-key \
  --key-output-file=KEY_FILENAME \
  --cert-output-file=CERT_FILENAME \
  --dns-san=DNS_NAME
```

IMO the [proposed solution](https://github.com/hashicorp/terraform-provider-google/issues/15102#issuecomment-1629705639) (or rather workaround) isn't sufficient. The [private_key](https://registry.terraform.io/providers/hashicorp/tls/4.0.4/docs/resources/private_key) resource explicitly states not to use this in a production environment, which disqualifies the proposed solution in many cases. 

### New or Affected Resource(s)

google_privateca_certificate - My expectation is that this resource, or something like it, would provide .key and .cert outputs.

### Potential Terraform Configuration

```tf 
```

### References

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/privateca_certificate
- https://cloud.google.com/certificate-authority-service/docs/creating-certificate-authorities#test
- https://registry.terraform.io/providers/hashicorp/tls/4.0.4/docs/resources/private_key

**Comment by rileykarson** [comment]
The warning from that resource (`The private key generated by this resource will be stored unencrypted in your Terraform state file. Use of this resource for production deployments is not recommended.`) would apply here as well, as this resource would also store those values unencrypted in state, as that's a necessary step to export them / otherwise make them available through Terraform.

https://developer.hashicorp.com/terraform/language/state/sensitive-data contains some guidance on mitigating, with GCS-specific encryption settings on https://developer.hashicorp.com/terraform/language/settings/backends/gcs if that's your state backend.
