### ISSUE TITLE
Validation should know that google_monitoring_alert_policy periods can only be defined in seconds

### ISSUE THREAD

**Issue by runephilosof-karnovgroup** [hashicorp/terraform-provider-google#17566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.84.0
+ provider registry.terraform.io/hashicorp/google-beta v4.84.0

### Affected Resource(s)

google_monitoring_alert_policy

### Terraform Configuration

```tf
resource "google_monitoring_alert_policy" "smtpd_block_list" {
  display_name = "On a block list"
  combiner     = "OR"
  conditions {
    display_name = "Log match condition"
    condition_matched_log {
      filter = "resource.type=\"gce_instance\"\nresource.labels.instance_id=\"vm.instance_id\"\nSEARCH(\"postfix `5.7.1` block list\")"
      label_extractors = {
        relay = "relay=([^,]*),"
      }
    }
  }

  alert_strategy {
    notification_rate_limit {
      period = "5m"
    }
    auto_close = "7d"
  }
  notification_channels = []
}
```

### Expected Behavior

From validate
```
    Invalid value at 'alert_policy.alert_strategy.notification_rate_limit.period' (type.googleapis.com/google.protobuf.Duration), Field 'period', Illegal duration format; duration must end with 's'
```

From apply
```
    Invalid value at 'alert_policy.alert_strategy.notification_rate_limit.period' (type.googleapis.com/google.protobuf.Duration), Field 'period', Illegal duration format; duration must end with 's'
```

### Actual Behavior

From validate
```
Success! The configuration is valid.
```

From apply
```
    Invalid value at 'alert_policy.alert_strategy.notification_rate_limit.period' (type.googleapis.com/google.protobuf.Duration), Field 'period', Illegal duration format; duration must end with 's'
```

### Steps to reproduce

1. `terraform validate`
1. `terraform apply`

b/329712857

**Comment by ggtisc** [comment]
Hi @runephilosof-karnovgroup!

Your point isn't clear according to what you say. It seems that you want that only seconds will be available for period argument, but this isn't possible since it can have values with seconds, minutes, hours or days.

If you have a different issue, please be more specific and share the complete description of it.

**Comment by runephilosof-karnovgroup** [comment]
I can see why it was hard to figure out what I meant.
I have updated the description now.

The problem is that when you apply, it only allows seconds.
So this bug can be fixed either by having `apply` convert it to seconds before sending it to the api, or by having `validate` know about this rule.

**Comment by ggtisc** [comment]
Thank you @runephilosof-karnovgroup!

Issue confirmed: `notification_rate_limit.auto_close` only accept values in seconds but it isn't specified that way in the documentation.

**Comment by roaks3** [comment]
Changing this to a documentation request, to make sure that https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#period mentions that only seconds can be used.

We generally don't add client-side validation for cases like this because they need to be kept up to date (for example, minutes or millis could be supported in the future) and the server already does the validation during apply. This is an older comment that makes the same point: https://github.com/hashicorp/terraform-provider-google/issues/5687#issuecomment-670183171.
