### ISSUE TITLE
google_spanner_database name regex in docs does not match validation regex

### ISSUE THREAD

**Issue by wrdls** [hashicorp/terraform-provider-google#17608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version

n/a

### Affected Resource(s)

google_spanner_database

### Terraform Configuration

https://github.com/hashicorp/terraform-provider-google/blob/3b7a3182b7fcea3e6d83887f98c984f212a3db6c/google/services/spanner/resource_spanner_database.go#L158-L160

According to the docs you can only use hyphen `-` as a separator, but the actual regex also allows underscores `_`.

b/330226614

**Comment by ggtisc** [comment]
Hi @wrdls! As the message says both `_` and `-` are valid, but what is the source of this? is this an official source? did you presented any issue? is this a question? please provide a complete explanation to understand your situation with Debug output, expected behavior, steps to reproduce, Important factoids, References, Code, and other things that you consider relevant for this.

**Comment by wrdls** [comment]
@ggtisc How is this not an official source? It's a link to code in this repo? 

Look carefully at the regex in the validation function and the one in the description, they don't match.

The description is what most people will see in the [Terraform docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database#name) so it is important this is correct.

**Comment by ggtisc** [comment]
Yes, I'm talking about the complete explanation of this because it was generated as a bug, but with the last is confirmed that it is a documentation issue. Thanks for the information.

It is confirmed that the information in the next 2 links don't match and may cause confusion:

1. https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database#name
2. https://github.com/hashicorp/terraform-provider-google/blob/3b7a3182b7fcea3e6d83887f98c984f212a3db6c/google/services/spanner/resource_spanner_database.go#L158-L160
