### ISSUE TITLE
Dispatch MM unit test workflows based on modular-magician downstream SHAs instead of branches

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#17924]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

We currently dispatch workflows like https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.github/workflows/test-tgc.yml based on a branch, which can lead to issues with TGC specifically where it can end up installing an older version of TPG (and then failing to compile) - for example, https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/8759519595/job/24042712410.

This could also hypothetically lead to race conditions if multiple commits are pushed close to each other, resulting in unit tests running for a newer SHA than intended.

We should pass specific SHAs to GHA workflows - and for TGC we should pass a SHA for TPGB in addition to one for TGC.

Ideally we would pass the downstream SHAs from the cloud build step that commits them to the steps that consume them, but I'm not sure offhand whether cloud build supports that.

**Comment by shuyama1** [comment]
> This could also hypothetically lead to race conditions if multiple commits are pushed close to each other, resulting in unit tests running for a newer SHA than intended.

I don't think this is possible as we use [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) to [group the same job runs for each PR (with different commits)](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.github/workflows/test-tgc.yml#L27), so as soon as a new commit is pushed, it will kick off a new job and the old one will be cancelled immediately. So I think the issue for this is always that the TGC is built on an older version of TPGB due to some caching issues, as we use upstream branch `@auto-pr-xxxx` to patch the version. Removing cacheing should potentially resolve this issue easily, I think. But I don't think it's a desirable approach that we'd like to move forward with. And yes, passing the exact upstream commit SHA is definitely more "correct" in this case. I followed the [Cloud Build Guide](https://cloud.google.com/build/docs/configuring-builds/pass-data-between-steps#passing_data_using_workspaces) to pass upstream commit SHA between build steps, but I just wish there's a more "straightforward" or "elegant" way for GCB to do the job
