### ISSUE TITLE
Confusing failures of missing-test-detector

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#17943]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

Sometimes the missing test detector falsely flags that a given field isn't present in a test. If there's a problem with the tool it should be updated, or if people are misunderstanding the feedback the tool is giving there should be additonal documentation etc. For example if the tool can it only look at generated tests and cannot inspect handwritten tests then the PR reviewer can ignore the feedback confidently if they know this and confirm the PR adds a handwritten test.

### References

Example of the tool being confusing: https://github.com/GoogleCloudPlatform/magic-modules/pull/10515#issuecomment-2074431487

**Comment by rileykarson** [comment]
Note: There is sometimes misleading feedback. In this case the user used a block for a map & there was an error prompting the failure. There are some cases where the missing test detector does not properly find test cases due to different config formattings.

We could encourage contributors to self-explore failures in docs or make the test format more prescriptive.

Closing this as a general issue; but we should file bugs for specific failures or confusing cases.
