### ISSUE TITLE
Error: Error creating LocationTagBinding: - no such host

### ISSUE THREAD

**Issue by reken-rich** [hashicorp/terraform-provider-google#18704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.9.2
on ubuntu-latest github runner
+ provider registry.terraform.io/hashicorp/google >=5.31.1
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X - not included

### Affected Resource(s)

google_tags_location_tag_binding

### Terraform Configuration

from plan output
```
resource "google_tags_location_tag_binding" "allUsersIngress" {
      + id        = (known after apply)
      + name      = (known after apply)
      + parent    = "//run.googleapis.com/projects/819362295409/locations/us-central1/services/internal-docs"
      + tag_value = "768892404956/allUsersIngress/True"
    }
```

### Expected Behavior

tag bound to cloud run service

### Actual Behavior

<img width="663" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/157654065/56e0bacc-650e-4507-aa4c-17302115138d">

### Steps to reproduce

1. `terraform apply`

**Comment by ggtisc** [comment]
Hi @reken-rich!

I tried to replicate this issue, but you don't share any code, just the result of the terminal. For this reason I test the functionality with the base example of [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_tags_location_tag_binding#example-usage---cloud-run-service)

But after this the result was successful without errors. I suggest you check the documentation, your project configuration and permissions.

Additionally this is the used code:

resource "google_cloud_run_service" "crs_18704" {
  name     = "crs-18704"
  location = "us-central1"

  template {
    spec {
      containers {
        image = "us-docker.pkg.dev/cloudrun/container/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}

resource "google_tags_tag_key" "tag_key_18704" {
  parent      = "organizations/1234567890"
  short_name  = "tag-key-18704"
  description = "something"
}

resource "google_tags_tag_value" "tag_value_18704" {
  parent      = "tagKeys/${google_tags_tag_key.tag_key_18704.name}"
  short_name  = "tag-value-18704"
  description = "something"
}

resource "google_tags_location_tag_binding" "tag_binding_18704" {
  parent    = "//run.googleapis.com/projects/my-project-name/locations/us-central1/services/${google_cloud_run_service.crs_18704.name}"
  tag_value = "tagValues/${google_tags_tag_value.tag_value_18704.name}"
  location  = "us-central1"
}

If you still continue with issues, we are going to need your full code, preferably without variables, locals and modules, because unless you also want to share an example of its values.

It is important to say that if you have sensitive data you could use examples like this:
- project = "my-project-name"
- org_id = 1234567890
- user = "my-user@my-domain.com"

**Comment by reken-rich** [comment]
I think the problem was that I did not set the location in the tag binding
resource, but that error message was certainly not helpful in figuring that
out.

**Comment by ggtisc** [comment]
Yes, I suggest you check the [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_tags_location_tag_binding#example-usage---cloud-run-service) and the [APi documentation](https://cloud.google.com/resource-manager/reference/rest/v3/tagBindings). It is always a good practice to review the APIs before using them to know how they work and how they are structured
