### ISSUE TITLE
BigQuery Salesforce Transfer | Requested entity was not found

### ISSUE THREAD

**Issue by RomeoAva** [hashicorp/terraform-provider-google#19018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

terraform version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v5.40.0

### Affected Resource(s)

After this fix has been pushed: https://github.com/hashicorp/terraform-provider-google/issues/18506

I went ahead and upgrade my Terraform to use v5.40.0 of Google provider.

### Terraform Configuration

```tf
resource "google_bigquery_data_transfer_config" "salesforce_account_import" {
  display_name           = "Salesforce Account Import"
  location               = "US"
  data_source_id         = "accounts"
  destination_dataset_id = "analysis"
  project                = var.projects[terraform.workspace]
  params = {
    "connector.authentication.oauth.clientId"     = data.google_secret_manager_secret_version.salesforce_consumer_key_version.secret_data
    "connector.authentication.oauth.clientSecret" = data.google_secret_manager_secret_version.salesforce_consumer_secret_version.secret_data
    "connector.authentication.oauth.myDomain"     = var.salesforce_url[terraform.workspace]
    "assets"                                      = "[Account]"
  }
}
```

### Debug Output

```
google_bigquery_data_transfer_config.salesforce_account_import: Creating...
╷
│ Error: Error creating Config: googleapi: Error 404: Requested entity was not found.
│ 
│   with google_bigquery_data_transfer_config.salesforce_account_import,
│   on bigquery_transfers.tf line 13, in resource "google_bigquery_data_transfer_config" "salesforce_account_import":
│   13: resource "google_bigquery_data_transfer_config" "salesforce_account_import" {
```

### Expected Behavior

To create the BQ Transfer

### Actual Behavior

Errors out. I think a point to look at is that between the first issue I posted and this one Google's documenation on how to create a BQ Salesforce Transfer has changed: https://cloud.google.com/bigquery/docs/salesforce-transfer

You no longer Salesforce Username/Password and Security Token

Maybe they also changed their backend URL to create a new transfer?

**Comment by ggtisc** [comment]
Hi @RomeoAva!

You are getting this error because you are trying to use an invalid value for `data_source_id`.

According to the documentation there isn't any data source called `accounts` for `google_bigquery_data_transfer_config`.

it's not possible to use a custom data source directly with the `google_bigquery_data_transfer_config` resource in Terraform.

`BigQuery Data Transfer Service` provides a predefined set of connectors for integrating with various data sources. These connectors are built and maintained by Google to ensure compatibility and reliability.

Here's the official Google Cloud documentation [link](https://cloud.google.com/bigquery/docs/dts-introduction) where you can find a comprehensive list of supported data sources for the BigQuery Data Transfer Service

Finally I suggest you read the [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config#params) and [API documentation](https://cloud.google.com/bigquery/docs/cloud-storage-transfer#bq) before you start using this resource because there are a set of rules you may take in consideration.

**Comment by RomeoAva** [comment]
> Hi @RomeoAva!
> 
> You are getting this error because you are trying to use an invalid value for `data_source_id`.
> 
> According to the documentation there isn't any data source called `accounts` for `google_bigquery_data_transfer_config`.
> 
> it's not possible to use a custom data source directly with the `google_bigquery_data_transfer_config` resource in Terraform.
> 
> `BigQuery Data Transfer Service` provides a predefined set of connectors for integrating with various data sources. These connectors are built and maintained by Google to ensure compatibility and reliability.
> 
> Here's the official Google Cloud documentation [link](https://cloud.google.com/bigquery/docs/dts-introduction) where you can find a comprehensive list of supported data sources for the BigQuery Data Transfer Service
> 
> Finally I suggest you read the [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigquery_data_transfer_config#params) and [API documentation](https://cloud.google.com/bigquery/docs/cloud-storage-transfer#bq) before you start using this resource because there are a set of rules you may take in consideration.

Aaaaahh silly me. I misunderstood the purpose of `data_source_id`. Thank you for the clarifications again!
