### ISSUE TITLE
Problem with PR review blocking via .ci/magician/github/membership.go

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#19032]
### What kind of contribution is this issue about?

Other (specify in details)

### Details

I was just on PTO and added [the dates into .ci/magician/github/membership.go here](https://github.com/GoogleCloudPlatform/magic-modules/blob/fdf0c088f9ad24207e61421c5810ebbbb1032b2a/.ci/magician/github/membership.go#L71-L73).  That change was [committed 5 days ago](https://github.com/GoogleCloudPlatform/magic-modules/commit/d01df11295e34416ad4f2eebfde9f700e2dc96eb) from today (Aug 7th) and marked me as on PTO up to and including yesterday (Aug 6th). 

However during that period (2 days ago, Aug 5th) I was assigned this PR to review https://github.com/GoogleCloudPlatform/magic-modules/pull/11356

Making this issue to either figure out what I did wrong or to help identify a bug?

**Comment by trodge** [comment]
Your commit (3559f) which added your vacation doesn't appear in the [history of the PR you were assigned to review](https://github.com/kautikdk/magic-modules/commits/7372b21dabf261e61fddae55ffe646efd32149b0/).

Based on this, I think the solution is going to involve always checking out the latest version on the main branch of `onVacationReviewers`, which will be simpler if it is in its own file.

**Comment by SarahFrench** [comment]
That makes sense, thanks for investigating!

**Comment by melinath** [comment]
Looked into this with Thomas earlier - for posterity, the issue wasn't that the commit wasn't in the history of the _PR_, because the review request always runs on the latest version of the PR's base branch. The issue was that this PR was for 6.0.0, and the vacation file in the 6.0.0 branch was out of sync with the main branch at that time. The fix is likely the same, though: checking out the main branch of the repo prior to requesting review. (Doesn't need to just be the membership file.)
