### ISSUE TITLE
Docs make importing `google_monitoring_alert_policy` … hard

### ISSUE THREAD

**Issue by roy-work** [hashicorp/terraform-provider-google#19453]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v5.23.0

### Affected Resource(s)

* `google_monitoring_alert_policy`

### Terraform Configuration

```tf
resource "google_monitoring_alert_policy" "example" {
  project = "example"
  display_name = "example-alerts"

  combiner     = "OR"
  conditions {
    display_name = "test condition"
    condition_threshold {
      filter     = "metric.type=\"compute.googleapis.com/instance/disk/write_bytes_count\" AND resource.type=\"gce_instance\""
      duration   = "60s"
      comparison = "COMPARISON_GT"
      aggregations {
        alignment_period   = "60s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  user_labels = {
    foo = "bar"
  }
}

```

### Expected Behavior

To be able to import these

### Actual Behavior

The docs say to just use `{{ name }}`, which since these are project-scoped, basically cannot be correct; there must be a project ID in there, somewhere.

In `gcloud`, there is however a `name` field:
```yaml
name: projects/example/alertPolicies/123456789
```

If I attempt to use that, however,

```
» terraform import 'google_monitoring_alert_policy.example' 'projects/example/alertPolicies/123456789'
google_monitoring_alert_policy.example: Importing from ID "projects/example/alertPolicies/123456789"...
╷
│ Error: project: required field is not set
│
│
╵
```
[The code](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/monitoring/resource_monitoring_alert_policy.go#L1483) seems to want a space-separated project ID; if we try that:

```
» terraform import 'google_monitoring_alert_policy.example' 'example 123456789'
google_monitoring_alert_policy.example: Importing from ID "restricted-ops 123456789"...
google_monitoring_alert_policy.example: Import prepared!
  Prepared google_monitoring_alert_policy for import
google_monitoring_alert_policy.example: Refreshing state... [id=example 123456789]
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "google_monitoring_alert_policy.example", the provider detected that no object exists with the given id. Only
│ pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply"
│ to create a new remote object for this resource.
╵
```

I was about to submit this bug report and tried one last permutation:
```
» terraform import 'google_monitoring_alert_policy.example' 'example projects/example/alertPolicies/123456789'
```

That worked. I think the documentation could probably be better here… and help me understand what `name` is referring to? (As it doesn't match the name a user supplies in the UI.)

(So, if you're reading this and wondering how to get that string, run,
```
gcloud alpha monitoring policies list --project $PROJECT_ID
```
and it's the `name` field.)

### Steps to reproduce

1. `terraform import google_monitoring_alert_policy.…`

b/368130892

**Comment by hao-nan-li** [comment]
Imported ID format pointer: https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/monitoring/resource_monitoring_alert_policy.go#L1478

**Comment by ggtisc** [comment]
Confirmed issue!

After following the steps and checking out in the documentation and in the @hao-nan-li shared [link](https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/monitoring/resource_monitoring_alert_policy.go#L1478) results very complicated to import this resource and the [terraform registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/monitoring_alert_policy#import) documentation doesn't help so much.

**Comment by rileykarson** [comment]
Note: This could also be resolved by making import easier (i.e. not requiring the separate project), not just a docs fix.

**Comment by ScottSuarez** [comment]
I've looked into solving this but there isn't a simple fix at the generator level without introducing complexity or new implied behavior. I can think for 5 potential solutions to this problem:

1. Invent some new syntax for import format that will allow condition decomposition of parameters. For example ({{%name}}=>projects/{{project}}). Here name is taken directly as a parameter but the the new => syntax can inform the generator to try and decompose projects/{{project}} from name.
2. Imply some behavior based on {{%name}} syntax. If we are importing a full name as a value we can try to (at import time) infer some standard imports (project/location/etc) if present on the schema.
3. Enforce custom import functions to supply an associated import format. The issue here appears that at submission time the [import format](https://github.com/GoogleCloudPlatform/magic-modules/blob/7a6b526edbeed3855fcfb3ea2c8a7dbb3e44ca55/mmv1/products/monitoring/AlertPolicy.yaml#L31-L33) is different from the [custom import behavior](https://github.com/GoogleCloudPlatform/magic-modules/blob/7a6b526edbeed3855fcfb3ea2c8a7dbb3e44ca55/mmv1/templates/terraform/custom_import/self_link_as_name.tmpl#L5). Enforcing the custom import function to supply the import format could avoid this behavior.
4. Fix flattener from self_link to be more tolerant of only receiving name. Attempt to auto infer project.
5. Fix the import format values on this one and others (no generator changes).
