### ISSUE TITLE
Failing test(s): TestAccDataSourceArtifactRegistryDockerImage

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#20257]
### Impacted tests

- TestAccDataSourceArtifactRegistryDockerImage

### Affected Resource(s)

- google_artifact_registry_docker_image

### Failure rates

- 100% since 2024-08-27

### Message(s)

```
 data_source_artifact_registry_docker_image_test.go:21: Step 1/1 error: Check failed: Check 4/10 error: Not found: data.google_artifact_registry_docker_image.testDigest in [root]
```

Previously this test was failing with a different message: https://github.com/hashicorp/terraform-provider-google/issues/18955

This message showed up after the merge of https://github.com/GoogleCloudPlatform/magic-modules/pull/11492

### Nightly build test history

https://hashicorp.teamcity.com/test/4451008058123925132?currentProjectId=TerraformProviders_GoogleCloud_GOOGLE_NIGHTLYTESTS&expandTestHistoryChartSection=true&expandedTest=build%3A%28id%3A225430%29%2Cid%3A2000000000

b/378153871

**Comment by brandonmichigangithub** [comment]
We don't have access to this project and can't really see what the failures are caused by.
Does the project actually have a "testDigest"?

**Comment by NickElliot** [comment]
It looks like the failure is caused by the line [here](https://github.com/hashicorp/terraform-provider-google/blob/a4968bb376e0edb2674e622cd5f1124597863572/google/services/artifactregistry/data_source_artifact_registry_docker_image_test.go#L33). It wasn't removed alongside the removal of the test data sources that pointed to the digest files we didn't own.

**Comment by melinath** [comment]
@NickElliot could you share the test logs on the internal ticket? @brandonmichigangithub is there anything else you need?
