### ISSUE TITLE
Feature Request: Google Cloud SQL import from Cloud Storage

### ISSUE THREAD

**Issue by jakon89** [hashicorp/terraform-provider-google#203]
Hello!

In Google Cloud SQL, once instance is created, it's possible to import custom file (.sql or .csv) in order to populate/create schema etc. File has to be imported from Cloud Storage bucket.

As Cloud SQL import is implemented as separate endpoint in Google Cloud GO API Client (https://github.com/google/google-api-go-client/blob/master/sqladmin/v1beta4/sqladmin-gen.go#L4806) it would be great to have it as a new resource. 

What do you think?

Thanks, Adam

**Comment by slevenick** [comment]
I've done some investigating into this and we have decided to not support it in the provider at this time.

The reasoning for this is that while the import job is supported at the SQL instance level, the import requires databases and tables to be already set up. While databases can currently be created through this provider, tables cannot be. Without a declarative way to provision tables within the database we are unable to ensure that the table exists before running an import job. Creating tables is typically done through SQL statements executed on the instance, and it is my opinion that importing should be done in the same way as it is an imperative operation rather than declarative

If we were to support this feature in the future it would make sense to split it out from the SQL instance resource because of numerous circular dependency issues. 

Summary of these issues:
Reading a CSV from a GCS bucket requires the SQL instance's service account to have certain permissions on the object. This service account is created during instance creation and has a generated name
Importing is done as a SQL user. SQL users are created on instances after the instance exists
Import jobs run against a database and table, which cannot be created until the instance is created
