### ISSUE TITLE
Support for staging Dataflow templates

### ISSUE THREAD

**Issue by fwinokur** [hashicorp/terraform-provider-google#2076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

In using Dataflow templates, we must stage the template by running a Python script (can also use the Java SDK) [see Creating and staging templates section](https://cloud.google.com/dataflow/docs/templates/creating-templates).  We must also run this script after any updates to the various templates.  Also, it must be run in the case of a new workspace (post-GCS bucket creation).  It would be really nice to manage the template staging process via Terraform.

### New or Affected Resource(s)
New:
* google_dataflow_template

This is a prerequisite for running:
* google_dataflow_job

### Potential Terraform Configuration

```tf
resource "google_dataflow_template" "transform_template" {
    name = "tsv-transform"
    template_location = "gs://my-bucket/templates/template_file"
    staging_location = "gs://my-bucket/templates/staging"
    temp_gcs_location = "gs://my-bucket/tmp_dir"
}
```

## References:

* b/180932593

**Comment by c2thorn** [comment]
Not sure if the `Upstream` tag still applies here. Removing to generate discussion in the next triage.

**Comment by c2thorn** [comment]
Supporting this resource would likely require both creating and launching via: https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.templates

**Comment by rileykarson** [comment]
I'm definitely not experienced with Beam or Dataflow, so it's very possible I'm getting this wrong. AIUI this isn't a request for launch/create w/ [cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.templates](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.templates), but is actually a request to stage the files required to run those commands in a GCS bucket using Terraform. It's closer to a request to expand a template file and then upload a GCS object, if anything, although it's a little messier than that.

Additionally I looked at the AWS and Azure providers and didn't find equivalents, in their products that are comparable to Dataflow. Again, not a subject matter expert, so I'd be glad to be corrected. In fact, templates in general appear to be unique to Dataflow (and most documentation I can find refers to flex templates, rather than classic ones). 

It looks like templates can be generated by running Beam with [certain flags in the Java and Python environments](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates#create-and-stage-a-classic-template), although not w/ Go (Dataflow [runners](https://beam.apache.org/get-started/quickstart-go/#run-wordcount) are supported with Go, though). Creating a template requires executing code on a per-job type basis, generating a representation of the job type in JSON (["A classic template contains the JSON serialization of a Dataflow job graph."](https://cloud.google.com/dataflow/docs/concepts/dataflow-templates#comparing-flex-templates-and-classic-templates)). It's possible that this is a simple JSON representation similar to flex templates, which seem [fairly simple to create with generic Terraform resources](https://binx.io/2022/07/28/a-declarative-approach-for-dataflow-flex-templates/), but all the documentation I've read suggested executing arbitrary code per-template is required.

What makes this difficult to represent with a Terraform resource is that bit- compiling and running Java code, or executing Python code on the user's machine. That's not something we'd love the Google provider to do, to start with! A user could probably do it themselves with a  `null_resource` and a `local_exec` provisioner, however.

That leaves us in a spot where:

* If this requires executing Java/Python code, this doesn't belong in the Google provider and should be managed by users manually with `null_resource`+`local_exec`
* If we can skip the Java/Python execution, publishing a JSON file directly to a GCS bucket similar to https://binx.io/2022/07/28/a-declarative-approach-for-dataflow-flex-templates/ is probably the best Terraform-y approach, possibly w/ a module to provide a clear interface on top of the object resource

I'm moderately inclined to close this as `wontfix` as a result, but don't feel confident enough in my conclusion to do so. I'm gonna shuffle around some metadata here + on an internal-to-Google bug to indicate that this is blocked.

**Comment by rileykarson** [comment]
Based on lack of pushback to my last response, closing.
