### ISSUE TITLE
Support for Spanner DB schema migrations

### ISSUE THREAD

**Issue by SargisPlusPlus** [hashicorp/terraform-provider-google#2082]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

We use google_spanner_database DDL functionality to define schema for our database. When schema changes, new tables are added or removed, entire database has to be destroyed and recreated for the new changes to be applied. It would be nice not to destroy entire database when schema changes are introduced but instead run migrations to change schema accordingly.

### New or Affected Resource(s)

* google_spanner_database

**Comment by rakyll** [comment]
@SargisPlusPlus we (the Cloud Spanner team) was just looking into this because we think we shouldn't destroy any resources for DDL updates. 

Recently, we have been working on schema migration tool support lately (e.g. Flyway, Liquibase, etc). We also discussed whether Terraform is a good place for this but given provisioning is not always in the path of development and Terraform itself doesn't have the sophisticated capabilities that you mention, we were thinking about sticking to get the migration tool integrations right. How does that sound?

**Comment by nielm** [comment]
I wrote: https://github.com/GoogleCloudPlatform/spanner-schema-diff-tool as a way of generating non-destructive alter statements to migrate schemas...

**Comment by danawillow** [comment]
@rakyll I noticed you're now proposing that people not manage their schema in TF at all. I think this is probably smart- writing ALTER statements isn't really a great fit for a declarative tool, since it means the same config can't be applied to a blank slate to create the same environment.

We'll probably still want to have update support for these statements anyway though so that people who wish to perform updates through Terraform can do so and also so people who aren't paying attention don't accidentally delete their databases. That work is allocated for our next sprint (Aug 17-31)
