### ISSUE TITLE
Support migrating google_compute_instance across zones and regions.

### ISSUE THREAD

**Issue by spil-dbhagat** [hashicorp/terraform-provider-google#2730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Google supports migrating compute instances across zones and regions.
https://cloud.google.com/compute/docs/instances/moving-instance-across-zones

This is useful for rebalancing clusters with state for high availability (Galera, for example), without having to do a full rebuild. 

### New or Affected Resource(s)

* google_compute_instance

--->

* #0000

**Comment by AarshDhokai** [comment]
b/262380024

**Comment by AarshDhokai** [comment]
- The process of migrating compute_instances across zones and regions requires multiple steps to be followed as mentioned in this [document](https://cloud.google.com/compute/docs/instances/moving-instance-across-zones#moving-an-instance-manually).
- As per the docs, moving a VM instance across zone and region requires creating a machine image of your source VM as a first step, and that again requires multiple steps to perform because it isn't possible to do that in single API calls. So currently, the support for moving a VM instance across zone and region is available via gcloud commands and SDK calls.
The steps mentioned in this [doc](https://cloud.google.com/compute/docs/instances/moving-instance-across-zones#moving-an-instance-manually) requires multiple steps like : 1.Create a machine image of your source VM. 2.Create a VM from the machine image in a different zone or region. 3.Set the auto-delete state of disks to false 4.Create backups of your data by using persistent disk snapshots. 5.Delete your current VM. 6.Create another snapshot of both the boot disk and the data disk. Etc.
- Hence, to enable this functionality, it is essential to evaluate these steps. Once this workflow has been streamlined, we may move on to implementing it in Terraform, which requires more investigation.

**Comment by rileykarson** [comment]
While this would be possible to do, a zonal migration is a fairly complicated procedure that may wipe disks, change IP addesses, etc. per https://cloud.google.com/compute/docs/instances/moving-instance-across-zones. We're not planning to support this in the provider. 

Instead, we'd recommend using `terraform state rm`, `gcloud` to move the instance, and then importing it in its new location.
