### ISSUE TITLE
Instance redistribution enable/disable for instance group

### ISSUE THREAD

**Issue by bkoochin-clgx** [hashicorp/terraform-provider-google#3841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

There does not seem to be a way to set the "Instance Redistribution" on/off when building a managed instance group using google_compute_region_instance_group_manager. It defaults to "on". It would be useful if this could be disabled via Terraform.

If this feature already exists then it should be added to the documentation for google_compute_region_instance_group_manager.

### Versions

Terraform v0.12.0
provider.google v2.7.0
provider.google-beta v2.5.1

### New or Affected Resource(s)

google_compute_region_instance_group_manager

### References
https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html

* #0000

**Comment by emilymye** [comment]
I'm not sure what you mean by "instance redistribution" - do you have a link to the docs describing the feature? 

If you mean general redistribution of instances across zones, I was under the impression that instance redistribution is a key component of regional instance group management and that if you don't want instances to be redistributed, you should probably be creating unmanaged (zonal-only) instance groups. If you only need to specify specific zones to distribute across, you can provide that via `distribution_policy_zones`, or if you are having trouble with instance auto-updating you could also look at changing the `rolling_update_policy` or `auto_healing_policies` in the beta provider resource. Otherwise the [API](https://cloud.google.com/compute/docs/reference/rest/v1/regionInstanceGroupManagers/insert) itself does not really provide a way to change how it distributes instances across zones.

**Comment by bkoochin** [comment]
Sorry, I'm talking about "proactive instance redistribution", documented here:

https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#Proactive-instance-redistribution

https://cloud.google.com/compute/docs/instance-groups/distributing-instances-with-regional-instance-groups#disabling_and_reenabling_proactive_instance_redistribution

This feature will actively shut down instances and launch them in new AZs if the numbers become uneven.

**Comment by sanghaniJ** [comment]
b/262361977
