### ISSUE TITLE
google_cloudbuild_trigger is missing some parameters

### ISSUE THREAD

**Issue by jackivanov** [hashicorp/terraform-provider-google#5108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The resource is missing some parameters that described [here](https://cloud.google.com/cloud-build/docs/build-config#options) (ie: options. artifacts, etc)

### New or Affected Resource(s)

* google_cloudbuild_trigger

### Potential Terraform Configuration

```tf
resource "google_cloudbuild_trigger" "app" {
  project     = google_project.app.id
  description = "Build app"

  trigger_template {
    project_id = google_project.app.id
    repo_name  = "app"
    tag_name   = var.tag_name
  }

  build {
    step {
      name = "gcr.io/cloud-builders/docker"
      id   = "Build"
      args = [
        "build",
        "-f", "Dockerfile",
        "-t", "eu.gcr.io/$PROJECT_ID/app:latest",
        ".",
      ]
    }

    images = [
      "eu.gcr.io/$PROJECT_ID/app:latest",
    ]

    options = {
      machineType = "N1_HIGHCPU_8"
    }
  }
}
```

### References

* #4844

**Comment by preston-hf** [comment]
It would be nice if we could set the logsBucket at least. Cloud build is almost useless on a team without being able to specify this parameter, since the default logsBucket requires Owner permission on the project to see the logs.

**Comment by achew22** [comment]
Is there a timeline for these parameters? In particular without [logsBucket](https://cloud.google.com/cloud-build/docs/build-config#logsbucket) being set, it's very difficult to use this on a team.

I'm trying to gauge if we should hack around it or if the enhancements work on our timescale.

Thanks so much!

**Comment by AlfatahB** [comment]
b/262663909

**Comment by AlfatahB** [comment]
I've looked into this issue and the following are the details that I have found out:
- It seems like this issue requests to add support for multiple fields in the `google_cloudbuild_trigger` resource.
> The resource is missing some parameters that described [here](https://cloud.google.com/cloud-build/docs/build-config#options) (ie: options. artifacts, etc)
- As per the link provided in the [above comment](https://github.com/hashicorp/terraform-provider-google/issues/5108#issue-534388551), this issue is targeting to add support for fields inside the [`Build` field](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#Build).
- These fields have already been supported in the [`google_cloudbuild_trigger` resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#build).
- There are a couple of PRs that add support to these fields. The links to the PRs are available [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/3627) and [here](https://github.com/GoogleCloudPlatform/magic-modules/pull/3944).

Hence, Closing this issue. If there is a need to support other fields, then please open a new issue that briefly describes the fields to be supported. Thanks!
