### ISSUE TITLE
Uniform access control for storage bucket

### ISSUE THREAD

**Issue by elsbrock** [hashicorp/terraform-provider-google#5875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Google Cloud Security Command Center recommends using storage buckets with uniform access control. I am unable to find information about this in the provider docs, so I assume this is currently not supported.

### New or Affected Resource(s)

* google_storage_bucket

### References

see https://cloud.google.com/storage/docs/uniform-bucket-level-access

**Comment by danawillow** [comment]
Hey @elsbrock, we do support this via the [bucket_policy_only](https://www.terraform.io/docs/providers/google/r/storage_bucket.html#bucket_policy_only) field, which unfortunately was renamed at a product level after we had already added support, which is why it wasn't immediately obvious that it's the same thing. I'm going to relabel this as a documentation issue, because we can definitely do a better job at clarifying what that field is.

**Comment by elsbrock** [comment]
Perfect, thank you!
