### ISSUE TITLE
DialogueFlow fulfillment support

### ISSUE THREAD

**Issue by rangerscience** [hashicorp/terraform-provider-google#6086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support for setting DialogueFlow's fulfillment webhook.

### New or Affected Resource(s)

* google_dialogflow_agent

### Potential Terraform Configuration

```tf
resource "google_dialogflow_agent" "full_agent" {
  //..
  fulfillment: {
    uri = heroku_app.my_app.web_url
    username = "admin"
    password = "somethingSomething"
    request_headers = { ... }
  }
}
```

### References

API Docs:
https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent/getFulfillment
https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent/updateFulfillment
https://cloud.google.com/dialogflow/docs/reference/rest/v2/Fulfillment

* #0000

**Comment by rangerscience** [comment]
I'm interested in working on this myself, but I'm really not sure how to get started (particularly with regards to the modular magician). If someone would be so nice as to point me at some resources for that, I'll see what I can do.

**Comment by c2thorn** [comment]
Hi @rangerscience thanks for creating this, and for your interest in contributing! The Magic Modules repo [README](https://github.com/GoogleCloudPlatform/magic-modules) is definitely the best place to get you started. It has a link to a codelab that will give you an overview of Magic Modules and how to create resources.

Looking over Dialogflow Fulfillments specifically, it seems that this would be best created as another resource, similar to [Intents PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/3285). Feel free to take a look at that PR as well. Fulfillments is much smaller than Intents, so there won't be as many fields to add in the api.yaml file.

If you get going, I'd be happy to help and review your pull request. Otherwise, this will get tracked an prioritized as normal.

**Comment by rangerscience** [comment]
Fantastic :) I'm keeping an eye out for time to put into this, but releasing the stable features is taking priority (as they're the *first* features, this is pretty understandable....)

**Comment by jcanizalez** [comment]
Hi team I hope you don't mind but I raised a PR to fix this issue GoogleCloudPlatform/magic-modules#4808
