### ISSUE TITLE
Change Configuration of PubSub subscription which created by Background Cloud Function

### ISSUE THREAD

**Issue by callppatel** [hashicorp/terraform-provider-google#6135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

One of our need to set "Retained acknowledged messages" to "Yes" for the subscriptions which is created by default by Background Cloud Function Terraform module. Currently it set by default to "No".
 
Is there any alternative approach to achieve with terraform?

### New or Affected Resource(s)

* google_cloudfunctions_function

### Potential Terraform Configuration

```tf
# We should pass Pubsub configuration as the parameter as well in "event_trigger" field

event_trigger = { 
event_type = "google.pubsub.topic.publish"
event_resource = "backgroud-subs"
retry = "true" 
}


```

### References

* #0000

**Comment by danawillow** [comment]
If you know the name of the subscription, you could [import](https://www.terraform.io/docs/providers/google/r/pubsub_subscription.html#import) it, though that would make it fully managed by Terraform, and cause drift issues if GCP made changes to it behind the scenes.

Otherwise, I'm not sure there's a way for Terraform to know programmatically the name of the subscription that cloud functions creates- does it have an identity that we could compute, or is it totally random? If it's not something we could guess in the provider, then we'd need API support for something like that.

Ideally, this entire functionality would be something that could be set on the cloud functions API so that we wouldn't have to try to hack talking to pubsub into the functions resource. You can file a request in an [issue tracker](https://cloud.google.com/support/docs/issue-trackers) or through your GCP rep.

**Comment by sadatAliKhan** [comment]
Subscription name in case of background functions conforms to the format - gcf-cloud function name-region where CF is deployed-topic for which function is created

For e.g. gcf-function1-us-central1-topicfunction1

I agree this should be handled by the cloud function api as that is what exclusively controls the subscription lifecycle ( in the case of b/g functions ).

**Comment by rileykarson** [comment]
I'm going to close this out. While the information is available and it would be _possible_, it's outside of the scope of what we'd like to do in the Terraform resource. If this becomes a part of the cloud function API, we'll gladly implement it, though.
