### ISSUE TITLE
Please add a deletion_protection field for google_sql_database_instance

### ISSUE THREAD

**Issue by david-wb** [hashicorp/terraform-provider-google#7072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today a changed the `database_version` field on a `google_sql_database_instance` resource from

```tf
database_version = "POSTGRES_11"
```
to
```tf
database_version = "POSTGRES_12"
```

**This caused the database to be completely deleted, including the backups!** Luckily this was a dev database, but there needs to be a better way to prevent this type of thing from happening.

I've considered changing the IAM role permissions under which terraform is being run so that deletion is prevented. Unfortunately, that solution isn't quite good enough. Other engineers on the project might run terraform locally and with different permissions and run into the same issue. I strongly believe both terraform-provider-google and GCP itself should  provide mechanisms to prevent accidental sql instance deletion.

### New or Affected Resource(s)

* google_sql_database_instance

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_sql_database_instance" "db_instance" {
  database_version = "POSTGRES_12"
  name             = "db"
  settings {
    deletion_protection = true

    tier = "db-f1-micro"

    ip_configuration {
      ipv4_enabled    = true
      private_network = "projects/project-${var.env}/global/networks/default"
    }

    backup_configuration {
      enabled = true
    }
  }

  region = "us-west3"
}
```

### References

* #0000

**Comment by Chupaka** [comment]
@david-wb what was the plan? Was it "update in-place" or "destroy and create a new instance"?

Because looks like "lifecycle { prevent_destroy = true }" is out-of-the-box solution for such cases for any resource.

**Comment by david-wb** [comment]
@Chupaka True, I've started using `lifecycle { prevent_destroy = true }` which might suffice for this. What really bothers me is that if the database does get destroyed, the backups are destroyed as well, but that is a GCP problem not a Terraform problem.

**Comment by rileykarson** [comment]
@Chupaka: after setting a precedent for a `deletion_protection` field in Bigtable, we've decided it's something we'd like for databases generally within the provider. I think `3.45.0` will has the same for `google_spanner_database`, for example.

The difference between `deletion_protection` and `lifecycle.prevent_destroy` is that it's an opt-out field instead of opt-in. One of the most common operational errors users have is accidentally deleting resources, and databases are extremely difficult to recover! `deletion_protection` provides a _much_ safer default behaviour, and one where users don't need to remember to apply the `lifecycle` block.

It also works in the case that the config for the resource is no longer present, unlike `lifecycle`. Check out [this talk](https://www.youtube.com/watch?v=ix0Tw8uinWs) for an example that `deletion_protection` could have stopped!
