### ISSUE TITLE
Add an instance template test that provisions a scratch disk

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#7148]
During a [Slack conversation](https://googlecloud-community.slack.com/archives/C1VNJ4EG7/p1598647646023800) where someone was having trouble [doing the 3.0.0 instance template upgrade](https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#disks-with-invalid-scratch-disk-configurations-are-now-rejected), I noticed we're not testing an instance template config where a scratch disk is successfully provisioned.

That meant I couldn't easily pull up logs of what the API does- not the biggest deal, but instance template is one of the resources where that's pretty valuable. I suspect this may also expose a minor bug at import time, where the `disk_size_gb` is imported with a value of `0` when it should be `375`, but I can't guarantee that that's the case.

`TestAccComputeInstanceTemplate_invalidDiskType` contains an _invalid_ config, and removing the second disk block from that should give us a config we can apply successfully.

**Comment by nyc3-mikekot** [comment]
Hi @rileykarson; bumping this for visibility.

I originally reported this issue in the Slack channel; I've finally gotten around to trying to update our configuration for this old instance template that was provisioned in 2.20.0 for provider version 3.40.0. 

To start off, I added "disk_size_gb = 375" to the appropriate .tf file which has the resource definition for `google_compute_instance_template`. The plan then suggests the following:

```
   ~ disk {
            auto_delete  = true
          ~ boot         = false -> (known after apply)
          ~ device_name  = "local-ssd-0" -> (known after apply)
          ~ disk_size_gb = 0 -> 375 # forces replacement
            disk_type    = "local-ssd"
            interface    = "NVME"
          - labels       = {} -> null
          ~ mode         = "READ_WRITE" -> (known after apply)
          + source_image = (known after apply)
            type         = "SCRATCH"
        }
```

Of course, all of our scratch disks are listed as 375 GB in the console, but Terraform still suggests otherwise (even after I explicitly define `disk_size_gb` in the terraform configuration.

- Next, I tried manually editing the state file to change all mentions of `"disk_size_gb": 0` to `"disk_size_gb": 375`
   This did not work, and on refresh, `terraform plan` was suggesting the value of the disks were 0 again, even though I had modified the state file with a text editor.

- I also tried to `terraform state rm` the instance template from the state file, then `terraform import` it back. However, after running another plan, the same diff popped up saying the instance template (and anything depending on it) needs to be replaced since scratch disks are being "resized" from 0 to 375.

Please let me know if there's any other possible remediation I can take at this point. Thank you!

**Comment by rileykarson** [comment]
Hey @nyc3-mikekot! Would you mind filing an issue specifically for the problems you're encountering with the upgrade, filling out the bug template? This issue was intended to track a missing test case- which has now been added.

From my look at this problem before, I would have expected editing the state file to work. Weird! I suspect the value in the API is "sticky" so that if the value was sent on creation it gets returned, and otherwise it doesn't. Once an issue is filed someone on our team should take a look and determine how we can fix this for good 🙂

**Comment by nyc3-mikekot** [comment]
Sorry about that! #7341
