### ISSUE TITLE
google_storage_bucket_iam* does not allow project per the docs

### ISSUE THREAD

**Issue by GavBurke** [hashicorp/terraform-provider-google#7170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.23

### Affected Resource(s)

* google_storage_bucket_iam*

### Terraform Configuration Files

```tf
resource "google_storage_bucket_iam_member" "hidden_name_of_iam" {
  project = "my_changed_project"
  bucket  = "my_bucket_name"
  role    = "roles/storage.objectAdmin"
  member  = "serviceAccount:${module.dev-core-sch-tasks.service_account}"
}
```

### Debug Output

Error: Unsupported argument

  on permissions.tf line 2, in resource "google_storage_bucket_iam_member" "hidden_name_of_iam":
   2:   project = "my_changed_project"

An argument named "project" is not expected here.

### Expected Behavior

IAM policy is applied to the named bucket in the named project

### Actual Behavior

The terraform plan errors not expecting project

### Steps to Reproduce

1. Use above snip-it of code
2. `terraform plan`

**Comment by edwardmedia** [comment]
@GavBurke can you post the debug log?

**Comment by ct-dh** [comment]
Simple repro with debug log attached for a terraform plan:

```

provider "google" {
  project     = "some-project"
  region      = "europe-west1"
}

resource "google_storage_bucket_iam_member" "hidden_name_of_iam" {
  project = "my_changed_project"
  bucket  = "my_bucket_name"
  role    = "roles/storage.objectAdmin"
  member  = "bob"
}
```

[debug.log](https://github.com/hashicorp/terraform-provider-google/files/5195490/debug.log)

**Comment by GavBurke** [comment]
Thanks @ct-dh , sorry I completely forgot to come back to this @edwardmedia 

Just for info though, a colleague of mine suggested removing the project and let Google figure out itself which project the bucket is in, and to my surprise that just worked!

The original issue, however, is still prevalent in that the documentation says you can specify project in the bucket_iam resources but that doesn’t work

**Comment by edwardmedia** [comment]
@GavBurke by removing `project`, the Google provider will pick the default value you have already set on your box It will not work if you have not done so. Below is the link to the detailed description you may want to review. I am glad you have got the answer and closing this issue then. 

https://www.terraform.io/docs/providers/google/guides/provider_reference.html#project-1

**Comment by ct-dh** [comment]
@edwardmedia you seem to have misunderstood the issue. The provider docs state that you can supply the `project` attribute on the resource, but you can't. If you do the provider complains as below and the run fails. The easiest fix in my mind is to remove that attribute from the docs.

```
Error: Unsupported argument

  on main.tf line 12, in resource "google_storage_bucket_iam_member" "hidden_name_of_iam":
  12:   project = "my_changed_project"

An argument named "project" is not expected here.
```

Excerpt from the docs page at https://www.terraform.io/docs/providers/google/r/storage_bucket_iam.html:

```
project - (Optional) The ID of the project in which the resource belongs. If it is not provided, the project will be parsed from the identifier of the parent resource. If no project is provided in the parent identifier and no project is specified, the provider project is used.
```

**Comment by mvn-srizzari** [comment]
I'm also facing this issue in Terraform v0.13.3.  Seems like this was closed without addressing the problem brought up.  Can someone reopen it please?  Thanks in advance.

**Comment by edwardmedia** [comment]
This resource assigns a policy on a bucket which is global. It does not make sense to take a `project`.

**Comment by melinath** [comment]
b/169953815

**Comment by sairajm** [comment]
<img width="685" alt="Screen Shot 2021-09-17 at 3 48 56 PM" src="https://user-images.githubusercontent.com/11436510/133861369-87fa32f3-8961-412c-8da2-ebddd754468b.png">
FWIW, I still see the project in the documentation. I get @edwardmedia's point about not requiring it because bucket name is unique, but please do remove it from the docs. It's confusing. I see that https://github.com/GoogleCloudPlatform/magic-modules/pull/4899 is still open and that should fix it.

**Comment by mariux** [comment]
> This resource assigns a policy on a bucket which is global unique and which is already specified its relation to a project. It does not make sense to take a `project`. Agreed with @ct-dh suggestion, going to remove the `project` from the docs

we just had a case where we moved a bucket to a new project and the initial plan did not trigger any IAM recreation as terraform does not know about the underlying relationship. for terraform the bucket name stays the same so no changes were planned.

i assume there is a trigger missing if the underlying project of a bucket actually changes? we will work around this with explicit dependencies now in a module...

**Comment by roaks3** [comment]
I see that https://github.com/GoogleCloudPlatform/magic-modules/pull/4662 and https://github.com/GoogleCloudPlatform/magic-modules/pull/4899 were both attempts at fixing this, but they do not entirely work and have been stalled for quite a while. There is agreement that the `project` parameter should be removed from the docs, but in this case it is slightly more complicated because this line of the documentation is shared across many resources.

@mariux I think explicit dependencies are what you want to use in your case, but to clarify, that would be for the `google_storage_bucket` resource, correct? The IAM resource mentioned in this issue would most likely depend on the bucket implicitly by using something like `bucket = google_storage_bucket.default.name`. If that's the case, I would suggest creating a separate issue if you have a question about that configuration or think there is a problem with the provider. That will allow us to work on and close out this documentation issue independently.

**Comment by roaks3** [comment]
b/251565688
