### ISSUE TITLE
create gcp alert policy using terraform

### ISSUE THREAD

**Issue by ajishikea** [hashicorp/terraform-provider-google#7267]
Hi Team,

I am trying to create gcp alert policy using terraform but i dont have a feature to JSON file while creating the alert policy. Can we know is any way in terraform we can provide JSON file to create a alert policy. Since gcloud we have a option --policy-from-file. DO we have any functions like this?

`gcloud alpha monitoring policies create --notification-channels=[NOTIFICATION_CHANNELS,…] [--aggregation=AGGREGATION --condition-display-name=CONDITION_DISPLAY_NAME --condition-filter=CONDITION_FILTER --duration=DURATION --if=IF_VALUE --trigger-count=TRIGGER_COUNT     | --trigger-percent=TRIGGER_PERCENT] [--combiner=COMBINER --display-name=DISPLAY_NAME --no-enabled --user-labels=[KEY=VALUE,…] --documentation-format=DOCUMENTATION_FORMAT; default="text/markdown" --documentation=DOCUMENTATION     | --documentation-from-file=DOCUMENTATION_FROM_FILE] [--policy=POLICY     | --policy-from-file=POLICY_FROM_FILE] [GCLOUD_WIDE_FLAG …]`

**Comment by upodroid** [comment]
Hi

The Google SDK takes the policy in yaml/json and converts it to this object https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies . You can verify this by running it with `--log-http` flag and see the api calls.

That feature doesn't exist in terraform because you are expected to specify all the alertPolicy fields when creating the resource in terraform.

https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html

Generally, no one of those helpers in the SDK usually exist in terraform unless the api itself expects you to provide a file, like  https://www.terraform.io/docs/providers/google/r/deployment_manager_deployment.html for example.

Thank you

**Comment by edwardmedia** [comment]
@ajishikea is this still an question to you?

**Comment by ajishikea** [comment]
Hi Thanks. I understand in Alert policy we cant able to pass the file using terraform.

**Comment by edwardmedia** [comment]
@ajishikea I am glad you understand. closing this question then.
