### ISSUE TITLE
Fix TestAccProviderMeta_setModuleName

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#7370]
```
TestAccProviderMeta_setModuleName: provider_test.go:252: Step 1/2 error: Error running pre-apply refresh: 2020/09/28 04:24:24 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Unsupported block type
on config348816855/terraform_plugin_test.tf line 3, in terraform:
3:   provider_meta "google" {
Blocks of type "provider_meta" are not expected here.
```

Related to the new module attribution content - removed from the v3.41.0 release

**Comment by megan07** [comment]
Module Attribution will only work with terraform version `0.13.0` and above, however, due to the issue [here](https://github.com/hashicorp/terraform/issues/25961), many of our data source tests will fail if we update TC to use `0.13.0` right now. Once the fix for that issue is released, we can update the terraform version in TC and this should be fixed.

Our other option, which I believe we've discussed, is to run multiple runs of the provider against different versions of terraform. This would likely take longer to get it all working with our current set up.

Transferring this issue to @aareet and @rileykarson as a reminder to update the terraform version when `0.14.0` is released, as I'll likely be OOO.

**Comment by melinath** [comment]
I know we're talking about upgrading the terraform version shortly; will that fix this issue? In which case: would it make sense to pull into a sprint?

**Comment by rileykarson** [comment]
@megan07, what's your take?

**Comment by megan07** [comment]
I updated the version this morning, I'd say let's give it a try! From my previous note it seems as though it should work! I will make this change later today. Thanks!
