### ISSUE TITLE
Auto added annotations `serving.knative.dev/creator` and `serving.knative.dev/lastModifier` do not play well with Terraform

### ISSUE THREAD

**Issue by steren** [hashicorp/terraform-provider-google#7583]
Cloud Run automatically adds annotations to the created resources `serving.knative.dev/creator` and `serving.knative.dev/lastModifier` under `metadata[0].annotations` . This seems to cause troubles with Terraform (see [example](https://github.com/hashicorp/terraform-provider-google/issues/7518#issuecomment-712867246))

Would it be possible to ignore them by default?

It seems that adding this config helps:
```
lifecycle {
    ignore_changes = [
      metadata[0].annotations["serving.knative.dev/creator"],
      metadata[0].annotations["serving.knative.dev/lastModifier"]
    ]
  }
```

**Comment by rileykarson** [comment]
Precedent in https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_dataflow_job.go#L29, https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/node_config.go#L593

**Comment by rileykarson** [comment]
Retriaging to enhancement, since this is closer to additive behaviour than a bugfix.

**Comment by joshk0** [comment]
I disagree; this is an essential annotation for using `google_cloud_run_domain_mapping` so every single user of it will run into this issue, unless I'm mistaken.

By the way, the requirement for the BETA launch stage annotation was not originally there, and was added as a constraint later. I have resources in my tf state which are grandfathered in, it seems.

I think I'd rather have it set up so that if you're using the terraform resource, it automatically adds that annotation if it isn't there. That would solve the original issue without needing to mess with ignored annotations, since most people are likely to not use annotations at all after it is no longer required to specify the launch stage annotation.

**Comment by steren** [comment]
I do not understand the previous comment. My request is about serving.knative.dev/creator and serving.knative.dev/lastModifier annotations. Launch stage should not be ignored.

**Comment by steren** [comment]
The PR ignores everything that contains `serving.knative.dev`, which is dangerous IMO, the request was only to ignore `serving.knative.dev/creator` and `serving.knative.dev/lastModifier`

**Comment by joshk0** [comment]
> I do not understand the previous comment. My request is about serving.knative.dev/creator and serving.knative.dev/lastModifier annotations. Launch stage should not be ignored.

My point was that most people are only using annotations to specify launch-stage, and that's only required because you can't use `google_cloud_run_domain_mapping` without using a launch-stage anymore. So I proposed that an alternative solution might include implying the beta launch stage whenever the domain mapping resource is used within terraform, and that might 'dodge' the problem rather than mandate a fix like what went in.

Given the approach that was taken, I agree that the ignoring strategy is a bit excessive.

**Comment by ndmckinley** [comment]
I'll contact the author and see if they'd like to revise it.  You propose ignoring specifically and exclusively `serving.knative.dev/creator` and `serving.knative.dev/lastModifier`?

**Comment by upodroid** [comment]
Hey

I have used Knative and Cloud Run myself so i'm pretty confident there are no user settable annotations under the serving.knative.dev namespace.

I had a look at the API Spec for Knative Serving at https://knative.dev/docs/serving/spec/knative-api-specification-1.0/ and it looks like annotations like serving.knative.dev/* are set by other components of Knative that end users shouldn't be manipulating.

**Comment by ScottSuarez** [comment]
I have a PR to restrict the annotations to the specific values that Cloud Run adds. Better to be precise about what we ignore imo.

https://github.com/GoogleCloudPlatform/magic-modules/pull/4202
