### ISSUE TITLE
GCP provider 3.49 wants to delete all my disks

### ISSUE THREAD

**Issue by knyttl** [hashicorp/terraform-provider-google#7908]
### Terraform Version

`v0.12.29`

### Affected Resource(s)

* GCP provider 3.49

### Expected Behavior

I have upgraded the Terraform GCP provider from 3.35 to version 3.49 and suddenly all the disks are to be replaced, eg.:

```terraform
 # google_compute_disk.dev-disk-0 must be replaced
-/+ resource "google_compute_disk" "dev-disk-0" {
      ~ creation_timestamp        = "2018-10-01T01:32:53.214-07:00" -> (known after apply)
      ~ id                        = "projects/------/zones/----/disks/dev-disk-0" -> (known after apply)
      + interface                 = "SCSI" # forces replacement
```

I tried to fiddle with the `interface` field, but it does not help. Only found solution was to use:

```terraform
lifecycle {
  ignore_changes = [interface]
}
```
Which is not super-correct.

### Actual Behavior

Terraform want to delete all my disks.

**Comment by c2thorn** [comment]
@knyttl Sorry you are running into issues here. I don't think it was expected for `interface` to not have a value. If you set `interface=""` does the problem go away for you?

Otherwise, do you mind sending the debug logs when you run `terraform plan`? I'd like to see the configuration and API response.

**Comment by knyttl** [comment]
I confirm that `interface=""` helps here and the disk is not being replaced.

However I find this strange - because the disk already is `SCSI`, so why setting `interface="scsi"` should be causing replacement?

```
$ gcloud compute disks describe MY_DISK
creationTimestamp: '2019-11-03T10:17:21.742-08:00'
guestOsFeatures:
- type: VIRTIO_SCSI_MULTIQUEUE
```

**Comment by c2thorn** [comment]
@knyttl Thanks for that information. My hunch is that this is due to the provider not supporting `guestOsFeatures`, which would need some interaction with the `interface` field. Once the provider adds support for that, this issue would likely be resolved. Thankfully, there is a workaround for now. Appreciate your support in this.

**Comment by knyttl** [comment]
> Once the provider adds support for that, this issue would likely be resolved. 

Will this be tracked somewhere?

**Comment by c2thorn** [comment]
> Will this be tracked somewhere?

Good call, made https://github.com/hashicorp/terraform-provider-google/issues/8012 with a note explaining what happened here.
