### ISSUE TITLE
Handwrite Data Catalog Taxonomy Sweeper

### ISSUE THREAD

**Issue by c2thorn** [hashicorp/terraform-provider-google#7929]
### Affected Resource(s)

* google_data_catalog_taxonomy

When our CI project hits the limit of data catalog taxonomy resources, taxonomy tests get the unhelpful error message:
```
Error 400: Precondition check failed.
```
Based on b/144370106, this means we have too many unswept taxonomies from previous tests. The current sweeper https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/services/datacatalog/resource_data_catalog_taxonomy_sweeper.go does not work and should be handwritten. 

b/317497372

**Comment by melinath** [comment]
It looks like the problem here is that the generated sweepers assume that the resource will have a `name` that starts with `tf-test`, but google_data_catalog_taxonomy gets an autogenerated name from the API - so we'd have to rely on `display_name` instead. It would be good to also make sure that the display names include a hyphen or underscore so that the sweeper would pick them up.

**Comment by melinath** [comment]
Sweepers are documented at https://github.com/hashicorp/terraform-provider-google/wiki/Developer-Best-Practices#sweepers

**Comment by hao-nan-li** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/9908
