### ISSUE TITLE
Add support for Redis transit_encryption_mode

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

https://cloud.google.com/memorystore/docs/redis/reference/rest/v1beta1/projects.locations.instances#TransitEncryptionMode

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
transit_encryption_mode = "SERVER_AUTHENTICATION" # also exported server_ca_certs field
```

### References

* b/172923146

**Comment by schirayu** [comment]
Hi @rileykarson,
Would there be support for supplying a DNS name that can be included in the cert. I'm not seeing that in the API doc linked above. Also not sure if this is the right place to ask the question (apologies in advance if it is not).
Thanks!

**Comment by rileykarson** [comment]
I'm not sure how it would be attached given the current API. If you've got relevant documentation, I can try to help puzzle it out!

**Comment by heiny** [comment]
Google decided that consumers are required to download and install the CA certificates on the client side.  The problem is that developers are still required to disable peer verification because they don't currently support specifying a SAN for their self signed certificates.

The problem with disabling peer verification on the client is the fact that it can connect to the Redis instance without having to install the CAs, which is a security risk that may not be apparent.

Because of this oversight, they've provided consumers an appropriate amount of rope to hang themselves with.

**Comment by rileykarson** [comment]
Got it. I'm not sure that's something that's available through the [rest api](https://cloud.google.com/memorystore/docs/redis/reference/rest/v1beta1/projects.locations.instances#ConnectMode) so I don't think there's anything for Terraform to do here.

**Comment by rileykarson** [comment]
Sprint 3 or 4 seems likely, yeah. It appears the outstanding PR has a failing test & some output only fields that need to get added.
