### ISSUE TITLE
google_storage_bucket_object add ability to use Customer Supplied Encryption Keys

### ISSUE THREAD

**Issue by jaceq** [hashicorp/terraform-provider-google#8133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

I'd like to be able to encrypt objects in bucket with customer supplied encryption keys as per: https://cloud.google.com/storage/docs/encryption/customer-supplied-keys

### New or Affected Resource(s)
google_storage_bucket_object 

### Potential Terraform Configuration

```tf
resource "google_storage_bucket_object" "example" {
  name    = "some_example_name"
  bucket  = "some_example_bucket"
  content = "some_example_content"
  customer_supplied_encryption_key = "base64 encoded encryption key"
}

```

**Comment by jaceq** [comment]
@rileykarson is there any rough estimate when could this be done?

**Comment by rileykarson** [comment]
No estimates from our team at this time! If there's any discussion it'll be reflected here, generally by moving the milestone.

**Comment by jaceq** [comment]
Thx for info @rileykarson 
Is there any contribution that would make it faster? I mean adding an attribute is usually not so complicated, so I am happy to look into that. I assume this comes from magic modules... correct?

**Comment by rileykarson** [comment]
If you're interested, you can try to add it! This field is a little unusual because it's actually a header in the API, but that shouldn't be too big a deal.

You can [edit it here](https://github.com/hashicorp/terraform-provider-google/blob/master/google/resource_storage_bucket_object.go) (and we'll upstream as part of the review) or [in Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/terraform/resources/resource_storage_bucket_object.go). https://github.com/GoogleCloudPlatform/magic-modules/pull/4561/files is a good reference if you haven't contributed to a Terraform provider before.
