### ISSUE TITLE
Add a Firestore Security Rules resource

### ISSUE THREAD

**Issue by evamaxfield** [hashicorp/terraform-provider-google#8263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add the ability to set Firestore Security Rules with Terraform which would add the final missing piece of allowing full Firestore setup with Terraform rather than UI / CLI.

### New or Affected Resource(s)

* google_firestore_security_rules

### Potential Terraform Configuration

```tf
resource "google_firestore_security_rules" "public_read" {
  version = "2"
  rules = "
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read;
    }
  }
}
"
}
```

### References

* https://github.com/hashicorp/terraform-provider-google/issues/3950
* https://github.com/hashicorp/terraform-provider-google/issues/3657

**Comment by JacksonMaxfield** [comment]
Hey @rileykarson just wanted to see if there was any movement on this or if there was a chance at an updated timeline from goals to a sprint?

**Comment by rileykarson** [comment]
None at this time, sorry!

**Comment by maxwell-oroark** [comment]
This would be amazing. +1

**Comment by ybavn** [comment]
Need this soon

**Comment by tylerg-dev** [comment]
Hey folks, I added a first version of Firebase Rules (for Firestore) a few months ago, though I didn't notice this pre-existing issue.

Are you are still interested? . You'd need to setup a [Ruleset](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_ruleset) and a [Release](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_release) at the minimum.

Does that provide what you needed?

**Comment by JacksonMaxfield** [comment]
I did see those resources were available. I know this is the terraform repo but Pulumi has them also available. I haven't tried since I opened this bug: https://github.com/pulumi/pulumi-google-native/issues/196

However after I opened that pulumi issue I also opened a Firebase support ticket because I believed the bug to be not on terraform or pulumi side but on Firebase side. They confirmed that the bug was on their side but I haven't heard anything back since February 24:

> I am so sorry for the big delay, I was checking the status of the internal ticket related to your case. Terraform support for Rules has an open pull request in review, that seems to be blocked by other work in progress fixes, unfortunately, this is out of our control and once it gets solved, the engineering team can continue with the pending tasks if it were the case.

I will ping the support ticket and see if the bug was fixed on their side as well.

**Comment by JacksonMaxfield** [comment]
Update from Firebase support, seems like the bug still exists (or at least status of bug is unknown):

> I have checked the status of your bug and, though it has had some updates it has not been solved yet, however, it seems like the Terraform pull request has already been merged, so I have asked the engineering team for updates.

**Comment by flovouin** [comment]
Hi tylerg-dev,

Thanks for your message, I did miss the introduction of the two resources!
As you mentioned, the documentation could be a bit more thorough to help set up the rules. But after some investigation, I was able to successfully set up the rules in Terraform. Here are my findings:

**Authorization**
The `firebaserules.googleapis.com` endpoint requires to be either authenticated as a service account or to provide a billing project in the requests. I'm currently performing manual tests before moving things to the CI, and I was using end-user credentials. While this concept is widespread across Google services, I had never encountered any problem with the Google Terraform provider when using my own credentials. However in this case I had to add:

```hcl
user_project_override = true
billing_project       = "my-project"
```

to the provider configuration or set the `USER_PROJECT_OVERRIDE` and `GOOGLE_BILLING_PROJECT` environment variables to be allowed to make the requests. Is this the expected behaviour?

**Release name**
As you did mention in your last message, the name of the release should be one of the supported values, but nothing prevents a user from providing a different one. The [documentation](https://firebase.google.com/docs/reference/rules/rest/v1/projects.releases#Release) is also a bit dry on what are the possible values. I did eventually find the possible values in the [firebase-tools](https://github.com/firebase/firebase-tools/blob/8ed6b4062f86dcec57ea8818ecbf8154e5b17f1e/src/rulesDeploy.ts#L25) code, but that was a bit of an adventure. 😄
Maybe those values could be documented in the Terraform provider?

**400 Bad Request when the ruleset is still referenced**
Of course, a ruleset cannot be deleted if it is still referenced by a release. However experimenting with release names (before finding `cloud.firestore`) led me to create useless releases referencing obsolete rulesets.
When deleting the referenced rulesets (in Terraform), the only returned error was a `400` with a rather generic message (something like `"Request contains an invalid argument."`). While this is not the provider's fault, if we're sure that the provider issues correctly formatted requests, the ruleset still being referenced might be the only reason to get a `400`. Maybe the provider could hint at this reason when receiving a `400`?

**Use the ruleset ID in the release**
The [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_release) shows an example where the `ruleset_name` is recreated/formatted from the `name` ruleset property. While this is valid, it is actually simpler to pass the `id` of the ruleset directly (see below). Maybe this is something the documentation could show instead?

All in all, the two resources are already a big step forward and I can ditch my ugly `null_resource` that was deploying the rules up to now. So thanks for that!

Just for reference for others, this is was I ended up with:

```hcl
resource "google_firebaserules_ruleset" "firestore" {
  source {
    files {
      content     = var.security_rules
      name        = "firestore.rules"
      fingerprint = sha1(var.security_rules)
    }
  }
}

resource "google_firebaserules_release" "firestore" {
  name         = "cloud.firestore"
  ruleset_name = google_firebaserules_ruleset.firestore.id
}
```

**Comment by tylerg-dev** [comment]
> If you have access to the support ticket then I think you will see my reproduction of the bug regardless of pulumi or terraform. Pulumi (and now terraform) have been able to create the ruleset and release for a while but until you visit the Firebase web UI the ruleset and release aren't provisioned properly. I reproduced the bug both with terraform and with pulumi which is why I think its a bug on the firebase side. Anyway, I have a couple of support case numbers: Case 10146375 and Case 10142522

JacksonMaxfield@ - I looked into the mentioned issues, one was an AdminSDK issue, the other looked like the same authorization challenge flovouin@ raised.  I've left some comments for the Support folks.

**Comment by tylerg-dev** [comment]
> Hi tylerg-dev,
> 
> Thanks for your message, I did miss the introduction of the two resources! As you mentioned, the documentation could be a bit more thorough to help set up the rules. But after some investigation, I was able to successfully set up the rules in Terraform. Here are my findings:
> 
> **Authorization** The `firebaserules.googleapis.com` endpoint requires to be either authenticated as a service account or to provide a billing project in the requests. I'm currently performing manual tests before moving things to the CI, and I was using end-user credentials. While this concept is widespread across Google services, I had never encountered any problem with the Google Terraform provider when using my own credentials. However in this case I had to add:
> 
> ```terraform
> user_project_override = true
> billing_project       = "my-project"
> ```
> 
> to the provider configuration or set the `USER_PROJECT_OVERRIDE` and `GOOGLE_BILLING_PROJECT` environment variables to be allowed to make the requests. Is this the expected behaviour?
> 
> **Release name** As you did mention in your last message, the name of the release should be one of the supported values, but nothing prevents a user from providing a different one. The [documentation](https://firebase.google.com/docs/reference/rules/rest/v1/projects.releases#Release) is also a bit dry on what are the possible values. I did eventually find the possible values in the [firebase-tools](https://github.com/firebase/firebase-tools/blob/8ed6b4062f86dcec57ea8818ecbf8154e5b17f1e/src/rulesDeploy.ts#L25) code, but that was a bit of an adventure. smile Maybe those values could be documented in the Terraform provider?
> 
> **Importing an existing release** When defining Firestore rules, the release will most likely need to be imported the first time, as `cloud.firestore` probably already exists in the project if Firestore has already been used (or even just been activated?).
> 
> **400 Bad Request when the ruleset is still referenced** Of course, a ruleset cannot be deleted if it is still referenced by a release. However experimenting with release names (before finding `cloud.firestore`) led me to create useless releases referencing obsolete rulesets. When deleting the referenced rulesets (in Terraform), the only returned error was a `400` with a rather generic message (something like `"Request contains an invalid argument."`). While this is not the provider's fault, if we're sure that the provider issues correctly formatted requests, the ruleset still being referenced might be the only reason to get a `400`. Maybe the provider could hint at this reason when receiving a `400`?
> 
> **Use the ruleset ID in the release** The [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firebaserules_release) shows an example where the `ruleset_name` is recreated/formatted from the `name` ruleset property. While this is valid, it is actually simpler to pass the `id` of the ruleset directly (see below). Maybe this is something the documentation could show instead?
> 
> All in all, the two resources are already a big step forward and I can ditch my ugly `null_resource` that was deploying the rules up to now. So thanks for that!
> 
> Just for reference for others, this is was I ended up with:
> 
> ```terraform
> resource "google_firebaserules_ruleset" "firestore" {
>   source {
>     files {
>       content     = var.security_rules
>       name        = "firestore.rules"
>       fingerprint = sha1(var.security_rules)
>     }
>   }
> }
> 
> resource "google_firebaserules_release" "firestore" {
>   name         = "cloud.firestore"
>   ruleset_name = google_firebaserules_ruleset.firestore.id
> }
> ```

flovouin@ thank you for the well researched and thorough feedback.  

**Authorization**: My assumption is that you are using your own credentials via OAuth using 'gcloud auth application-default login' or something similar.  If so, the error is raised because gcloud does not operate on firebaserules at this time, so does not have the Rules API enabled on its Consumer Project.  When using your Consumer Project (via user-project-override) you almost certainly have the Rule API enabled.  This is likely to be a common challenge when dealing with resources not managed by gcloud.

**Release Name**: I'm working on getting updated documentation (including this suggestion) added.  In addition I've passed this feedback along to the API owners to see where improvements are feasible. 

**Importing an existing release**: If you are adding Terraform configuration to an existing project, you are correct you will most likely need to run 'terraform import ... ' for the Release resource.  

**400 Bad Request when the ruleset is still referenced**: I've passed this feedback along to the API owners as well.  I'd like to see if it is plausible to address in the API, as that would improved the experience of all Integrations.

**Use the ruleset ID in the release**: Using the Ruleset.id is an interesting solution.  It suggested to me a related change that will allow us to use both the long and short resource name (and updating documentation demonstrate both).  This means ruleset.id, ruleset.name, as well as manually constructed variants will all be accepted by the provider.

**Comment by melinath** [comment]
@tylerg-dev is there any work to do here or is this ticket completed?

**Comment by melinath** [comment]
Okay closing this issue - please feel free to open separate issues for any remaining change requests.
