### ISSUE TITLE
`google_secret_manager_secret_version` destroys secrets when replacing

### ISSUE THREAD

**Issue by achew22** [hashicorp/terraform-provider-google#8653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

When working with GCP secret manager, this plugin does a wonderful job of creating secrets, but I think it has a counter-intuitive behavior when replacing a secret. It destroys the old secret, permanently and irrecoverably removing any trace of it.

For this sample of code, pulled from [the docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version):

```hcl

resource "google_secret_manager_secret" "secret-basic" {
  secret_id = "secret-version"

  labels = {
    label = "my-label"
  }

  replication {
    automatic = true
  }
}


resource "google_secret_manager_secret_version" "secret-version-basic" {
  secret = google_secret_manager_secret.secret-basic.id

  secret_data = "secret-data"
}
```

Everything is great! The secret is created, you get a version 1 of the secret and all is well. Let's say that secret version can be referred to by `projects/123/secrets/secret-version/versions/1` My concern comes when you attempt to rotate that secret. For example, if you replace this snippet with:

```hcl

resource "google_secret_manager_secret" "secret-basic" {
  secret_id = "secret-version"

  labels = {
    label = "my-label"
  }

  replication {
    automatic = true
  }
}


resource "google_secret_manager_secret_version" "secret-version-basic" {
  secret = google_secret_manager_secret.secret-basic.id

  secret_data = "new-data" # Note that this is different
}
```

I, as a lay-person in the subject would have expected the plan to suggest replacement (it did) since this is a versioned asset. When I applied it, it did something unexpected. It created `projects/123/secrets/secret-version/versions/2` but then it transitioned the version 1 to a state of `DESTROYED` which, as the name implies, completely destroys the secret! GCP Secrets Manager does have a 3rd state for secrets called `DISABLED`, which is what I was expecting it to transition to.

My next thought was that I should actually be defining each version of the secret. As the value changes, it is expected that I would have one entry for each version I would like to keep around, but I don't believe it's possible to specify the version of the secret that you're managing, it is part of the implicit state of the `google_secret_manager_secret_version` object.

Would it be possible to do one of a couple of things:

1. I think the most likely situation here is that I'm holding it wrong. Could you explain how to use `google_secret_manager_secret_version` so that I am less surprised by its behavior? I'd be happy to rewrite anything you say on this front and put it into documentation.
2. Modify the deletion to default to not destroy, but instead to disable and add a warning in the UI that says "this disables instead of destroys by default".
3. Add a `version` field to the `google_secret_manager_secret_version` resource so that the user can control when and how deletion happens.

### New or Affected Resource(s)

* `google_secret_manager_secret_version`

### Potential Terraform Configuration

I think that there should be a new attribute defaulting to false:

```hcl
resource "google_secret_manager_secret_version" "secret-version-basic" {
  secret = google_secret_manager_secret.secret-basic.id

  secret_data = "secret-data"
  destroy_on_delete = true # protect the secret from being destroyed unless the user opts out
}
```

**Comment by slevenick** [comment]
I think this question comes down to how Terraform handles resources when their blocks are removed from the config as well as how the Secret/SecretVersion API works.

When you change the secret_data value in your config you are essentially telling Terraform to destroy the old version & recreate a new version as you identified. This is intended and seems to be working as you expect except that the old version is destroyed rather than just disabled. We choose to destroy the old version because in general we try not to leave unmanaged resources after Terraform destroys. This has a tendency to cause projects to fill up with forgotten resources when Terraform is used frequently. We *could* add a forget-on-delete functionality, but I would prefer not to unless there is a very compelling use case. You can handle this manually by using the `terraform state rm` command: https://www.terraform.io/docs/cli/commands/state/rm.html

You can set the secret version to [disabled manually](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret_version#enabled), and I would recommend this if you want to keep the secret data around.

Specifying the version seems to make sense from a user's perspective, but the way the API is implemented makes `version` an unsettable field. When we create a new secret version it gets an auto-incremented number, so allowing a user to set this field would not be possible. 

But, I think what you are trying to accomplish can be done by making a separate `google_secret_manager_secret_version` resource for each different secret data you want to store. Like the following:
```hcl
resource "google_secret_manager_secret" "secret-basic" {
  secret_id = "secret-version"

  labels = {
    label = "my-label"
  }

  replication {
    automatic = true
  }
}

resource "google_secret_manager_secret_version" "secret-version-one" {
  secret = google_secret_manager_secret.secret-basic.id

  secret_data = "old-data"
}

resource "google_secret_manager_secret_version" "secret-version-two" {
  secret = google_secret_manager_secret.secret-basic.id

  secret_data = "new-data" # Note that this is different
}
```

This allows you to add new secret versions while keeping around the old ones in your Terraform config. It will cause your configs to grow, but I think that the right way to handle Terraform-managed resources is to keep track of them until you actually want to delete them. Does this seem like it would work for you?

**Comment by achew22** [comment]
@slevenick, thanks for your thoughtful response and apologies for my slow response.

I think your solution is totally reasonable and a fair assessment of the situation.

I would like to point out that `terraform-provider-google`, in a couple of places where data loss is irreversible, has decided that this is not an acceptable risk. In my cursory skimming of the repo I found at least two resources where the risk of data loss was deemed to be high enough that an extra `force_destroy` argument was added to the resource. 

* `google_storage_bucket`
* `google_dns_managed_zone`

I did go read the implementation code for each of those flags and I guess an alternate explanation for the flag is that due to proclivities of the GCS and Google DNS APIs force you to delete all the subobjects of those resources before they can be destroyed. However, the perceived effect, as an end user, is that those resource types are dangerous enough that they have special protections.

Obviously, I'm just some guy on the internet. Thanks for giving it a think.

**Comment by slevenick** [comment]
Yeah, there are cases where we have added extra deletion protection. This is normally for cases where accidental deletion is very painful, like databases or other resources that contain important state.

I don't think that secrets are a case of this? The config itself contains the secret data, so it cannot really be "lost" like data in a database.

The feature you are asking for is to allow Terraform to effectively "forget" about a resource without deleting it in GCP, which we generally try to discourage. I would especially discourage making this the default behavior, as an unsuspecting user could accidentally end up leaving around a bunch of these resources

**Comment by achew22** [comment]
I hadn't considered that the terraform state will almost certainly hold the value. I think that is the last nail in the coffin for this idea.

Thanks so much for the spirited conversation!
