### ISSUE TITLE
Failed to pull composer-agent image when creating Google Composer environment

### ISSUE THREAD

**Issue by tfcacos** [hashicorp/terraform-provider-google#8676]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.14.6
provider registry.terraform.io/hashicorp/google v3.54.0

### Affected Resource(s)

google_composer_environment

Setting up a Composer environment with Terraform fails with the following error:

_Http error status code: 400
Http error message: BAD REQUEST
Errors in: [Web server]; Error messages:
	Creation of airflow web server version failed. This may be an intermittent issue of the App Engine service. You may retry the operation later.
{"ResourceType":"appengine.v1.version","ResourceErrorCode":"504","ResourceErrorMessage":"Your deployment has failed to become healthy in the allotted time and therefore was rolled back. If you believe this was an error, try adjusting the 'app_start_timeout_sec' setting in the 'readiness_check' section."}_

A closer look into the Google log files reveals the following error:

_Failed to pull image "europe-docker.pkg.dev/cloud-airflow-releaser/composer-agent/composer-agent:cloud_composer_service_2021-02-28-RC2": rpc error: code = Unknown desc = Error response from daemon: Get https://europe-docker.pkg.dev/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"_

So it seems, that the composer image just cannot be pulled. However, when creating the Composer environment with the exact same settings using the GUI, there is no issue with the images. Apparently when using the GUI, the default repository to this image is being used (which would be eu.gcr.io/...). So, for some reason, Terraform tries to pull the image from a different repository. The google_composer_environment resource also does not contain an attribute allowing to overwrite the repository path.

**Comment by edwardmedia** [comment]
@tfcacos can you share your config code and the full debug log?

**Comment by edwardmedia** [comment]
@tfcacos is this still an issue?

**Comment by tpolekhin** [comment]
@edwardmedia we hit this issue with Terraform provisioning Composer environment as well. I couldn't find logs that @tfcacos mentioned with the image pull error, likely because im not really sure where to look for them, but symptoms are the same - terraform fail with the error:
```
Error: Error waiting to create Environment: Error waiting for Creating Environment: Error code 3, message: Http error status code: 400
Http error message: BAD REQUEST
Errors in: [Web server]; Error messages:
	Creation of airflow web server version failed. This may be an intermittent issue of the App Engine service. You may retry the operation later.
{"ResourceType":"appengine.v1.version","ResourceErrorCode":"504","ResourceErrorMessage":"Your deployment has failed to become healthy in the allotted time and therefore was rolled back. If you believe this was an error, try adjusting the 'app_start_timeout_sec' setting in the 'readiness_check' section."}
```

I need to notice that this started Mar 16 2021 and still ongoing, but this issue only occurs on 2 of our environments(projects) that use the same Shared VPC. Another 2 environments(projects) that both use different Shared VPC deploy without any issues.
Terraform code is exactly the same between the environments, except for service accounts and network IDs.
This code was not modified for a while and was working fine before.

I was able to deploy a Composer environment manually using Cloud Console providing the same deployment parameters that we have in the terraform, so for now im not really sure what could cause that behavior.

If i can provide any additional information let me know.
I've also commented on a bug report for the Composer https://issuetracker.google.com/issues/182884052

**Comment by tpolekhin** [comment]
We fixed the issue by providing Composer EKS nodes egress internet access.

It seems like with new Composer release they now host docker images in Artifact Registry `us-docker.pkg.dev` instead of Container Registry `us.gcr.io`, and for some reason this Artifact Registry is not available (or not configured) for Private Service Access that we've been using for all our environments.

**Comment by edwardmedia** [comment]
@tpolekhin I am glad you have found the fix. Let's close this issue now, and keep eye on the deployment. If the problem show up again and you feel something that we can do in the provider, feel free to reopen the issue.
