### ISSUE TITLE
Beta provider versioning

### ISSUE THREAD

**Issue by upodroid** [hashicorp/terraform-provider-google#8749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The google provider implements many GCP features in preview/beta. Beta APIs have fields that change during the beta. 

I would like to see field removals/renames during minor versions which I know is against SemVer and [Terraform guidelines](https://www.terraform.io/docs/extend/best-practices/versioning.html#versioning-specification). SemVer and beta APIs are inherently incompatible concepts and I don't think anyone else is implementing a beta + GA provider.

I promoted `google_billing_budget` to GA recently and it had a changed field which we renamed internally and accrued a small technical debt but more importantly it generated a number of bug reports for cases that we didn't anticipate in testing and is not present when the resource is created from scratch with the GA provider. 

#8241 #8228 #8238

*This product or feature is covered by the Pre-GA Offerings Terms of the Google Cloud Platform Terms of Service. Pre-GA products and features may have limited support, and changes to pre-GA products and features may not be compatible with other pre-GA versions. For more information, see the launch stage descriptions.*

Given this notice, it is fair to assume:
- Preview products have alot of limitations around support from Google.
- Backward incompatible changes are present and fields change during beta to GA promotion.
- Beta to GA transition is likely to be buggy given Google's poor documentation around API changes once it goes GA.
- Terraform users should be pinning their provider versions. Beta provider should be a fast moving provider and users should be keeping with any deprecations and breaking changes that get introduced. It is tradeoff between bleeding edge features and stability.

I don't think we can do much in v3, but I would like to see this in the next major release where the beta provider doesn't follow SemVer with regards to breaking changes. We are also stripping beta APIs from the GA provider so it should be easier to implement.

**Comment by rileykarson** [comment]
Hey! We reviewed the list of proposed breaking changes and accepted/rejected them based on a few factors including cost (in effort), value to users, and disruption to users. This one and #7332 both got rejected because we felt the disruption to users wasn't worth the value- for example, here,]\ we _could_ change the policy around beta resources/fields and breaking changes, but felt that it wasn't worth it.

The problem is, we've supported `google-beta` as a stable surface for years. We'd originally intended to break it when the API broke but haven't- and doing so now would break the assumptions users make about the stability of the provider. We'd save a bit of complexity, and some work in relatively small number of cases of major API breakage (`google_billing_budget` was a particularly bad one) but would also put customers at risk of breaking between minor versions, and possibly getting into unrecoverable states.

We receive reports from users regularly where they aren't even running `terraform plan` prior to `terraform apply`, and have seen folks lose disks / databases / gke clusters (which are effectively databases) when we didn't fully encapsulate the state a user's resources can be in (a particularly sticky case are resources that have a field set if they were created after a certain date, and the field being unset means the same thing as that default.) The risk we'd take on by making breakages in `google-beta` would almost certainly lead to more _very_ negative outcomes from those users.
