### ISSUE TITLE
while creating vm in gcp i am getting below error 

### ISSUE THREAD

**Issue by lankakiran** [hashicorp/terraform-provider-google#9157]
![image](https://user-images.githubusercontent.com/48472282/118400151-0c188480-b67e-11eb-9835-9b3f79ae7907.png)
[](url)

module "google_instance_example_new" {​​​​​
source    = "../../google_instance"  
project = "mtech-wms-oms-poc" 
 zone = "us-central1-a"
  instance_name = "vm-macys-092"  
role = "roles/compute.osLogin"  
member = "user:sai.prasad.rao@macys.com"
}​​​​​

│    7: resource "google_compute_instance_iam_member" "default" {

can you please help on this issue

**Comment by edwardmedia** [comment]
@lankakiran you are running a module. The code you provided does not tell us how you want to config. You may want to check with the module owners to see if they can help. 

Here is the doc about the resource [google_compute_instance_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_iam#google_compute_instance_iam_member) and its examples that might help you debug

You can also post the config of individual resources and I can help take a look. In the meantimes, post the debug log

**Comment by edwardmedia** [comment]
@lankakiran  is this still an issue?

**Comment by lankakiran** [comment]
Dear Edward ,

I am getting still same issue i don't know what happened can you please
help to me .

Thanks & Regards
Kiran

**Comment by edwardmedia** [comment]
@lankakiran sure. But the info you provided is not enough. Instead of module, can you execute [google_compute_instance_iam_member](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_iam#google_compute_instance_iam_member)  directly? There are several examples in the [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_iam#google_compute_instance_iam_member)

If not, can you post the debug log by adding the env variables (**export TF_LOG=DEBUG**)?

**Comment by edwardmedia** [comment]
@lankakiran closing the issue now based on no response received.
