### ISSUE TITLE
Flakey test: TestAccNotebooksInstance_notebookInstanceFullExample

### ISSUE THREAD

**Issue by melinath** [hashicorp/terraform-provider-google#9244]
### Affected Resource(s)

* google_notebooks_instance

This test seems to be flakey due to state/update_time issues. Failed 3 times in the last week. https://ci-oss.hashicorp.engineering/test/1861864166893878271?currentBuildTypeId=GoogleCloud_ProviderGoogleCloudGoogleProject&currentProjectId=GoogleCloud&branch=%3Cdefault%3E&expandedTest=id%3A245071%2Cbuild%3A%28id%3A188774%29

**Comment by rileykarson** [comment]
notes: this is likely eventual consistency from the API

**Comment by mitj04** [comment]
b/261686781

**Comment by mitj04** [comment]
It looks like that it [failed](https://ci-oss.hashicorp.engineering/test/1861864166893878271?currentProjectId=GoogleCloud&branch=%3Cdefault%3E&expandedTest=id%3A205284%2Cbuild%3A%28id%3A340939%29) only for once in the Test History which was of error `ImportStateVerify attributes not equivalent` for the `update_time`. Later it was passing till the latest build since 28th Sept, 2022.

**Comment by roaks3** [comment]
Considering this resolved, because I'm not seeing any failures anymore, and it's possible this was fixed on the API side. The `update_time` should not be impacted by a Read operation, and this test does not perform an update.
