### ISSUE TITLE
ressource google_iap_client is missing attributes "Authorised JavaScript origins" and "Authorised redirect URIs"

### ISSUE THREAD

**Issue by tzahari** [hashicorp/terraform-provider-google#9267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

To create a OAuth Web Client the attributes for 
* Authorised JavaScript origins
* Authorised redirect URIs
are missing.

### New or Affected Resource(s)

* google_iap_client

### Potential Terraform Configuration

```tf
resource "google_iap_brand" "brand" {
  support_email     = "support@email"
  application_title = "Web Login"
  project           = "web auth"
}

resource "google_iap_client" "client" {
  brand        = google_iap_brand.brand.id
  display_name = "Client ID"
  javascript_uri = [
    "https://uri1/",
    "https://uri2/"
  ]
  redirect_uri = [
    "https://uri1/",
    "https://uri2/"
  ]
}
```

### References

*

**Comment by slevenick** [comment]
Unfortunately I don't believe this will be possible.

Terraform uses the REST API for IAP client which is documented here: https://cloud.google.com/iap/docs/reference/rest/v1/projects.brands.identityAwareProxyClients

You will notice that none of these fields appear in the documentation, and I don't believe they will be added anytime soon. I believe this is an intentional choice made by the API team.

See my previous response on a similar topic here: https://github.com/hashicorp/terraform-provider-google/issues/6074#issuecomment-639808102
