### ISSUE TITLE
resourceInUseByAnotherResource when TF is performing what seems like an unnecessary update/change to a google_compute_resource_policy resource

### ISSUE THREAD

**Issue by jdstone** [hashicorp/terraform-provider-google#9435]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Summary

This issue showed up after upgrading to Terraform v0.15.5 and TF Google provider v3.70.0.  No changes were made to this resource within our TF configuration.  I even tried importing the resource using the `terraform import` command, and after a successful import, Terraform still complained that a change needed to be made as shown below.  Note that the `description` matches exactly what is in GCP web console.

```tf
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # google_compute_resource_policy.nightly-snapshot must be replaced
-/+ resource "google_compute_resource_policy" "nightly-snapshot" {
      - description = "Nightly snapshots with 14 day retention" -> null # forces replacement
      ~ id          = "projects/example-production/regions/us-central1/resourcePolicies/nightly-snapshot" -> (known after apply)
        name        = "nightly-snapshot"
      ~ project     = "example-production" -> (known after apply)
      ~ region      = "https://www.googleapis.com/compute/v1/projects/example-production/regions/us-central1" -> "us-central1"
      ~ self_link   = "https://www.googleapis.com/compute/v1/projects/example-production/regions/us-central1/resourcePolicies/nightly-snapshot" -> (known after apply)

      ~ snapshot_schedule_policy {


          ~ snapshot_properties {
              - labels            = {} -> null
              - storage_locations = [] -> null
                # (1 unchanged attribute hidden)
            }
            # (2 unchanged blocks hidden)
        }

      - timeouts {}
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_compute_resource_policy.nightly-snapshot: Destroying... [id=projects/example-production/regions/us-central1/resourcePolicies/nightly-snapshot]
╷
│ Error: Error when reading or editing ResourcePolicy: googleapi: Error 400: The resource_policy resource 'projects/example-production/regions/us-central1/resourcePolicies/nightly-snapshot' is already being used by 'projects/example-production/zones/us-central1-a/disks/prod-bastion-01', resourceInUseByAnotherResource
```

### Terraform Version

```tf
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.73.0
+ provider registry.terraform.io/hashicorp/google-beta v3.73.0
```

### Affected Resource(s)

* google_compute_resource_policy

### Terraform Configuration Files

```tf
resource "google_compute_resource_policy" "nightly-snapshot" {
  name   = "nightly-snapshot"
  region = "us-central1"
  snapshot_schedule_policy {
    retention_policy {
      max_retention_days    = 14
      on_source_disk_delete = "KEEP_AUTO_SNAPSHOTS"
    }

    schedule {
      daily_schedule {
        days_in_cycle = 1
        start_time    = "12:00"
      }
    }

    snapshot_properties {
      guest_flush = false
    }
  }
}
```

### Debug Output

https://gist.github.com/jdstone/d96b4b18f9c87e3456ab2b6a2f31b9d0

### Panic Output

N/A

### Expected Behavior

Since no change was made to GCP or the Terraform configuration files, the resource should not need to be changed updated/replaced/destroyed.

### Actual Behavior

Terraform wants to replace the resource, which of course fails because the resource is in use by another resource.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* #8459

**Comment by edwardmedia** [comment]
@jdstone how do you manage the disk `prod-bastion-01`? It appears it is not in the same plan/state with `google_compute_resource_policy`. Due to the relationship of these two resources, you can't do anything for the `policy` without deleting the disk first. 

@ScottSuarez this is an interesting use case. `google_compute_resource_policy` does not support `update`. How do you want to address this issue?

**Comment by ScottSuarez** [comment]
There isn't much we can do here. What I think is happening is someone added the description to the resource outside of terraform. Maybe somewhere in ui and now it's returning that description to us. Terraform doesn't have the description in the config and is trying to reconcile it by deleting the resource and creating a new one. This is because the api we use to manage this resource doesn't have an update method. So there is no way we can reconcile the difference otherwise. If you add the description thats being returned in the rest response to the terraform config that will resolve the difference and terraform won't try to delete the resource. There is nothing we can do here unfortunately. If the rest api enables updating then we could potentially support it.

https://gist.github.com/jdstone/d96b4b18f9c87e3456ab2b6a2f31b9d0#file-terraform_debug_log_google_compute_resource_policy-nightly-snapshot_20210623-txt-L6691
https://cloud.google.com/compute/docs/reference/rest/v1/resourcePolicies

**Comment by jdstone** [comment]
@ScottSuarez Oh my goodness.  I feel like such an idiot for missing not seeing that the `description` was not in the Terraform config.  I apologize.  Feel free to close this issue.

**Comment by ScottSuarez** [comment]
no worries. It happens!
