### ISSUE TITLE
use previous vcr run if no changes to downstream pr

### ISSUE THREAD

**Issue by ScottSuarez** [hashicorp/terraform-provider-google#9775]
Sometimes the vcr will kick off, complete but the cloudbuild op will timeout so the subsequent vcr steps of rerunning tests that failed in replaying mode never gets initiated. In this case the user can rerun the tests using `/gcbrun` but the generate-diff function will blindly rerun the same suite, and possibly encounter the same issue. I encourage our CI to intelligently detect if the previous vcr ran and completed successfully then only running tests that failed therein. This way we can save time on CI checkin from timed out cb ops.

**Comment by rileykarson** [comment]
triage note: This is a possible solution to some of the problems we have w/ the Magician, but we could consider others:

- TeamCity callbacks?

**Comment by melinath** [comment]
I thought I had looked into the callback option but I'm having trouble finding any notes on it. I think it would be better if we could pull it off, since it would be more reliable & would hypothetically require less human intervention. But it might be more compliated to implement, since it would involve basically adding a line to the TeamCity test run script that calls a webhook we designate, then kick off a build on our end based on that endpoint. This might be size/l rather than size/m.

@megan07 do you know how easy / feasible it would be to modify the script in TeamCity?

**Comment by rileykarson** [comment]
Closing as stale- I think that the issue as raised is still present, but the solution presented in the issue body is outdated.
