### ISSUE TITLE
v4.0.0 Projected Date

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-google#9830]
Can you please update the projected date for v4.0.0 in https://github.com/hashicorp/terraform-provider-google/milestone/8? It currently says it is due in less than a month but has 44 open and 0 closed issues so that doesn't look accurate

**Comment by rileykarson** [comment]
We've bumped the release a few times and probably won't hit the date on that milestone, but haven't projected a replacement yet. It's worth noting, not every issue under that milestone will happen- they're currently labelled `4.0.0-under-review`, and only ones we move the `4.0.0-accepted` will actually get done in `4.0.0` with the rest getting closed or moved to `5.0.0`.

`4.0.0` is likely to be an extremely small release compared to `2.0.0` or `3.0.0`, making only a limited number of breaking changes.

**Comment by rileykarson** [comment]
Closing as outdated since `4.0.0` has been out a while. Note that we're fairly early in the planning process for `5.0.0` (all current issues are still in an "under consideration" milestone: https://github.com/hashicorp/terraform-provider-google/milestone/69) but we're aiming for the target date with more precision: https://github.com/hashicorp/terraform-provider-google/milestone/89

That's not to say it's guaranteed to be on that date- I think it's a Friday- but we're planning to keep within ~a week after that date barring some exceptional disruption.
